fix(Menu toggle): Passed aria label prop value to typeahead variant
patternfly/patternfly-react pull request #10084
Opened 2024-02-13 21:47 UTC by tlabaj

**What**: Closes #9976

2024-02-13 21:52 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10084.surge.sh

2024-02-15 13:24 UTC, thatblindgeye requested changes
Just needs several examples updated to pass the aria-label in to typeahead, one on the Menu Toggle page and 5 on the Select page

2024-02-15 14:20 UTC, thatblindgeye approved these changes

2024-02-16 19:58 UTC, mfrances17 approved these changes
lgtm 👍

2024-02-19 15:28 UTC, merged

2024-02-19 15:41 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.3.0-prerelease.3
 - @patternfly/react-core@5.3.0-prerelease.2
 - @patternfly/react-docs@6.3.0-prerelease.4
 - @patternfly/react-drag-drop@5.3.0-prerelease.2
 - demo-app-ts@5.1.1-prerelease.76
 - @patternfly/react-table@5.3.0-prerelease.2

Thanks for your contribution! :tada: