feat(MenuToggle): consumed Penta updates
patternfly/patternfly-react pull request #10097
Opened 2024-02-21 15:16 UTC by thatblindgeye

**What**: Closes #9986 

This also bumps the Core versions

**Additional issues**:

2024-02-21 15:26 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10097.surge.sh

2024-02-26 18:16 UTC, mattnolting requested changes
Looks good, saw one bug

2024-02-27 16:58 UTC, kmcfaul approved these changes
lgtm just an extra space in the docs, but not a blocker

2024-02-27 16:58 UTC, kmcfaul commented on packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
> +When a user selects a toggle, it becomes expanded and is styled with a blue underline. To flag expanded toggles, and apply expanded styling, use the `isExpanded` property .
Extra space at the end of the line

2024-02-28 16:03 UTC, mattnolting approved these changes
Awesome! Great work, thank you! LPTM

2024-03-04 21:11 UTC, wise-king-sullyman approved these changes

2024-03-12 19:19 UTC, andrew-ronaldson approved these changes
LGTM

2024-03-12 20:38 UTC, merged

2024-03-12 20:52 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.0.0-alpha.41
 - @patternfly/react-core@6.0.0-alpha.41
 - @patternfly/react-docs@7.0.0-alpha.43
 - @patternfly/react-drag-drop@6.0.0-alpha.22
 - @patternfly/react-integration@6.0.0-alpha.22
 - demo-app-ts@5.1.1-alpha.40
 - @patternfly/react-table@6.0.0-alpha.41

Thanks for your contribution! :tada: