Descriptionlist complex content demo
patternfly/patternfly-react pull request #10237
Opened 2024-04-02 17:39 UTC by ajaypratap003

**What**: Closes https://github.com/patternfly/patternfly-react/issues/10228
Descriptionlist complex content demo

**Additional issues**:

2024-04-18 18:35 UTC, tlabaj reviewed
@ajaypratap003 this demo does not match any core demos and It is not needed.

2024-04-22 13:32 UTC, ajaypratap003 commented
closing this PR as this demo does not match any core demos and It is not needed.

2024-04-23 21:16 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10237.surge.sh

2024-04-29 17:56 UTC, thatblindgeye requested changes
Comment about imports below, but also some smaller updates needed to be closer to the [core complex example](https://www.patternfly.org/components/description-list/html-demos/complex-content/)

2024-04-29 17:56 UTC, thatblindgeye commented on packages/react-core/src/demos/DescriptionList/DescriptionList.md
> +import BarsIcon from '@patternfly/react-icons/dist/esm/icons/bars-icon';
The imports here just need to be cleaned up to remove things that aren't actually being used in this demo.

2024-05-08 15:10 UTC, kmcfaul commented
@tlabaj This PR was closed and reopened, do we still want to add this demo?

2024-05-08 15:52 UTC, andrew-ronaldson commented
If we were to keep this demo I'd want to click it back to design. The layout is a bit off in my mind.

2024-11-13 21:21 UTC, tlabaj commented
@andrew-ronaldson should the core review be removed and we close this PR?

2025-01-08 13:45 UTC, thatblindgeye commented
Closing this PR and linked issue out for now as the demo itself is going to be shuffled back to design. We can open a new issue and PR once things move forward from there.

2025-01-08 13:45 UTC, closed without merging