Masthead: add demo that includes horizontal nav
patternfly/patternfly-react pull request #10241
Opened 2024-04-03 12:42 UTC by ajaypratap003

**What**: Closes https://github.com/patternfly/patternfly-react/issues/6826
Masthead: add demo that includes horizontal nav

**Additional issues**:

2024-04-03 12:48 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10241.surge.sh

2024-04-22 16:31 UTC, wise-king-sullyman reviewed
Looks great!

One question I have, I wonder if we would want to remove all of the logic for the search input and the favoriting and everything? It seems like it isn't really the focus of this demo and it seems to take up about half of the file.

2024-04-23 13:49 UTC, thatblindgeye requested changes

2024-04-23 13:49 UTC, thatblindgeye commented on packages/react-core/src/demos/Masthead.md
> +### Masthead with horizontal nav
Can we just update this and the above demo name to omit the "Masthead" text?

2024-04-23 13:49 UTC, thatblindgeye commented on packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
> +      </MastheadToggle>
We don't need this MastheadToggle

2024-04-23 13:49 UTC, thatblindgeye commented on packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
> +      aria-label="Toggle"
```suggestion
      aria-label="Applications"
```

2024-04-24 20:09 UTC, tlabaj commented
@ajaypratap003 this demo was recently added to the v6 branch.  Perhaps you could cherry pick that commit, or you could make sure they align.

2024-04-25 11:08 UTC, ajaypratap003 commented
> @ajaypratap003 this demo was recently added to the v6 branch. Perhaps you could cherry pick that commit, or you could make sure they align.

@tlabaj Can you please share the commit which is related to this PR

2024-04-25 13:55 UTC, tlabaj commented
> > @ajaypratap003 this demo was recently added to the v6 branch. Perhaps you could cherry pick that commit, or you could make sure they align.
> 
> @tlabaj Can you please share the commit which is related to this PR

@ajaypratap003 Nevermind.  I was mistaken.  it was a Nav example that was added.

2024-04-25 13:59 UTC, thatblindgeye approved these changes

2024-04-26 16:58 UTC, ajaypratap003 commented
@tlabaj Can you please merge this PR if everything look good.

2024-04-30 17:34 UTC, mattnolting requested changes
Nice work! Looks like you need to add `toolbar` to `.pf-v5-c-masthead__content`.

<img width="384" alt="Screenshot 2024-04-30 at 1 32 47 PM" src="https://github.com/patternfly/patternfly-react/assets/5385435/f60e5885-e2e2-49b3-8fd3-848548f258dc">

2024-05-07 12:27 UTC, ajaypratap003 commented
> Nice work! Looks like you need to add `toolbar` to `.pf-v5-c-masthead__content`.
> 
> <img alt="Screenshot 2024-04-30 at 1 32 47 PM" width="384" src="https://private-user-images.githubusercontent.com/5385435/326919672-f60e5885-e2e2-49b3-8fd3-848548f258dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODMxNzksIm5iZiI6MTcxNTA4Mjg3OSwicGF0aCI6Ii81Mzg1NDM1LzMyNjkxOTY3Mi1mNjBlNTg4NS1lMmUyLTQ5YjMtOGZkMy04NDg1NDhmMjU4ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTE1NDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWVlMTMxYjAzNzU2OTc2MGQ0Njc4NmE5NTUwNjM4MjcyZTA1ZWM0N2I0ZDdkYjhjYjE4ZjNhMTVmZDIyZTNhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xQsVLb3BMVrz42FimkEoQH_IFU1Qe3-zenhjoqX3Dkw">

@mattnolting Sorry, I don't get this point. Can you please describe bit more

2024-05-08 15:13 UTC, kmcfaul approved these changes
lgtm

@mattnolting Can you explain a bit more what your requested change is? The masthead content does contain the toolbar.

2024-05-08 16:45 UTC, mattnolting commented
@kmcfaul @ajaypratap003 
From: https://www.patternfly.org/components/masthead/html-demos/horizontal-nav/

![Screenshot 2024-05-08 at 12 44 27 PM](https://github.com/patternfly/patternfly-react/assets/5385435/6fc5b910-896a-4d69-82cf-1be4d3357443)

2024-05-08 18:22 UTC, mattnolting requested changes
`nav` goes inside a `toolbar__item` with the class `pf-m-overflow-container`

**Current**

<img width="711" alt="Screenshot 2024-05-08 at 2 20 31 PM" src="https://github.com/patternfly/patternfly-react/assets/5385435/ff5276eb-2e27-43d7-81fa-ac949eb2e76f">



**update**
<img width="731" alt="Screenshot 2024-05-08 at 2 20 19 PM" src="https://github.com/patternfly/patternfly-react/assets/5385435/dab29669-e7ba-49f6-97f6-50688f48a09a">

2024-05-08 18:28 UTC, ajaypratap003 commented
> `nav` goes inside a `toolbar__item` with the class `pf-m-overflow-container`
> 
> **Current**
> 
> <img alt="Screenshot 2024-05-08 at 2 20 31 PM" width="711" src="https://private-user-images.githubusercontent.com/5385435/328997186-ff5276eb-2e27-43d7-81fa-ac949eb2e76f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTI4MjksIm5iZiI6MTcxNTE5MjUyOSwicGF0aCI6Ii81Mzg1NDM1LzMyODk5NzE4Ni1mZjUyNzZlYi0yZTI3LTQzZDctODFmYS1hYzk0OWViMmU3NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTgyMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFjZDY4Mjc4MjZmMTQ3MDJjNzNkODBkNjRjNTkzMWY3M2IwMDAyYjExMjUxZGMyZjJjMDQ3NTNiNWFjYjFiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DA1y9_WRxPdIgoHzBpZUHjZu3IBfgXOP1NizxL0NZVs">
> **update** <img alt="Screenshot 2024-05-08 at 2 20 19 PM" width="731" src="https://private-user-images.githubusercontent.com/5385435/328997229-dab29669-e7ba-49f6-97f6-50688f48a09a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTI4MjksIm5iZiI6MTcxNTE5MjUyOSwicGF0aCI6Ii81Mzg1NDM1LzMyODk5NzIyOS1kYWIyOTY2OS1lN2JhLTQ5ZjYtOTdmNi01MDY4OGY0OGEwOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTgyMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE4ZGU3M2JhODBmZjE5MDZmYWE4Nzc4ZDg1NjM0OTFlNmQwZWUyMDZlMDY2ODhhN2IzNDg2NmIxMmRhNGFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KMiLTDQYyuu6LT0H-zxyA5u_z2I2FppPLq1POTnD7_o">

nav is already inside toolbar_item. this is the latest commit https://github.com/patternfly/patternfly-react/pull/10241/commits/525f4a7b7b89695cc40fc1a4d7fac8d79aa6ce00

2024-05-14 13:32 UTC, mattnolting commented
> > `nav` goes inside a `toolbar__item` with the class `pf-m-overflow-container`
> > **Current**
> > <img alt="Screenshot 2024-05-08 at 2 20 31 PM" width="711" src="https://private-user-images.githubusercontent.com/5385435/328997186-ff5276eb-2e27-43d7-81fa-ac949eb2e76f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTI4MjksIm5iZiI6MTcxNTE5MjUyOSwicGF0aCI6Ii81Mzg1NDM1LzMyODk5NzE4Ni1mZjUyNzZlYi0yZTI3LTQzZDctODFmYS1hYzk0OWViMmU3NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTgyMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFjZDY4Mjc4MjZmMTQ3MDJjNzNkODBkNjRjNTkzMWY3M2IwMDAyYjExMjUxZGMyZjJjMDQ3NTNiNWFjYjFiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DA1y9_WRxPdIgoHzBpZUHjZu3IBfgXOP1NizxL0NZVs">
> > **update** <img alt="Screenshot 2024-05-08 at 2 20 19 PM" width="731" src="https://private-user-images.githubusercontent.com/5385435/328997229-dab29669-e7ba-49f6-97f6-50688f48a09a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTI4MjksIm5iZiI6MTcxNTE5MjUyOSwicGF0aCI6Ii81Mzg1NDM1LzMyODk5NzIyOS1kYWIyOTY2OS1lN2JhLTQ5ZjYtOTdmNi01MDY4OGY0OGEwOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTgyMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE4ZGU3M2JhODBmZjE5MDZmYWE4Nzc4ZDg1NjM0OTFlNmQwZWUyMDZlMDY2ODhhN2IzNDg2NmIxMmRhNGFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KMiLTDQYyuu6LT0H-zxyA5u_z2I2FppPLq1POTnD7_o">
> 
> nav is already inside toolbar_item. this is the latest commit [525f4a7](https://github.com/patternfly/patternfly-react/commit/525f4a7b7b89695cc40fc1a4d7fac8d79aa6ce00)

Still can't see these. 
```
This private-user-images.githubusercontent.com page can’t be found
```

2024-06-03 15:40 UTC, mattnolting reviewed
Almost there, need to include nav in a single toolbar

2024-06-03 15:40 UTC, mattnolting commented on packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
> +        </ToolbarItem>
As only a single toolbar should be used, this needs to be moved to line 234

2024-06-03 15:40 UTC, mattnolting commented on packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
> +        </ToolbarItem>
```suggestion
        </ToolbarItem>
        <PageHorizontalNav />

```

2024-06-03 15:40 UTC, mattnolting commented on packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
> +      <ToolbarContent>
```suggestion
```

2024-06-03 15:40 UTC, mattnolting commented on packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx
> +    </Toolbar>
```suggestion
```

2024-06-10 14:21 UTC, mattnolting approved these changes
Great work! Looks like you got it all 👍

2024-06-10 14:32 UTC, merged