feat(Toggle group): Add support for icon position
patternfly/patternfly-react pull request #10291
Opened 2024-04-19 19:51 UTC by tlabaj

**What**: Closes #10059

2024-04-19 19:56 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10291.surge.sh

2024-04-22 07:20 UTC, adamviktora approved these changes
LGTM

2024-04-22 07:20 UTC, adamviktora commented on packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx
> +          <ToggleGroupItemElement variant={ToggleGroupItemVariant.icon}>{icon}</ToggleGroupItemElement>
nit: we could extract this ToggleGroupItemElement to a variable to not have it duplicated

2024-04-22 13:15 UTC, thatblindgeye requested changes
A few quick changes below.

Not a blocker, but an example description would be good to add in as well. Maybe something like, "When passing both the `text` and `icon` properties into a `<ToggleGroupItem>`, you can also pass in the `iconPosition` property to determine whether the icon is rendered at the start or end of the item." cc @edonehoo. We could also just open a followup to add descriptions for all ToggleGroup examples since there's not a lot of them, though.

2024-04-22 13:15 UTC, thatblindgeye commented on packages/react-core/src/components/ToggleGroup/examples/ToggleGroupTextIcon.tsx
> +      <ToggleGroup aria-label="Text and icon toggle group">
```suggestion
      <ToggleGroup aria-label="Text and icon toggle group with icons at start">
```

2024-04-22 13:15 UTC, thatblindgeye commented on packages/react-core/src/components/ToggleGroup/examples/ToggleGroupTextIcon.tsx
> +      <ToggleGroup aria-label="Text and icon toggle group">
```suggestion
      <ToggleGroup aria-label="Text and icon toggle group with icons at end">
```

2024-04-22 13:15 UTC, thatblindgeye commented on packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx
> +  /** Sets position of the icon */
```suggestion
  /** Sets position of the icon when text is also passed in */
```

2024-04-22 14:53 UTC, edonehoo commented
@thatblindgeye oo yeah let's do a follow up and I can got ahead and fill out the whole page!

2024-04-23 18:04 UTC, thatblindgeye approved these changes

2024-04-24 13:52 UTC, merged

2024-04-24 14:04 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.0.0-alpha.52
 - @patternfly/react-core@6.0.0-alpha.52
 - @patternfly/react-docs@7.0.0-alpha.54
 - @patternfly/react-drag-drop@6.0.0-alpha.33
 - demo-app-ts@5.1.1-alpha.51
 - @patternfly/react-table@6.0.0-alpha.52
 - @patternfly/react-templates@6.0.0-alpha.2

Thanks for your contribution! :tada: