feat(DragDropSort): update drag button usage
patternfly/patternfly-react pull request #10356
Opened 2024-05-13 15:04 UTC by kmcfaul

**What**: Closes #10290

Removes `defaultWithHandle` variant, and made that the default behavior.
Removed the drag button-less example.
Updated tests.

2024-05-13 15:13 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10356.surge.sh

2024-05-16 12:37 UTC, thatblindgeye requested changes
Just a typo fix, otherwise lgtm

2024-05-16 12:37 UTC, thatblindgeye commented on packages/react-drag-drop/src/components/DragDrop/DragDropSort.tsx
> +   * Default varaint wraps the draggable object in a div.
```suggestion
   * Default variant wraps the draggable object in a div.
```

2024-05-20 18:21 UTC, nicolethoen approved these changes

2024-05-23 13:10 UTC, thatblindgeye approved these changes

2024-05-23 13:23 UTC, merged

2024-05-23 13:37 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@7.0.0-alpha.63
 - @patternfly/react-drag-drop@6.0.0-alpha.41

Thanks for your contribution! :tada: