feat(Modal): promoted next version
patternfly/patternfly-react pull request #10358
Opened 2024-05-13 15:12 UTC by thatblindgeye

**What**: Closes #8078 

**Additional issues**:

2024-05-13 15:17 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10358.surge.sh

2024-05-16 13:50 UTC, wise-king-sullyman approved these changes

2024-06-04 14:38 UTC, kmcfaul approved these changes

2024-06-06 14:25 UTC, tlabaj requested changes
General comment.  We should not be using the deprecated modal in our components or examples/demos. We can open a follow up issue for that.

2024-06-06 14:25 UTC, tlabaj commented on packages/react-core/src/components/AboutModal/AboutModal.tsx
> -import { Modal, ModalVariant } from '../Modal';
we should be using the new modal here.  I am ok with follow up issue to do that, but it should be done for Beta.

2024-06-06 14:25 UTC, tlabaj commented on packages/react-core/src/components/Label/examples/LabelGroupEditableAddModal.tsx
> +import { Modal as ModalDeprecated, ModalVariant as ModalVariantDeprecated } from '@patternfly/react-core/deprecated';
same comment as above here

2024-06-06 14:25 UTC, tlabaj commented on packages/react-core/src/components/Wizard/examples/WizardWithinModal.tsx
> +      <ModalDeprecated
we should use new modal here.

2024-06-06 16:01 UTC, thatblindgeye commented
In regards to above, followup created for updating examples: https://github.com/patternfly/patternfly-react/issues/10363

2024-06-06 16:02 UTC, tlabaj approved these changes

2024-06-06 16:02 UTC, merged

2024-06-06 16:15 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.0.0-alpha.66
 - @patternfly/react-core@6.0.0-alpha.66
 - @patternfly/react-docs@7.0.0-alpha.70
 - @patternfly/react-drag-drop@6.0.0-alpha.48
 - @patternfly/react-integration@6.0.0-alpha.33
 - demo-app-ts@5.1.1-alpha.65
 - @patternfly/react-table@6.0.0-alpha.66
 - @patternfly/react-templates@6.0.0-alpha.16

Thanks for your contribution! :tada: