feat(badge): add disabled badge variant
patternfly/patternfly-react pull request #10445
Opened 2024-05-23 21:36 UTC by evwilkin

**What**: Closes #10417 

https://github.com/patternfly/patternfly/pull/6616

This PR adds a disabled badge variant

2024-06-03 15:42 UTC, wise-king-sullyman requested changes
Looks great other than one nit about the docs, and maybe I'm misunderstanding something (likely) but shouldn't there be a change in Button that goes along with this change too?

2024-06-03 15:42 UTC, wise-king-sullyman commented on packages/react-core/src/components/Badge/examples/Badge.md
> +## Disabled
Should be an h3 not an h2 right?

2024-06-03 19:56 UTC, wise-king-sullyman approved these changes
🎉

2024-06-05 18:36 UTC, tlabaj commented on packages/react-core/src/components/Badge/Badge.tsx
> +      (isDisabled ? styles.modifiers.disabled : '') as any,
since there is no alternative can we say do this instead?
`isDisabled && styles.modifiers.disabled`

2024-06-05 18:37 UTC, tlabaj requested changes
one small update needed

2024-06-05 21:03 UTC, tlabaj approved these changes

2024-06-06 13:23 UTC, thatblindgeye approved these changes

2024-06-06 13:51 UTC, merged

2024-06-06 14:04 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.0.0-alpha.65
 - @patternfly/react-core@6.0.0-alpha.65
 - @patternfly/react-docs@7.0.0-alpha.69
 - @patternfly/react-drag-drop@6.0.0-alpha.47
 - demo-app-ts@5.1.1-alpha.64
 - @patternfly/react-table@6.0.0-alpha.65
 - @patternfly/react-templates@6.0.0-alpha.15

Thanks for your contribution! :tada: