feat(Content): introduce Content component (replacement for Text)
patternfly/patternfly-react pull request #10579
Opened 2024-06-10 17:01 UTC by adamviktora

**What**: Closes #10395, #10390 

**Followup issues**:
- Replace occurrences of Text in the codebase with the new Content component
- Deprecate Text component

**Questions**:
- Do we need the ContentVariants enum? I lean towards removing it as we use the typescript union type in the `component` anyways. Codemode-wise it shouldn't be a problem.

2024-06-11 13:41 UTC, nicolethoen commented
🤔 

Creating a new Content component (and the noted follow up issue opened to deprecate the Text component) is raising some :red_flag: for me. Text is the MOST used component from PF according to our analytics. Is there a way we can make this change under the hood without deprecating our most used component?

2024-06-11 14:29 UTC, wise-king-sullyman commented
@nicolethoen we could definitely keep Text around either as-is or as essentially an alternative API for this Content component (which I think would be my preferred route of the two).

That being said we'll be able to handle the Text -> Content changes for consumers via a codemod, so I'm not sure I see the same red flags 🤔 Is the objection just based on consumer familiarity with Text?

2024-06-11 14:40 UTC, nicolethoen commented
I'm primarily concerned that we might be creating a scenario where products are going to need to make possible dozens or hundreds of manual changes to their static text and that will not go over well. If all changes here are non-breaking or something that can be handled completely by  codemods, then I'm less concerned. 

I dont' think we have the luxury to deprecate the old Text component (move it to a deprecated directory) and expect that they need to make any manual changes to move off of it.

2024-06-11 14:45 UTC, adamviktora commented
It is all fixable via codemods (I forgot to open a codemod issue). We can do this change directly, without deprecating Text, but I think it would be good to keep the Text component on the website and announce "Here is a link to the new Content component".

2024-06-11 15:16 UTC, kmcfaul approved these changes

2024-06-11 19:56 UTC, wise-king-sullyman requested changes
Looks great!

I love the test suite 🚀 but I do think we should also test that the contentH1, contentP etc classes are all appropriately applied.

2024-06-11 20:32 UTC, tlabaj reviewed
@adamviktora  are you going to open new PR or update this one?

2024-06-12 10:50 UTC, adamviktora commented
@tlabaj I'll update this one, regarding the new tests Austin mentioned. We will see after Office hours today if we have some new feedback - working on the slides now. But about https://github.com/patternfly/patternfly-react/issues/10580 I plan to do that in a separate PR.

2024-06-12 13:52 UTC, tlabaj requested changes
@adamviktora I think we should update this PR or open a new on so that it modifies Text rather than introduce a new componet since that is what we are doing.

2024-06-13 00:30 UTC, mcoker requested changes
LGTM, just one comment around what we chatted about in office hours.

2024-06-13 00:30 UTC, mcoker commented on packages/react-core/src/components/Content/Content.tsx
> +        isList && styles.content,
As discussed in office hours, I would remove this under the assumption that if you want to be able to write plain HTML, you'll need to wrap that markup in `<Text>`.

I think the idea for an `isContentWrapper` (or whatever it's called) prop that could be applied to a list, paragraph, etc, is a great idea and would give the functionality that exists in this PR currently, though IMO that could be an enhancement for later. If we add that, I'd like some time to test it and make sure it works as intended.

2024-06-26 16:24 UTC, adamviktora commented
Closing this PR, because the change will be handled with 2 new PRs: https://github.com/patternfly/patternfly-react/pull/10611, https://github.com/patternfly/patternfly-react/pull/10643

2024-06-26 16:24 UTC, closed without merging