Replace Text, TextContent, TextList and TextListItem with Content
patternfly/patternfly-react pull request #10611
Opened 2024-06-13 13:39 UTC by adamviktora

**What**: Closes #10395, #10390 

Previous PR: https://github.com/patternfly/patternfly-react/pull/10579

2024-06-13 13:43 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10611.surge.sh

2024-06-24 13:05 UTC, tlabaj approved these changes

2024-06-25 18:53 UTC, thatblindgeye approved these changes

2024-06-25 19:05 UTC, kmcfaul requested changes
We should update `Content.tsx` to export as `Content`, it's still being exported as `Text` and is referred to as `Text` in the docs and examples (including the imports and usage in examples). The examples should use `Content` instead of the `Text` suite (maybe keeping a couple Text-using examples if we are keeping the Text components around, but my impression was they were being removed?).

Do we want to remove TextContent, TextList, TextListItem or are we keeping them for now? Not a blocker if we want to keep them.

2024-06-26 15:09 UTC, adamviktora commented
@kmcfaul 
Sorry, I did not explain the intention in the description. So there will also be a part 2 PR: https://github.com/patternfly/patternfly-react/pull/10643 which removes the Text, TextContent, TextList and TextListItem.

The reason for doing the changes separately in two PRs is:
1) To keep the correct version history of the files, so the changes are tracked as a rename rather than a new component (see [this](https://github.com/patternfly/patternfly-react/pull/10579#issuecomment-2165515755) conversation)
2) The second PR will break the build because updates are needed in org as well.

2024-06-26 17:16 UTC, kmcfaul approved these changes

2024-07-01 17:51 UTC, mcoker approved these changes
👍👍

2024-07-01 18:00 UTC, merged

2024-07-01 18:18 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.0.0-alpha.74
 - @patternfly/react-core@6.0.0-alpha.74
 - @patternfly/react-docs@7.0.0-alpha.80
 - @patternfly/react-drag-drop@6.0.0-alpha.56
 - demo-app-ts@5.1.1-alpha.73
 - @patternfly/react-table@6.0.0-alpha.75
 - @patternfly/react-templates@6.0.0-alpha.24

Thanks for your contribution! :tada: