fix: accordion sub components spread props
patternfly/patternfly-react pull request #10679
Opened 2024-06-28 21:03 UTC by nicolethoen

**What**: Closes https://github.com/patternfly/patternfly-react/issues/10678

2024-06-28 21:07 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10679.surge.sh

2024-07-03 13:00 UTC, thatblindgeye requested changes
Looks like we may want to add another prop to AccordionContent that can be passed to AccordionExpandableContentBody internally. Right now the only way to pass other props to AccordionExpandableContentBody is by explicitly using the component within a `<AccordionContent isCustomContent><AccordionExpandableContentBody>....`, vs just being able to do something like `<AccordionContent contentBodyProps={...}`

Could we also just add a test to both of these updated components for passing props that would get spread to them?

2024-07-16 15:35 UTC, kmcfaul approved these changes

2024-07-16 15:49 UTC, wise-king-sullyman approved these changes

2024-07-16 17:32 UTC, thatblindgeye approved these changes

2024-07-18 15:25 UTC, tlabaj approved these changes

2024-07-18 15:25 UTC, merged