feat(MultiTypeaheadSelect): Add MultiTypeaheadSelect to react-templates
patternfly/patternfly-react pull request #10757
Opened 2024-07-16 16:42 UTC by jeff-phillips-18

**What**:
Closes #10733 

**Description**:
Adds a `MultiTypeaheadSelect` component to the @patternfly/react-templates package and a demo of the component for the docs apge.

2024-07-16 16:47 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10757.surge.sh

2024-07-17 14:34 UTC, tlabaj requested changes

2024-07-17 14:34 UTC, tlabaj commented on packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx
> +  const NO_RESULTS = 'no results';
Can we add a prop so consumers an change this string?

2024-07-17 17:54 UTC, dlabaj approved these changes
Other then titani's comment LGTM.

2024-07-17 18:29 UTC, tlabaj approved these changes

2024-07-17 18:29 UTC, tlabaj commented on packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx
> +  const NO_RESULTS = 'no results';
Never mind.  It looks like that is not a display string.

2024-07-17 18:41 UTC, kmcfaul requested changes
Just one behavioral bug, everything else lgtm

2024-07-17 18:41 UTC, kmcfaul commented on packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx
> +    const selections = selected.includes(option) ? selected.filter((o) => option === o) : [...selected, option];
The true branch here should be `selected.filter((o) => option !== o)`. Currently it's resetting the selections array when an option is deselected.

2024-07-17 18:44 UTC, kmcfaul commented on packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx
> +    const selections = selected.includes(option) ? selected.filter((o) => option === o) : [...selected, option];
```suggestion
    const selections = selected.includes(option) ? selected.filter((o) => option !== o) : [...selected, option];
```

2024-07-17 18:45 UTC, kmcfaul commented on packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx
> +    const selections = selected.includes(option) ? selected.filter((o) => option === o) : [...selected, option];
The true branch here should be selected.filter((o) => option !== o). Currently it's resetting the selections array when an option is deselected.

2024-07-17 19:18 UTC, jenny-s51 approved these changes

2024-07-17 20:38 UTC, kmcfaul approved these changes

2024-07-17 20:38 UTC, merged

2024-07-17 20:51 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@6.4.0-prerelease.41
 - @patternfly/react-templates@1.1.0-prerelease.28

Thanks for your contribution! :tada: