feat(Masthead): Updates for new masthead structure in Penta
patternfly/patternfly-react pull request #10809
Opened 2024-07-26 00:02 UTC by tlabaj

**What**: Closes #10788

2024-07-26 00:06 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10809.surge.sh

2024-07-26 13:47 UTC, wise-king-sullyman approved these changes

2024-07-26 14:03 UTC, srambach reviewed
Surge is down so I haven't run it yet but had a couple of questions. Otherwise looks good on inspection!

2024-07-26 14:04 UTC, tlabaj commented on packages/react-core/src/components/Masthead/examples/Masthead.md
> +`MastheadMain` represents the smaller area taken up by a logo, and will typically contain a `MastheadLogo`. `MastheadContent` represents the main portion of the masthead area and will typically conta
Yes!  I meant to go back an look at the wording.  I will see if Erin can review it too.

2024-07-26 14:51 UTC, edonehoo requested changes
since surge is down, this is going off the file changes as best I can. can re-review if/when surge comes back to make sure I checked everything, but this probably covers the main things regardless!

2024-07-26 14:51 UTC, edonehoo commented on packages/react-core/src/components/Masthead/examples/Masthead.md
> +`Masthead` should contain the following components to maintain proper layout and formatting: `MastheadMain`, and `MastheadContent`.
```suggestion
To maintain proper layout and formatting, a `<Masthead>` should contain both a `<MastheadMain>` and `<MastheadContent>` component.
```

2024-07-26 14:51 UTC, edonehoo commented on packages/react-core/src/components/Masthead/examples/Masthead.md
> +`MastheadMain` represents the smaller area taken up by a toggle and logo, and will typically contain a `MastheadToggle` and a `MastheadLogo`. `MastheadContent` represents the main portion of the mast
```suggestion
The `<MastheadMain>` component includes the smaller area that typically contains the `<MastheadToggle>` and a `<MastheadLogo>`. `<MastheadContent>` represents the main portion of the masthead, and will typically contain a `<Toolbar>` or other menu-like components, like a `<Dropdown>`.
```

2024-07-26 14:51 UTC, edonehoo commented on packages/react-core/src/components/Page/examples/Page.md
> +  - Mastheads contain the `<MastheadMain>` that wraps a `<PageToggleButton>` and `<MastheadBrand>`. The `<MastheadBrand>` wraps `<MastheadLogo>`. The masthead also contains  the page's header toolbar
```suggestion

The `<MastheadMain>` component includes the smaller area that typically contains the `<MastheadToggle>` and a `<MastheadLogo>`. `<MastheadContent>` represents the main portion of the masthead, and will typically contain a `<Toolbar>` or other menu-like components, like a `<Dropdown>`.

  - Mastheads contain a `<MastheadMain>` component, which includes the `<MastheadToggle>`, a `<MastheadLogo>`,  and the page's toolbar (via `<MastheadContent>`.) The `<MastheadToggle>` component contains a `<PageToggleButton>`, and the `<MastheadLogo>` component contains a `<MastheadBrand>`. 
```

This is going off of the changes from the masthead page, where mention of MastheadBrand was replaced. But I may have misinterpreted that & you may need to correct this suggestion for accuracy

2024-07-26 15:02 UTC, thatblindgeye approved these changes

2024-07-26 15:16 UTC, tlabaj commented on packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx
> +            <Button variant="plain" onClick={() => {}} aria-label="Global navigation">
this is in the demo app for integration test and they are currently no test for masthead.  I don't think it is necessary to update this here.

2024-07-26 17:51 UTC, edonehoo approved these changes

2024-07-29 14:50 UTC, kmcfaul approved these changes
lgtm. We may want to open a follow up in org if we don't already have one to update the structure for the docs site (the surge masthead is the old structure still).

2024-07-29 14:52 UTC, andrew-ronaldson approved these changes
Great stuff!

2024-07-29 15:57 UTC, srambach approved these changes
🎉 ⭐

2024-07-29 15:57 UTC, merged