chore(docs): core bump, jumplinks demo fix
patternfly/patternfly-react pull request #10993
Opened 2024-09-13 02:28 UTC by evwilkin

Closes #10887 

This PR:
- Bumps Core versions to pull in Page overflow fix from https://github.com/patternfly/patternfly/pull/7025.
- Updates jumplinks demo to fix offset calculations.
- Updates jumplinks integration test.
- Fixes incorrect test name in code editor integration test.

2024-09-13 15:36 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-10993.surge.sh

2024-09-24 17:41 UTC, tlabaj approved these changes

2024-09-24 17:44 UTC, tlabaj requested changes
I am seeing a reference error in the jumplinks with drawer demo.
"ReferenceError: breadcrumbStyles is not defined"

2024-09-24 19:13 UTC, mcoker approved these changes
LGTM! I'll mention core is on [prerelease.13](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-prerelease.13) now. Not sure if it's worth trying to bump that in this PR or somewhere else?

2024-09-24 19:13 UTC, kmcfaul approved these changes

2024-09-24 19:13 UTC, merged

2024-09-24 19:14 UTC, tlabaj commented
@mcoker I am bumping the versions in may datalist PR.

2024-09-24 19:28 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-charts@8.0.0-prerelease.11
 - @patternfly/react-code-editor@6.0.0-prerelease.16
 - @patternfly/react-core@6.0.0-prerelease.16
 - @patternfly/react-docs@7.0.0-prerelease.26
 - @patternfly/react-drag-drop@6.0.0-prerelease.16
 - @patternfly/react-icons@6.0.0-prerelease.5
 - @patternfly/react-integration@6.0.0-prerelease.9
 - demo-app-ts@6.0.0-prerelease.19
 - @patternfly/react-styles@6.0.0-prerelease.4
 - @patternfly/react-table@6.0.0-prerelease.17
 - @patternfly/react-templates@6.0.0-prerelease.16
 - @patternfly/react-tokens@6.0.0-prerelease.5

Thanks for your contribution! :tada: