CodeEditor loading property considered by the Editor
patternfly/patternfly-react pull request #11034
Opened 2024-09-20 09:37 UTC by Ginxo

**What**: Closes #11033

**Additional issues**:

2024-09-20 09:38 UTC, Ginxo commented
I would like to see tests for this particular use case not being covered, I will provide as soon as we have an approval about the issue and also the proposal (this PR)

2024-09-20 09:41 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-11034.surge.sh

2024-10-09 16:40 UTC, kmcfaul requested changes

2024-10-09 16:40 UTC, kmcfaul commented on packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
>                  {...editorProps}
`editorProps` should already allow `loading` to be passed. If we want `loading` to be a distinct property, we will need to add it to the props table.

2024-10-10 15:09 UTC, kmcfaul approved these changes
Ah I do see we have this on our props table already, it wasn't being passed. 

Using `editorProps` would also work, but I'm in favor of adding this method too.

2024-10-10 15:09 UTC, kmcfaul commented on packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
>                  {...editorProps}
I missed that this already was in the props table and is unsed.

2024-10-12 10:25 UTC, Ginxo commented
one more additional approver required, please any kind soul aroung? :pray: :wink:

2024-10-23 14:43 UTC, tlabaj approved these changes

2024-10-23 14:43 UTC, tlabaj commented
@Ginxo if you need this in v5, can you please change the base branch to the `v5` branch

2024-10-24 10:17 UTC, Ginxo commented
> @Ginxo if you need this in v5, can you please change the base branch to the `v5` branch

a [new PR for V5](https://github.com/patternfly/patternfly-react/pull/11134) already open

2024-10-24 17:24 UTC, tlabaj commented
@Ginxo We are still in code freeze right now.  We will merge your PR once our release is live.

2024-10-29 15:43 UTC, merged