fix(Menu toggle): Remove pf-m-action modifier
patternfly/patternfly-react pull request #11096
Opened 2024-10-01 15:40 UTC by tlabaj

**What**: Closes #11095

2024-10-01 15:44 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-11096.surge.sh

2024-10-01 15:47 UTC, mcoker approved these changes
L🎃TM!

2024-10-01 19:22 UTC, edonehoo approved these changes
content looks good!

2024-10-01 20:04 UTC, dlabaj reviewed
React code looks good to me.

2024-10-01 20:32 UTC, kmcfaul requested changes
Just a minor example update to get it working, otherwise lgtm. Slider also looks like it's acting fine on the preview.

2024-10-01 20:32 UTC, kmcfaul commented on packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonAction.tsx
> +      SplitButtonItems={[
Needs to be lower case `s`.

2024-10-02 13:15 UTC, evwilkin approved these changes
LGTM

2024-10-02 14:20 UTC, kmcfaul approved these changes

2024-10-02 14:24 UTC, merged