docs(misc): update to new logo
patternfly/patternfly-react pull request #11290
Opened 2024-11-25 22:54 UTC by kmcfaul

**What**: Closes #9443

I initially tried to use the new horizontal logo with LoginPage, but it was very large and currently LoginPage has no method to customize the internal Brand component, so I went with the icon logo instead. LMK if we want to still go with the horizontal logo + add a Brand spread props to LoginPage.

2024-11-25 22:58 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-11290.surge.sh

2024-12-03 19:23 UTC, thatblindgeye requested changes
Quick nit below. I'd agree with adding a prop to spread to Brand in LoginPage, but not a blocker for this PR to me.

2024-12-03 19:23 UTC, thatblindgeye commented on packages/react-core/src/demos/CustomMenus/examples/ApplicationLauncherDemo.tsx
> +          icon={<img src={brandImg} width={25} height={25} />}
```suggestion
          icon={<img src={brandImg} alt="" width={25} height={25} />}
```

2024-12-04 16:38 UTC, thatblindgeye approved these changes

2024-12-13 17:08 UTC, wise-king-sullyman approved these changes

2024-12-13 17:08 UTC, merged

2024-12-13 17:19 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.1.0-prerelease.16
 - @patternfly/react-core@6.1.0-prerelease.16
 - @patternfly/react-docs@7.1.0-prerelease.25
 - @patternfly/react-drag-drop@6.1.0-prerelease.16
 - demo-app-ts@6.0.0-prerelease.45
 - @patternfly/react-table@6.1.0-prerelease.16
 - @patternfly/react-templates@6.1.0-prerelease.16

Thanks for your contribution! :tada: