feat(Table,misc): rewrite column management demo, remove old dnd examples
patternfly/patternfly-react pull request #11295
Opened 2024-11-27 16:16 UTC by kmcfaul

Closes #11190.

Also slightly touches up the basic column management demo as the changes to Modal are the same.

There is an issue with `DragDropSort` I've noticed but haven't yet debugged, that the DataListItems it creates internally are for some reason duplicating the `DataListItemControl` component for the `DataListCheck`, giving it extra padding. I'm not sure why this is happening, as it doesn't occur in the `DragDropSort` DataList example even with the same content code strucutre.

2024-11-27 16:20 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-11295.surge.sh

2024-12-04 15:16 UTC, tlabaj commented
@kmcfaul can you open an issue to track the DragDropSort bug you mention above?

2024-12-04 15:41 UTC, kmcfaul commented
Opened https://github.com/patternfly/patternfly-react/issues/11312

2024-12-20 15:40 UTC, wise-king-sullyman requested changes
Overall looks great, I did see a bug in the dragable column management demo where the table stops rendering if the drag is done before any columns are toggled on or off that we probably want to fix before merging.

2024-12-20 15:58 UTC, thatblindgeye approved these changes
Other than the above this lgtm

2025-01-13 18:30 UTC, nicolethoen reviewed
This LGTM!

only, there is a rogue comma between the modal buttons 😆 

![Screenshot 2025-01-13 at 1 30 12 PM](https://github.com/user-attachments/assets/1240af6d-2c45-4137-bc34-6980fee92430)

2025-01-20 15:13 UTC, nicolethoen approved these changes

2025-01-20 18:38 UTC, wise-king-sullyman approved these changes

2025-01-20 18:38 UTC, merged

2025-01-20 18:49 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.2.0-prerelease.6
 - @patternfly/react-core@6.2.0-prerelease.5
 - @patternfly/react-docs@7.2.0-prerelease.13
 - @patternfly/react-drag-drop@6.2.0-prerelease.6
 - demo-app-ts@6.0.0-prerelease.54
 - @patternfly/react-table@6.2.0-prerelease.6
 - @patternfly/react-templates@6.2.0-prerelease.6

Thanks for your contribution! :tada: