feat(Toolbar): add insets property
patternfly/patternfly-react pull request #4757
Opened 2020-08-31 20:34 UTC by kmcfaul

**What**: Closes #4661

2020-08-31 20:43 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-4757.surge.sh

2020-09-03 15:47 UTC, tlabaj requested changes

2020-09-03 15:47 UTC, tlabaj commented on packages/react-integration/cypress/integration/toolbar.spec.ts
> +  it('has inset classes', () => {
can you test all breakpoints.  We have had issues in the past when classes where not being applied correctly at certain breakpoints.  See Tabs for an example.

2020-09-11 16:20 UTC, tlabaj approved these changes
LGTM

2020-09-11 17:57 UTC, mcarrano commented
@mcoker @mattnolting can either of you confirm that this is doing what's it's supposed to?

2020-09-11 18:59 UTC, evwilkin approved these changes
LGTM

2020-09-11 19:00 UTC, merged