Added OUIA support into NavItem
patternfly/patternfly-react pull request #4769
Opened 2020-09-02 11:28 UTC by quarckster

**What**: #4768

This PR makes NavItem OUIA compatible.

2020-09-02 11:28 UTC, quarckster commented
@redallen @jschuler please review

2020-09-02 11:37 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-4769.surge.sh

2020-09-02 12:57 UTC, redallen submitted a review, later dismissed

2020-09-03 17:10 UTC, jenny-s51 submitted a review, later dismissed

2020-09-14 19:05 UTC, jschuler commented on packages/react-core/src/components/Nav/NavItem.tsx
> +    <li className={css(styles.navItem, className)} {...getOUIAProps(NavItem.displayName, ouiaId, ouiaSafe)}>
to support better ouia default ids, you can do the following:
```
import { useOUIAProps } from '../../helpers';
...
const ouiaProps = useOUIAProps(NavItem.displayName, ouiaId, ouiaSafe);
...
return (
  <li {...ouiaProps} />
)
```

2020-09-14 19:06 UTC, jschuler requested changes
See comment above

2020-09-21 16:52 UTC, jschuler approved these changes

2020-09-21 17:22 UTC, redallen approved these changes

2020-09-21 17:22 UTC, merged