release notes 2020.12
patternfly/patternfly-react pull request #4841
Opened 2020-09-17 20:03 UTC by tlabaj

**What**: Closes #4838

2020-09-17 20:08 UTC, redallen approved these changes

2020-09-17 20:12 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-4841.surge.sh

2020-09-18 13:17 UTC, evwilkin approved these changes
LGTM

2020-09-18 13:19 UTC, redallen requested changes

2020-09-18 13:19 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +- [@patternfly/react-core@4.50.4](https://www.npmjs.com/package/@patternfly/react-core/v/4.50.4)
This version hasn't been released yet. `4.50.1` is the last `prerelease`.

2020-09-18 18:02 UTC, redallen approved these changes

2020-09-18 18:03 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +- [@patternfly/react-core@4.50.4](https://www.npmjs.com/package/@patternfly/react-core/v/4.50.4)
I pushed a fix to this PR.

2020-09-18 18:04 UTC, evwilkin approved these changes
LGTM thanks!

2020-09-18 18:04 UTC, merged

2020-09-18 18:23 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.8.39

Thanks for your contribution! :tada: