Fix(datalist): update aria of datalist
patternfly/patternfly-react pull request #4913
Opened 2020-09-30 14:19 UTC by jessiehuff

**What**: Closes #4896

2020-09-30 14:23 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-4913.surge.sh

2020-09-30 17:16 UTC, redallen requested changes
Not sure this does what you're expecting. Since `Boolean({ 'aria-selected': true }) === true` this will only add `{  'aria-activedescendant': selectedDataListItemId }` and will ignore the `aria-selected`. Did you mean to add both?
```jsx
{...(isSelectable && selectedDataListItemId === id && {
  'aria-selected': true,
  'aria-activedescendant': selectedDataListItemId
})}
```

2020-10-01 15:49 UTC, kmcfaul submitted a review, later dismissed

2020-10-01 17:52 UTC, KKoukiou approved these changes
Reading your comment and the listbox [role docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role) I think your decision makes sense.

2020-10-01 18:55 UTC, redallen approved these changes

2020-10-01 18:55 UTC, merged