feat(table): added support for single row radio select
patternfly/patternfly-react pull request #4925
Opened 2020-10-01 17:15 UTC by KKoukiou

2020-10-01 17:32 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-4925.surge.sh

2020-10-01 18:27 UTC, redallen requested changes
Probably don't want a radio button in the table header?
![image](https://user-images.githubusercontent.com/47335686/94848514-1c7f3600-03f2-11eb-8528-1cb1234920e5.png)

2020-10-01 18:27 UTC, redallen commented on packages/react-table/src/components/Table/examples/Table.md
> +### Selectable Radio Input
Use sentence case: `Selectable radio input`

2020-10-01 19:23 UTC, mcoker commented
Aside from @redallen's comments, this LGTM. One thing I noticed is that the react table uses `pf-c-check__input` and `pf-c-radio__input` for the check and radio inputs, but we don't use those in core. They're just regular `<input type="[radio/check]">` elements. The check and radio components are designed to work as an input/label pair, and the `pf-c-[check/radio]__input` elements are expected to be children of `pf-c-[check/radio]`.

I don't think that we want to change the checkbox inputs since that could break users if they're styling them using the `pf-c-check__input` class or something like that, but I'm wondering if we should use regular radio inputs, or use the `pf-c-radio__input` element to be consistent with the table checkboxes.

2020-10-02 07:14 UTC, KKoukiou commented
> Aside from @redallen's comments, this LGTM. One thing I noticed is that the react table uses `pf-c-check__input` and `pf-c-radio__input` for the check and radio inputs, but we don't use those in core. They're just regular `<input type="[radio/check]">` elements. The check and radio components are designed to work as an input/label pair, and the `pf-c-[check/radio]__input` elements are expected to be children of `pf-c-[check/radio]`.
> 
> I don't think that we want to change the checkbox inputs since that could break users if they're styling them using the `pf-c-check__input` class or something like that, but I'm wondering if we should use regular radio inputs, or use the `pf-c-radio__input` element to be consistent with the table checkboxes.

@mcarrano amazing how you noticed this! Indeed I introduced these classes in a separate commit in this PR, and the reason I did it, it because I noticed that checboxes/radio inputs without these two classes (`pf-c-radio__input, pf-c-check__input`) do not show the black circle when being hovered over in a disable mode.

This is a bug and adding these classes fixes the issue.

So if I was to choose between fixing an existing bug by using the classes, and protecting users who are using custom CSS on these classes and might see issues, I would go with the first.
In any case, I leave it up to you to decide :)

2020-10-02 14:19 UTC, redallen approved these changes
Code LGTM!

2020-10-02 14:48 UTC, mcoker commented
@KKoukiou ah! Thanks for the explanation and fixing the bug. It's ultimately a misuse of the radio/check component, and will also change the positioning of the existing check input because the check component's input has a margin - https://github.com/patternfly/patternfly/blob/1b3c31608b8d7f43f3509cdeef8b7e62358b8a46/src/patternfly/components/Check/check.scss#L26-L28

I'm in favor of leaving it with the disabled input bug for the time being. We have an issue to allow the check/radio inputs to be used on their own in the check/radio components here - https://github.com/patternfly/patternfly/issues/3311

I think once we have support for  https://github.com/patternfly/patternfly/issues/3311 we can look at whether we should introduce the check/radio component input here, or just style the regular check/radio inputs in the table to support a disabled state until we're able to update the table to use the check/radio component inputs. Sound ok?

2020-10-02 14:48 UTC, jschuler reviewed
Code LGTM, just need to clarify on the radio/checkbox styling with @mcoker

2020-10-02 14:48 UTC, jschuler commented on packages/react-table/src/components/Table/Table.tsx
> +  /** Where the row checkbox/radio button is disabled */
```suggestion
  /** Whether the row checkbox/radio button is disabled */
```

2020-10-02 14:56 UTC, KKoukiou commented
> @KKoukiou ah! Thanks for the explanation and fixing the bug. It's ultimately a misuse of the radio/check component, and will also change the positioning of the existing check input because the check component's input has a margin - https://github.com/patternfly/patternfly/blob/1b3c31608b8d7f43f3509cdeef8b7e62358b8a46/src/patternfly/components/Check/check.scss#L26-L28
> 
> I'm in favor of leaving it with the disabled input bug for the time being. We have an issue to allow the check/radio inputs to be used on their own in the check/radio components here - [patternfly/patternfly#3311](https://github.com/patternfly/patternfly/issues/3311)
> 
> I think once we have support for [patternfly/patternfly#3311](https://github.com/patternfly/patternfly/issues/3311) we can look at whether we should introduce the check/radio component input here, or just style the regular check/radio inputs in the table to support a disabled state until we're able to update the table to use the check/radio component inputs. Sound ok?

Perfect! Reverting the relevant commit.

2020-10-02 15:37 UTC, mcoker approved these changes
lgtm! Thanks @KKoukiou!!

2020-10-02 17:57 UTC, mcoker approved these changes

2020-10-02 18:11 UTC, redallen approved these changes

2020-10-02 18:11 UTC, merged