feat(Form): add FormAlert, isLimitWidth, and allow helper text above field
patternfly/patternfly-react pull request #5036
Opened 2020-10-19 20:59 UTC by nicolethoen

**What**: Closes #4958 

FormAlert component - used for wrapping Alerts at the top of a form. There is no styles attached to the `.pf-c-form__alert` component. So it does not exist in react-styles.

isLimitWidth - can be put on the Form component to limit the max-width of the whole form.

the prop name could probably be better? `helperTextIsBeforeField`

2020-10-19 21:05 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5036.surge.sh

2020-10-20 16:15 UTC, redallen requested changes
Some nits, overall looks good.

2020-10-20 16:15 UTC, redallen commented on packages/react-core/src/components/Form/FormGroup.tsx
> +  helperTextIsBeforeField?: boolean;
Change to `isHelperTextBeforeField`.

2020-10-20 16:15 UTC, redallen commented on packages/react-core/src/components/Form/FormAlert.tsx
> +  <div {...props} className={css('pf-c-form__alert', className)}>
Let's wait for the React style in #4983 before merging this.

2020-10-20 16:15 UTC, redallen commented on packages/react-core/src/components/Form/FormGroup.tsx
> +            : showValidHelperTxt(validated))}
Add
```ts
const helperText = validated === ValidatedOptions.error && helperTextInvalid
            ? inValidHelperText
            : showValidHelperTxt(validated);
```

Then change to `{helperTextIsBeforeField && helperText}` and `{!helperTextIsBeforeField && helperText}`.

2020-10-20 16:15 UTC, redallen commented on packages/react-core/src/components/Form/examples/Form.md
> +### Invalid with Form alert
Lowercase F in form.

2020-10-20 18:07 UTC, jessiehuff reviewed
Typically when adding a dynamic alert, I would suggest using an `aria-live` approach. I think given what we offer with our alerts, you can likely just change the attributes on the Alert (particularly: `ariaLive: 'polite'` - we can test out if polite works to avoid the intrusiveness of assertive, otherwise we can make it assertive and `aria-atomic="false"`). The [dynamic alert example](https://www.patternfly.org/v4/components/alert#dynamic-live-region-alert) shows these potential variations.

2020-10-20 19:18 UTC, redallen approved these changes
Since it's just a placeholder class this LGTM!

2020-10-20 21:38 UTC, kmcfaul submitted a review, later dismissed
lgtm!

2020-10-22 14:56 UTC, tlabaj requested changes

2020-10-22 14:56 UTC, tlabaj commented on packages/react-core/src/components/Form/Form.tsx
> +  isLimitWidth?: boolean;
Maybe `isWidthLimited` for the prop name.

2020-10-22 14:56 UTC, tlabaj commented on packages/react-core/src/components/Form/FormGroup.tsx
> +  isHelperTextBeforeField,
Can we default this to false like we typically do with our other boolean props?

2020-10-22 15:48 UTC, mcoker submitted a review, later dismissed
lgtm! 👍

2020-10-22 17:47 UTC, mcarrano reviewed
Not sure if this 100% covered what I expect. I'm comparing with the demo here: https://pf4.patternfly.org/components/alert/html-demos/inline-alert-in-horizontal-form/  I think part of the ask was to support adding alert text like this inline with a form but I might be mistaken.

![Screen Shot 2020-10-22 at 1 46 40 PM](https://user-images.githubusercontent.com/6619860/96910194-19192080-146d-11eb-847d-ef2daba701d0.png)

@mcoker can you help clarify?

2020-10-22 18:27 UTC, nicolethoen commented
> Not sure if this 100% covered what I expect. I'm comparing with the demo here: https://pf4.patternfly.org/components/alert/html-demos/inline-alert-in-horizontal-form/ I think part of the ask was to support adding alert text like this inline with a form but I might be mistaken.
> 
> ![Screen Shot 2020-10-22 at 1 46 40 PM](https://user-images.githubusercontent.com/6619860/96910194-19192080-146d-11eb-847d-ef2daba701d0.png)
> 
> @mcoker can you help clarify?

@mcarrano That screen shot you provide is supported with these updates. we just dont have an example of a validated horizontal checkbox group in these docs. I can modify the example "Horizontal helper text on top" to be an example that displays an error message rather than helper text.

2020-10-22 18:46 UTC, mcoker commented on packages/react-core/src/components/Form/examples/Form.md
> +          fieldId="options">
Can you add `hasNoPaddingTop`? We use that when the thing in the form element field isn't a text input, textarea, or select.

2020-10-22 19:17 UTC, mcarrano commented
I'm good as long as this is supported @nicolethoen . We do have an issue in the backlog about creating a more robust Form demo so maybe this example belongs there. I'll defer to your judgement on whether it will be clear enough to a developer how to construct an inline validation like I'm showing should that need come up.

2020-10-22 20:50 UTC, tlabaj approved these changes
LGTM

2020-10-23 15:36 UTC, mcoker approved these changes
beautiful! 😍

2020-10-23 15:52 UTC, dlabrecq approved these changes

2020-10-23 17:46 UTC, redallen approved these changes

2020-10-23 17:47 UTC, merged