feat(Splitter): add Splitter component
patternfly/patternfly-react pull request #5051
Opened 2020-10-22 15:21 UTC by nicolethoen

**What**: Closes #4715 

New issues created:
Create examples which incorporate sliding interaction using mouse or keyboard to slide the splitter. - #5049
Add Drawer and MasterDetails demos(?)/variants(?) which incorporate a sliding splitter. - #5050

2020-10-22 15:26 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5051.surge.sh

2020-10-22 17:40 UTC, mcarrano submitted a review, later dismissed
This looks good to me and thanks for opening the follow-on issues. I'm OK to merge this with the caveat that we have more work to do on adding examples if others agree.

2020-10-22 17:42 UTC, mcoker approved these changes
LGTM!

2020-10-22 20:02 UTC, kmcfaul submitted a review, later dismissed

2020-10-22 20:44 UTC, tlabaj requested changes

2020-10-22 20:44 UTC, tlabaj commented on packages/react-core/src/components/Splitter/Splitter.tsx
> +  /** Additional classes added to the Splitter. */
Nit. Sentence case

2020-10-22 22:09 UTC, tlabaj approved these changes
LGTM

2020-10-23 13:32 UTC, dlabrecq approved these changes

2020-10-23 14:02 UTC, merged

2020-10-23 14:17 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.8.83
 - @patternfly/react-core@4.71.0
 - @patternfly/react-datetime@4.2.28
 - @patternfly/react-docs@5.10.43
 - @patternfly/react-inline-edit-extension@4.5.141
 - demo-app-ts@4.57.0
 - @patternfly/react-integration@4.57.0
 - @patternfly/react-table@4.18.38
 - @patternfly/react-topology@4.6.48
 - @patternfly/react-virtualized-extension@4.5.128

Thanks for your contribution! :tada: