chore(release notes): Updated release notes for 2020.14
patternfly/patternfly-react pull request #5064
Opened 2020-10-26 16:33 UTC by tlabaj

**What**: Closes #5063

2020-10-26 16:38 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5064.surge.sh

2020-10-26 16:51 UTC, redallen requested changes
Nits

2020-10-26 16:51 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +  - Updated to allow custom chip render props in the multi typehead select . ([#5031](https://github.com/patternfly/patternfly-react/pull/5031))
Stray `.`

2020-10-26 16:51 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +- **Charts:** Legend tooltip example ([#5006](https://github.com/patternfly/patternfly-react/pull/5006))
Remove `**Charts:** `

2020-10-26 17:29 UTC, redallen approved these changes

2020-10-26 19:21 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Updated to allow custom chip render props in the multi typehead select ([#5031](https://github.com/patternfly/patternfly-react/pull/5031))
```suggestion
  - Updated to allow custom chip render props in the multi typeahead select ([#5031](https://github.com/patternfly/patternfly-react/pull/5031))
```

2020-10-26 19:22 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Converted DataLIstAction to functional component ([#4947](https://github.com/patternfly/patternfly-react/pull/4947))
```suggestion
  - Converted DataListAction to functional component ([#4947](https://github.com/patternfly/patternfly-react/pull/4947))
```

2020-10-26 19:23 UTC, evwilkin requested changes
2 very small nits, otherwise looks good

2020-10-26 21:07 UTC, evwilkin approved these changes
LGTM - thanks!

2020-10-27 13:29 UTC, redallen approved these changes

2020-10-27 13:29 UTC, merged

2020-10-27 13:46 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.10.50

Thanks for your contribution! :tada: