feat(textarea): support isDisabled
patternfly/patternfly-react pull request #5107
Opened 2020-11-08 19:03 UTC by boaz0

**What**: Closes #5068 

It is a breaking change. If someone is using `disabled` in the props then after updating with this change Typescript will show error message saying `disabled` is not a valid props of `TextArea`.

2020-11-08 19:08 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5107.surge.sh

2020-11-09 20:21 UTC, redallen approved these changes

2020-11-09 20:22 UTC, redallen commented on packages/react-core/src/components/TextArea/TextArea.tsx
> +export interface TextAreaProps extends Omit<HTMLProps<HTMLTextAreaElement>, 'disabled' | 'onChange' | 'ref'> {
I'm in favor of this and I think it warrants finally having a "breaking type change" discussion I've been postponing.

2020-11-09 20:43 UTC, tlabaj requested changes
We should also add the `isReadOnly` prop.  That is what the consumer seems to be looking for.  Please see my comment in the issue.

2020-11-11 18:24 UTC, kmcfaul submitted a review, later dismissed

2020-11-11 18:52 UTC, tlabaj reviewed
Can you also update the demo app please.

2020-11-11 19:27 UTC, boaz0 commented
@tlabaj done! :+1:

2020-11-13 16:38 UTC, kmcfaul submitted a review, later dismissed

2020-11-19 15:59 UTC, tlabaj commented on packages/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx
> +        <Text>Disabled text area </Text>
can you update the cypress test to verify expected behaviour.

2020-12-03 18:27 UTC, boaz0 commented
Hi @tlabaj, I added tests to cypress as you requested. Sorry for the late response :bow:

2020-12-07 17:06 UTC, tlabaj approved these changes

2020-12-07 17:08 UTC, kmcfaul approved these changes

2020-12-07 17:08 UTC, redallen approved these changes

2020-12-07 17:08 UTC, merged

2020-12-07 21:43 UTC, boaz0 commented
Thank you all!