chore(docs): release notes 2020.15
patternfly/patternfly-react pull request #5155
Opened 2020-11-17 22:45 UTC by tlabaj

**What**: Closes #5154 

**Additional issues**:

2020-11-17 22:50 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5155.surge.sh

2020-11-18 14:26 UTC, redallen requested changes

2020-11-18 14:26 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +  - updated breakpoints and formatting examples. Created collapsed variant. ([#5123](https://github.com/patternfly/patternfly-react/pull/5123))
Change to "Updated"

2020-11-18 14:26 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +  - Fixed example codesandbox ([#5065](https://github.com/patternfly/patternfly-react/pull/5065))
The tabbing for these items is off.

2020-11-18 15:02 UTC, evwilkin requested changes
sentence case needed for Dual list selector & Tree view, and the indentation is off for the items under "Chore" at the bottom as @redallen noted.

2020-11-18 15:02 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +- **DualListSelector:**
Sentence case

2020-11-18 15:02 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +- **Tree View:**
Sentence case

2020-11-18 15:03 UTC, redallen requested changes

2020-11-18 15:03 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +  - pdated breakpoints and formatting examples. Created collapsed variant. ([#5123](https://github.com/patternfly/patternfly-react/pull/5123))
Missing the "U" in "Updated".

2020-11-18 17:22 UTC, evwilkin commented
PR #5158 has now been merged for this release as well.

2020-11-19 15:22 UTC, redallen approved these changes

2020-11-19 15:35 UTC, evwilkin approved these changes
LGTM - thanks!

2020-11-19 15:36 UTC, merged

2020-11-19 15:57 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.10.72

Thanks for your contribution! :tada: