fest(react-core): Update react-core copyStyles.js
patternfly/patternfly-react pull request #5166
Opened 2020-11-19 16:00 UTC by sjd78

Update react-core's `copyStyles.js` generate script to generate both the pure PF4 `base.css` file and the PF3+PF4 no reset
`base-no-reset.css` file.  This will allow a project using both PF3-react and PF4-react on the same page without resorting to using sass or falling back to PF4's `patternfly-no-reset.css`.

Before this PR, if a project uses PF3 and PF4, and doesn't want to adopt sass, the css imports would be:
```jsx
import 'patternfly-react/dist/css/patternfly-react.css' // PF3-react
import '@patternfly/patternfly/patternfly-no-reset.css' // PF4
```

After this PR is merged, projects just using PF4 can still import the `base.css` normally:
```jsx
import '@patternfly/react-core/dist/style/base.css'
```

But, now projects using PF3 and PF4 can use the new react-core `base-no-reset.css` that includes the optimizations of the current `base.css`:
```jsx
import 'patternfly-react/dist/css/patternfly-react.css' // PF3-react
import '@patternfly/react-core/dist/style/base-no-css.css' // PF4-react
```

2020-11-19 16:07 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5166.surge.sh

2020-12-07 16:07 UTC, redallen commented
Unfortunately `@patternfly/patternfly/patternfly-no-reset.css` is not a "base" 40Kb stylesheet like `@patternfly/patternfly/patternfly-base.css` but rather 850Kb of every PatternFly component. This means after this PR if you write:
```
import '@patternfly/react-core/dist/style/base-no-reset.css' // PF4-react
import { Button } '@patternfly/react-core'
```
you'd get styles for ALL components on the first line and `Button.css` styles a second time on the second line.

@mcoker Can we make a `patternfly-base-no-reset.css` upstream?

2020-12-07 16:42 UTC, mcoker commented
@redallen sure! https://github.com/patternfly/patternfly/issues/3735

2020-12-07 16:54 UTC, dlabrecq reviewed
I prefer not to have any PF3 styles in order to keep is as small as possible for my app.

2020-12-07 16:55 UTC, redallen commented
@dlabrecq This doesn't add PF3 styles. It just reexports the `no-reset` styles from Core which don't override existing PF3 styles.

2020-12-07 17:09 UTC, sjd78 commented
@redallen - To add to the fun, at least on ovirt, extensions are loaded into an iframe.  We do a React portal to the parent frame to render the modal.  Part of the portal element creation is pushing the css to the parent frame so the Modal gets styled properly.  The only way I've found to make sure everything PF4 gets styled properly is to use the full style sheet.

Unless you have some ideas on how to let the dynamic style loading the components do reflect in the iframe's parent?

2020-12-07 17:20 UTC, redallen requested changes
If you need the whole stylesheet your existing `import '@patternfly/patternfly/patternfly-no-reset.css'` works well and I'd recommend [using `null-loader` on `react-styles/css/**/*.css`](https://github.com/patternfly/patternfly-org/blob/master/packages/theme-patternfly-org/scripts/webpack/webpack.client.config.js#L82) to only load CSS once.

The reexporting base styles from react-core is just for convenience using our current "only load the CSS you need" model and we aren't aiming to reexport all of `@patternfly/patternfly`. I still find it useful to reexport a `base-no-reset` for consumers transitioning from PF3 that want to use this model.

2020-12-07 17:20 UTC, redallen commented on packages/react-core/scripts/copyStyles.js
> +  'base-no-reset.css': 'patternfly-no-reset.css'
Once #5219 is in just change this to `patternfly-base-no-reset.css`.

2020-12-07 17:26 UTC, sjd78 commented
> If you need the whole stylesheet your existing `import '@patternfly/patternfly/patternfly-no-reset.css'` works well and I'd recommend [using `null-loader` on `react-styles/css/**/*.css`](https://github.com/patternfly/patternfly-org/blob/master/packages/theme-patternfly-org/scripts/webpack/webpack.client.config.js#L82) to only load CSS once.

Oh that's a good idea!

> 
> The reexporting base styles from react-core is just for convenience using our current "only load the CSS you need" model and we aren't aiming to reexport all of `@patternfly/patternfly`. I still find it useful to reexport a `base-no-reset` for consumers transitioning from PF3 that want to use this model.

Will do. Hopefully it'll be useful for us on ovirt-web-ui (which is mostly PF3) soon(ish).

2020-12-08 18:30 UTC, redallen approved these changes
LGTM, thanks @sjd78 !

2020-12-08 19:30 UTC, evwilkin approved these changes
LGTM

2020-12-08 19:31 UTC, merged

2020-12-08 19:55 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.8.120
 - @patternfly/react-console@4.1.21
 - @patternfly/react-core@4.83.2
 - @patternfly/react-docs@5.12.10
 - @patternfly/react-inline-edit-extension@4.5.181
 - demo-app-ts@4.63.2
 - @patternfly/react-table@4.19.39
 - @patternfly/react-topology@4.6.84
 - @patternfly/react-virtualized-extension@4.5.165

Thanks for your contribution! :tada: