feat(CodeEditor): add new code editor
patternfly/patternfly-react pull request #5294
Opened 2020-12-22 19:04 UTC by nicolethoen

I need to figure out how to get focus out of editor using keyboard

still needs jest and cypress tests

still need to update some aria-label props and prop descriptions

but i'm done with it until after shut down :)

2020-12-22 19:13 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5294.surge.sh

2021-01-04 20:24 UTC, mcarrano commented
@nicolethoen I took a quick look at this today. It's looking good. I just had a couple of questions/comments:

* In read-only mode, I'm still able to get a text cursor even though I can't enter anything. Per the design here, https://marvelapp.com/prototype/b284chd/screen/70964527, when in read-only mode the user should see a gray background and not be able to interact with the editor. There is a core example here: https://www.patternfly.org/v4/components/code-editor#read-only
* All tool buttons should have tooltips per the design.
* I can't seem to be able to make upload work. I can choose a file, but not seeing anything loaded into the editor. Should this work?

Let me know if you have any questions after looking at the Marvel document. @gdoyle worked on this and can also be consulted with any design questions.

cc @evwilkin

2021-01-04 20:41 UTC, nicolethoen commented
@mcarrano 

> * In read-only mode, I'm still able to get a text cursor even though I can't enter anything. Per the design here, https://marvelapp.com/prototype/b284chd/screen/70964527, when in read-only mode the user should see a gray background and not be able to interact with the editor. There is a core example here: https://www.patternfly.org/v4/components/code-editor#read-only

- the read only styling will need to be handled by core, i think. I've applied the readOnly styles provided, but they do not currently impact anything inside the actual editor.

> * All tool buttons should have tooltips per the design.

- i can do that!

> * I can't seem to be able to make upload work. I can choose a file, but not seeing anything loaded into the editor. Should this work?

- Core and I still need to create/implement error states, but the uploaded file type needs to match the specified language, that may be why it is not working.

2021-01-04 20:49 UTC, evwilkin commented
@nicolethoen the tooltip isn't displaying if you click on the icon, only if you click in the blank space around the icon.

> I can't seem to be able to make upload work. I can choose a file, but not seeing anything loaded into the editor. Should this work?

After trying several file types a `.txt` file uploaded & opened fine. Per your suggestion I added the `language="javascript"` prop and then the `.txt` file wouldn't upload but the `.js` file started working as expected for upload 👍  I think that if this is the expected behavior we should call it out in the docs somewhere.

2021-01-04 21:13 UTC, mcarrano commented
> the uploaded file type needs to match the specified language, that may be why it is not working.
Yes, thanks for the tip. It works when I correctly set the prop. Agree with @evwilkin that we should document this somewhere.

> the read only styling will need to be handled by core, i think. I've applied the readOnly styles provided, but they do not currently impact anything inside the actual editor.

@mcoker can you look at/comment on this?

2021-01-05 00:18 UTC, mcoker commented
This looks good to me. The component is pretty simple on the core side. We allow for an HTML `<pre>` tag that uses our monospace font "Liberation Mono", which I'm assuming would be used to represent a static code block (not using the monaco editor). That looks like this:

<img width="293" alt="Screen Shot 2021-01-04 at 5 54 46 PM" src="https://user-images.githubusercontent.com/35148959/103591627-4e52dd80-4eb6-11eb-9928-26ffae4ffb6d.png">

The same block in the monaco editor looks like this

<img width="362" alt="Screen Shot 2021-01-04 at 5 54 40 PM" src="https://user-images.githubusercontent.com/35148959/103591662-63c80780-4eb6-11eb-853a-2427bfe12f8d.png">

I'm not sure if we would want to create some sort of parity in the font family, size, etc?

It also seems like it might look better if the padding around the editor were changed. Here is what it looks like without the padding. You achieve that by not including the `pf-c-code-editor__code` element. I think our intent with that element is for when static code is placed in the editor, though we may want to change that so that static code and monaco editor code look more similar.

<img width="826" alt="Screen Shot 2021-01-04 at 6 02 14 PM" src="https://user-images.githubusercontent.com/35148959/103591884-0ed8c100-4eb7-11eb-979d-61226dae8356.png">

> the read only styling will need to be handled by core

Assuming there isn't something out of the box we can use built in to the editor, and we don't want to go another route to indicate that the editor is read-only (couple of ideas below), we probably want to look at what options are available to style/theme it, and apply some sort of read only styles. 

<img width="818" alt="Screen Shot 2021-01-04 at 6 17 02 PM" src="https://user-images.githubusercontent.com/35148959/103592601-14cfa180-4eb9-11eb-9e87-6cbdf5939e1c.png">
<img width="817" alt="Screen Shot 2021-01-04 at 6 14 49 PM" src="https://user-images.githubusercontent.com/35148959/103592602-15683800-4eb9-11eb-90fe-f5d2e8f597c4.png">

2021-01-07 14:36 UTC, redallen requested changes
What's our plan for language support?

2021-01-07 14:36 UTC, redallen commented on packages/react-code-editor/package.json
> +    "react-dropzone": "9.0.0",
Move these 3 to dependencies.

2021-01-07 14:36 UTC, redallen commented on packages/react-code-editor/package.json
> +  "version": "0.0.0",
Change to 4.0.0

2021-01-07 14:36 UTC, redallen commented on packages/react-code-editor/package-lock.json
> +{
Remove this file.

2021-01-07 15:05 UTC, nicolethoen commented
> What's our plan for language support?

I know of no particular plan. 
The editor has a fairly extensive list of languages it supports. I built some enums and mappings for languages/extensions, so right now the consumer is limited to the languages I specified there. We can add more. I know that'd need to be documented.

I'm open to suggestions or insights. My initial approach was a bit of a stab in the dark to get this PR up.

2021-01-07 15:18 UTC, redallen commented
Oh I completely missed the `language` prop which works splendidly!

I'm noticing that this PR loads 4 files from `cdn.jsdelivr.net`:
![image](https://user-images.githubusercontent.com/47335686/103909240-74a09500-50d1-11eb-9dc4-12e99a5a2fb7.png)

PatternFly has never required an external CDN... do you know if it's possible to import these files directly instead?

2021-01-08 16:11 UTC, gdoyle1 commented
@nicolethoen is there a way we can make the react code flexible enough to include custom actions? I was assuming that download copy and upload were just examples... depending on the use case, they may need to be different. Here's an example of what I mean where the terminal action would run that command in a web terminal. Created this by just editing the HTML component that's been released
![Screen Shot 2021-01-08 at 11 07 46 AM](https://user-images.githubusercontent.com/30870144/104037068-37580800-51a2-11eb-874c-311077f1524f.png)

2021-01-08 16:22 UTC, nicolethoen commented
@gdoyle1 I am happy to try! I'll let you know if I run into any issues

2021-01-08 19:23 UTC, mcarrano commented
@gdoyle1 Do you think we should have some actions that are permanent/standard? Like Upload or Copy to Clipboard? Or should all the actions just be passed through a prop? I guess that would require the consumer to pass an icon, and callback function, and possibly a tooltip for each action. Thoughts @nicolethoen ?

2021-01-08 20:23 UTC, nicolethoen commented
@mcarrano i could do it so that the actions are customizable, i think. But then the example which implements the upload/download/copy would probably need to be a demo because the user would need to build the empty state and the dropzone in that case. is that okay?

2021-01-08 21:29 UTC, mcarrano commented
I don't know @nicolethoen . I kind of like that these features are built into the component.

@gdoyle1 do you see any reason you would want to remove or customize any of the standard features? What is we made it so you could add additional actions which could be custom?

2021-01-11 13:18 UTC, gdoyle1 commented
> I don't know @nicolethoen . I kind of like that these features are built into the component.
> 
> @gdoyle1 do you see any reason you would want to remove or customize any of the standard features? What is we made it so you could add additional actions which could be custom?

@mcarrano Allowing additional actions that are custom would be fine - as long as you can optionally remove a standard feature (if you didn't offer uploading in the code editor, you can remove that action), then I think we can just add a "custom" action additionally

2021-01-14 16:57 UTC, gdoyle1 commented
@nicolethoen here's the OpenShift keyboard shortcut accessibility add-on feature I was referring to in our meeting
![Screen Shot 2021-01-14 at 11 45 43 AM](https://user-images.githubusercontent.com/30870144/104622654-8816a780-565f-11eb-9a83-fe159935ee0a.png)
![Screen Shot 2021-01-14 at 11 45 38 AM](https://user-images.githubusercontent.com/30870144/104622655-88af3e00-565f-11eb-964c-a36a8b8f205a.png)

2021-01-14 17:05 UTC, christianvogt commented
![image](https://user-images.githubusercontent.com/14068621/104623871-d24c5880-5660-11eb-99e5-8d4a5ab76903.png)

2021-01-15 15:28 UTC, nicolethoen commented
@redallen  
> PatternFly has never required an external CDN... do you know if it's possible to import these files directly instead?

Would this solution work in PF?
If it looks promising to you i'll reach out so you can help me understand it.
https://github.com/suren-atoyan/monaco-react#config

2021-01-15 15:35 UTC, redallen commented
Yes that looks promising! I'm happy to dig into the source to figure out how to load from node_modules instead.

2021-01-22 16:07 UTC, kmcfaul commented
Everything seems good to me. Only thing I noticed is for the keyboard interaction, `Shift + Tab` takes you out of the editor while `Escape` does nothing. I think either keybind works, just curious if `Escape` should also have that behavior?

2021-01-22 18:17 UTC, nicolethoen commented
@kmcfaul I will look into it. 
I do know that the editor uses many key controls already so I'll have to investigate if the escape button already has some function in the editor. The editor's key controls are extensive so I'm not sure.

2021-01-22 18:38 UTC, kmcfaul commented
Yeah understandable. I didn't notice it do anything but perhaps there is an edge case. But in any case I'm fine with the current keyboard handling, I don't think this is a blocker or anything.

2021-01-22 19:05 UTC, jessiehuff reviewed
I was actually just about to chime in about that too haha. 🙂   I think that the current keyboard implementation is SO much better than what is defaulted by Monaco. I'm not sure what key commands that the Monaco editor uses though so I'm not positive what's available to us and what's not. I checked with Jenn on this one as well because there's not really a common standard on this pattern so I wanted to make sure that we talked about it. Jenn agreed that this is currently pretty awesome. 

When talking it out though, we wondered if Shift + Tab would conflict with anything in Monaco? We talked about how maybe we could also implement using Enter to get into the editor as well as the down arrow key, and like Katie's comment, we wondered if the Esc key would feel more natural to escape than the Shift + Tab. Though, truthfully, if it stayed the way it is now, I still think it's a massive improvement to the "Tab trapping" that Monaco does. But I think which interaction we use is definitely open for debate. It's a subjective thing that not a lot of people have done before from what I can find. (Another cool way that we're paving the way for accessibility! 😄 )

We also discussed whether we should include instructions in some way for users as part of the design because we don't know what keyboard users would expect (since it's not a common or firm standard). However, I know that's more of a design question. 🙂

2021-01-22 19:56 UTC, nicolethoen commented
@jessiehuff 
so, in the first example, if you start typing, you'll see that (since the language is set to javascript) as you type, an autocomplete or intellisense feature that pops up. Escape closes that box.

2021-01-25 15:15 UTC, tlabaj commented on packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
> +  isLanguageLabel?: boolean;
How about `isLanguageLabelVisible`

2021-01-25 15:15 UTC, tlabaj commented on packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
> +  isAllowCopy?: boolean;
how about `isCopyButtonVisible`

2021-01-25 15:15 UTC, tlabaj commented on packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
> +  isDisplayMinimap?: boolean;
maybe `isMinmapDisplayed` or `isMinmapVisible`

2021-01-25 16:06 UTC, redallen approved these changes
LGTM from the build side!

2021-01-25 16:07 UTC, tlabaj submitted a review, later dismissed
LGTM

2021-01-25 16:08 UTC, tlabaj commented
Looks like you have a conflict and linting errors.

2021-01-25 16:16 UTC, kmcfaul submitted a review, later dismissed
Looks good! Just need to resolve the conflict

2021-01-25 16:16 UTC, mcarrano reviewed
Looks good @nicolethoen . The only question I have from a design perspective is what this example is intended to show: https://patternfly-react-pr-5294.surge.sh/components/code-editor#with-custom-control

This is what I see, even though it looks like you are declaring that a Play button should be added to the toolbar.

![Screen Shot 2021-01-25 at 11 16 07 AM](https://user-images.githubusercontent.com/6619860/105732786-d39e4080-5efe-11eb-8fcb-b04328083ef7.png)

2021-01-25 16:28 UTC, nicolethoen commented
> Looks good @nicolethoen . The only question I have from a design perspective is what this example is intended to show: https://patternfly-react-pr-5294.surge.sh/components/code-editor#with-custom-control
> 
> This is what I see, even though it looks like you are declaring that a Play button should be added to the toolbar.
> 
> ![Screen Shot 2021-01-25 at 11 16 07 AM](https://user-images.githubusercontent.com/6619860/105732786-d39e4080-5efe-11eb-8fcb-b04328083ef7.png)

@mcarrano if you begin putting code in the editor, the controls appear. It's a custom `execute` command, which only makes sense if there is code in the editor to execute.

2021-01-25 17:23 UTC, mcarrano approved these changes
> @mcarrano if you begin putting code in the editor, the controls appear. It's a custom execute command, which only makes sense if there is code in the editor to execute.

Thanks for the clarification @nicolethoen . I would prefer that the buttons be visible and disabled in this case, but I will not hold up the release for this. I'm OK to open a follow-up issue for this.

2021-01-25 17:28 UTC, tlabaj approved these changes

2021-01-25 17:32 UTC, kmcfaul approved these changes

2021-01-25 17:33 UTC, redallen approved these changes

2021-01-25 17:34 UTC, merged

2021-01-25 17:45 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@4.1.0
 - @patternfly/react-docs@5.15.0

Thanks for your contribution! :tada: