fix(Wizard): add wizard demos to match core
patternfly/patternfly-react pull request #5325
Opened 2021-01-12 21:31 UTC by nicolethoen

Closes #4780

2021-01-12 21:36 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5325.surge.sh

2021-01-19 18:25 UTC, kmcfaul approved these changes
lgtm

2021-01-19 18:53 UTC, mcarrano reviewed
This looks good @nicolethoen . I just have one question. For the In Page version. I notice that in the core demo, the buttons are anchored to the bottom of the page where in the react version they fall in the middle of the page. I don't have a strong opinion on which is correct, but unclear why they are different. Do we set a fixed height on the wizard or is it designed to fill the page? @mcoker thoughts?

2021-01-20 01:06 UTC, mcoker commented on packages/react-core/src/demos/Wizard/WizardDemo.md
> +              height={400}
```suggestion
```

2021-01-20 01:07 UTC, mcoker requested changes
Looks like there is an unnecessary height limitation on the in page wizard. That's what's keeping it from consuming the page height @mcarrano

2021-01-20 19:54 UTC, jessiehuff approved these changes
LGTM!

2021-01-20 21:12 UTC, mcarrano approved these changes
Looks great @nicolethoen .

2021-01-23 00:57 UTC, mcoker approved these changes
🤩👍

2021-01-25 15:47 UTC, tlabaj approved these changes

2021-01-25 15:48 UTC, merged

2021-01-25 16:02 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.9.11
 - @patternfly/react-console@4.2.11
 - @patternfly/react-core@4.89.2
 - @patternfly/react-docs@5.14.2
 - @patternfly/react-inline-edit-extension@4.6.11
 - demo-app-ts@4.68.2
 - @patternfly/react-table@4.20.11
 - @patternfly/react-topology@4.7.11
 - @patternfly/react-virtualized-extension@4.6.11

Thanks for your contribution! :tada: