feat(Modal): support disabling the 'Close' button on the modal header
patternfly/patternfly-react pull request #5359
Opened 2021-01-22 13:32 UTC by KKoukiou

When onCloseDisabled is set the modal can't be closed using Escape key
either.

Fixes #5210
Closes #5359

2021-01-22 13:37 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5359.surge.sh

2021-01-25 17:13 UTC, KKoukiou commented
Rebased to solve conflict.

2021-02-01 21:27 UTC, mcarrano approved these changes
Looks good to me. Thanks @KKoukiou .

2021-02-03 17:20 UTC, tlabaj requested changes
Look good.  Can you just add the new prop to the demo-app and add an integration test for this.

2021-02-09 19:44 UTC, jessiehuff reviewed
I find the example here slightly confusing. From an accessibility standpoint, if you trap focus there has to be a clear way to get out and to have that communicated to users. Here, the user can still get out of the modal by confirming or cancelling so there's a way out, but it seems confusing to me to see the disabled close button without understanding why it's disabled. In this example, why wouldn't we just not show the close button? Should there be some way to communicate that there's a process happening or that input is required or some design guideline that helps users to know when this will be used and how to include a11y in that? I also noticed that there's not a core example of this. Should there be an issue to create that example in core as well?

2021-02-09 19:52 UTC, KKoukiou commented
> I find the example here slightly confusing. From an accessibility standpoint, if you trap focus there has to be a clear way to get out and to have that communicated to users. Here, the user can still get out of the modal by confirming or cancelling so there's a way out, but it seems confusing to me to see the disabled close button without understanding why it's disabled. In this example, why wouldn't we just not show the close button? Should there be some way to communicate that there's a process happening or that input is required or some design guideline that helps users to know when this will be used and how to include a11y in that? I also noticed that there's not a core example of this. Should there be an issue to create that example in core as well?

Good point, I was not aware about the accessibility issues this might cause.

The use case I have is that many modals (in Cockpit) when submitted perform operations that can't be stopped. For these modals, 
* I disable the `cancel` button,
*  show a spinner in the submit button
* disable all input fields

Of course Esc and [x] have to also be disabled or hidden though for the modal to no unexpectedly close.
 
For consistency with the rest of the modals in our project, which don't have non-interruptible operations, and therefore can be stopped by closing the modal, I thought we should always have the close button available, just sometimes disabled when the 'Cancel' button is also disabled.

Another approach would be to always allow closing the modal by 'cancel' or [x] or Esc but have a warning that the operation started will continue on the background.

Either of the two approaches would work for me. So if some designer here feels that they want to advice me to follow one of the two approaches, I am happy to proceed accordingly. 

I just find important that all modals within a project don't deviate visually from one another.

2021-02-09 22:11 UTC, mcarrano commented
@KKoukiou @jessiehuff I at first found this example confusing also since there no context. Should Cancel as well as Close be disabled? Maybe Confirm should change to Exit? I don't think the close button should be hidden since it might be available prior to the action.

I agree that there a design question here that goes beyond the scope of this example. By holding the user in this dialog with no way to close it, there is no way out if the operation hangs or takes too long, for example. I guess you could allow the dialog to be closed and then use a toast alert to signal the user when the process is complete. But this is really a product design question that I don't think we can enforce via PatternFly.

2021-02-10 08:08 UTC, KKoukiou commented
@mcarrano @jessiehuff thanks for taking time to answer here. I am fine with handling it as @mcarrano suggested, in that case we can close this.

2021-02-10 16:51 UTC, tlabaj commented
closing this one as a result of the discussion.

2021-02-10 16:51 UTC, closed without merging