feat(card): add pf-m-display-lg and pf-m-rounded
patternfly/patternfly-react pull request #5389
Opened 2021-01-27 20:47 UTC by redallen

**What**: Closes #5334

**Additional issues**:

2021-01-27 20:52 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5389.surge.sh

2021-01-28 14:39 UTC, KKoukiou approved these changes
Nice parametrization of the examples code @redallen!

Your change it of course totally fine codewise, I just wonder why PF wants to expose to its consumers that isRounded property. It causes a really subtle difference, and I feel that the PF designers should decide if the cards should have rounded corners or not and not let the consumers make decisions about it.

After all, the reason that we all use PF and not custom styling is in order that all RH products have the same Ui experience.

So, this PR is fine to go in but I really don't see the usecase for it.

2021-01-28 14:41 UTC, redallen commented
@KKoukiou This thread has the context behind pf-m-rounded: https://github.com/patternfly/patternfly/issues/3670 . I'd ask @mcarrano its purpose.

2021-01-28 16:56 UTC, mcarrano commented
You ask a valid question @KKoukiou . This originated from the web properties design team wanting to use PatternFly to present more marketing oriented content. @mmenestr do you know if we have plans to add this guidance to our design guidelines for Cards? I agree that we don't want designers to just arbitrarily pick styling. Products and web applications should stick with the squared corners.

2021-01-28 17:03 UTC, mmenestr commented
@mcarrano I don't believe we do. This is the first I've heard of this! Just to make sure I have the info right, is it just a modifier to give cards the capability of having rounded edges? And we want to recommend that this only be done for marketing purposes and that products keep using non-rounded cards?

2021-02-01 18:53 UTC, mcoker reviewed
`isLarge` and `isCompact` shouldn't be used together - do we need to do anything special for that?

2021-02-01 19:05 UTC, redallen commented
@mcoker Unfortunately since we've already released `isCompact` there isn't much we can do. I've added a warning and will default to `isCompact` if both are specified.

2021-02-01 19:29 UTC, kmcfaul commented
Can we also add something to both prop descriptions (isLarge and isCompact) for clarity? Like `Should not be used together with {X}`. Or maybe the console warning is enough?

2021-02-01 19:32 UTC, redallen commented
@kmcfaul I added that to the prop description.

2021-02-01 19:43 UTC, mcoker approved these changes
L👍TM!

2021-02-01 20:46 UTC, jessiehuff reviewed
I really like the modifier example! It's really neat to be able to play with all of the different modifiers. Can we add the keyboard interaction to the selectable example though? I currently can't select it by keyboard or screen reader the way I could with the previous selectable example. (I'm hoping that by adding the keyboard interaction, it'll work through screen reader as well.)

2021-02-01 20:55 UTC, redallen commented
@jessiehuff I've removed the `isSelectable` and `isSelected` to avoid confusion and keep the demo simple.

2021-02-01 21:29 UTC, mcarrano submitted a review, later dismissed
Looks good to me. Thanks @redallen .

2021-02-01 23:41 UTC, tlabaj requested changes
looks good.  Can you just update the demo app and add test for new props.

2021-02-01 23:41 UTC, tlabaj commented on packages/react-core/src/components/Card/Card.tsx
> +    // eslint-disable-next-line no-console
can you add a test for this

2021-02-02 18:08 UTC, redallen commented on packages/react-core/src/components/Card/Card.tsx
> +    // eslint-disable-next-line no-console
Done

2021-02-02 18:46 UTC, kmcfaul approved these changes

2021-02-02 18:46 UTC, merged