bug(codeeditor) Displays empty state if one is supplied 🥳
patternfly/patternfly-react pull request #5413
Opened 2021-02-02 20:07 UTC by AllenBW

no issue, cuz this was a quick n easy one, presently , users supplying empty states dont see em CUZ they're hidden by that showEmptyState toggle 

now ya'll see one if its provided

2021-02-02 20:11 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5413.surge.sh

2021-02-02 20:14 UTC, redallen requested changes

2021-02-02 20:14 UTC, redallen commented on packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
> +                    {showEmptyState || providedEmptyState && !value ? emptyState : editor}
The `&&` evaluates first. I think you meant `(showEmptyState || providedEmptyState) && !value ? emptyState : editor`?

2021-02-02 20:22 UTC, redallen commented
Try `yarn lint:ts --fix`. I think it's complaining about spacing

2021-02-02 20:57 UTC, redallen approved these changes

2021-02-03 13:46 UTC, AllenBW commented
any chance @nicolethoen yah could take ah look at this one 🤞 🌺

2021-02-03 13:51 UTC, nicolethoen approved these changes
Good catch!

2021-02-03 14:29 UTC, redallen approved these changes

2021-02-03 14:29 UTC, merged

2021-02-03 14:40 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@4.1.9
 - @patternfly/react-docs@5.15.12

Thanks for your contribution! :tada: