feat(FormSelect): added support for placeholder styled option
patternfly/patternfly-react pull request #5428
Opened 2021-02-09 02:43 UTC by tlabaj

**What**: Closes #5335

2021-02-09 02:47 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5428.surge.sh

2021-02-09 14:36 UTC, redallen approved these changes

2021-02-09 21:04 UTC, mcarrano approved these changes
Looks good @tlabaj !

2021-02-09 23:43 UTC, mcoker submitted a review, later dismissed
🤠👍

2021-02-10 16:53 UTC, evwilkin commented on packages/react-core/src/components/FormSelect/FormSelect.tsx
> +    /* find sekected option and get placeholder flag */
```suggestion
    /* find selected option and get placeholder flag */
```

2021-02-10 16:58 UTC, evwilkin commented on packages/react-core/src/components/FormSelect/FormSelectOption.tsx
> +  /* flag indicating if option will have placeholder styling applied when selected*/
```suggestion
  /* flag indicating if option will have placeholder styling applied when selected */
```
This missing space is causing this text not to show up for prop description on the site.

2021-02-10 16:58 UTC, evwilkin requested changes
Functionality looks great, just 2 typos in the documentation

2021-02-10 17:00 UTC, evwilkin approved these changes
LGTM

2021-02-10 18:57 UTC, redallen approved these changes

2021-02-10 22:27 UTC, dlabrecq approved these changes
LGTM

2021-02-11 14:37 UTC, nicolethoen approved these changes

2021-02-11 14:45 UTC, merged

2021-02-11 14:57 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.9.27
 - @patternfly/react-code-editor@4.1.18
 - @patternfly/react-console@4.2.27
 - @patternfly/react-core@4.94.0
 - @patternfly/react-docs@5.15.23
 - @patternfly/react-inline-edit-extension@4.6.28
 - demo-app-ts@4.72.0
 - @patternfly/react-integration@4.72.0
 - @patternfly/react-table@4.20.28
 - @patternfly/react-topology@4.7.27
 - @patternfly/react-virtualized-extension@4.6.28

Thanks for your contribution! :tada: