feat(SearchInput): add advanced search feature
patternfly/patternfly-react pull request #5454
Opened 2021-02-11 17:14 UTC by nicolethoen

Closes: #5332 

Note: tests coming very soon - just wanted to get the PR up for review

2021-02-11 17:19 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5454.surge.sh

2021-02-11 18:43 UTC, kmcfaul commented
Pressing `space` in the username/first name fields adds a space to the `has words` field, which I found a little odd. I understand space not doing anything for the first two fields (though maybe it should work in the first name field, for compound names?) but I don't think it should be editing anything for a different field.

2021-02-11 19:41 UTC, mcarrano requested changes
This is looking great @nicolethoen ! I encountered the same issue as @kmcfaul . The only other nit I had was that we should not assume a default for the delimiter character but make the consumer declare it explicitly. Not sure that we have an accepted standard inside Red Hat.

2021-02-11 22:30 UTC, mcoker commented on packages/react-core/src/components/SearchInput/SearchInput.tsx
> +              <Button variant="primary" onClick={onSearchHandler}>
Random but should this have `type="submit"`?

```suggestion
              <Button type="submit" variant="primary" onClick={onSearchHandler}>
```

2021-02-11 22:31 UTC, mcoker commented on packages/react-core/src/components/SearchInput/SearchInput.tsx
> +                <Button variant="link" onClick={onClear}>
`type="reset"`?

```suggestion
                <Button  type="reset" variant="link" onClick={onClear}>
```

2021-02-11 22:32 UTC, mcoker commented on packages/react-core/src/components/SearchInput/examples/SearchInput.md
> +import { Checkbox, SearchInput, Stack, StackItem } from '@patternfly/react-core';
Do you need `Stack` and `StackItem`? Doesn't look like they're used.

```suggestion
import { Checkbox, SearchInput } from '@patternfly/react-core';
```

2021-02-11 22:34 UTC, mcoker reviewed
Looks great! 👍 Left a few comments for review.

2021-02-12 14:20 UTC, tlabaj commented on packages/react-core/src/components/SearchInput/SearchInput.tsx
> +  attr: string;
can you add descriptions to these and expose it in the docs.

2021-02-12 14:20 UTC, tlabaj commented on packages/react-core/src/components/SearchInput/examples/SearchInput.md
> +### Advanced
Add `SearchAttribute` on line 5

2021-02-12 14:22 UTC, tlabaj requested changes

2021-02-12 14:22 UTC, tlabaj commented on packages/react-core/src/components/SearchInput/SearchInput.tsx
> +  advancedSearchDelimiter?: string;
this is also missing a description

2021-02-12 19:33 UTC, kmcfaul approved these changes
I'm still seeing the odd behavior with `space` but I don't think its a blocker and can be addressed later on. Everything else looks good.

2021-02-12 19:56 UTC, tlabaj approved these changes
LGTM

2021-02-12 20:04 UTC, evwilkin commented
I'm seeing the space bar issues @kmcfaul mentioned, and also seeing that if you add a space in the middle of the text for Username or First name fields it moves the text following the space from that field down to the Has words field - not sure if that's intentional or not

2021-02-12 20:09 UTC, mcoker approved these changes
L🍕TM!! 🥳

2021-02-12 20:36 UTC, nicolethoen commented
@evwilkin @kmcfaul 
There is possibly a lot more follow up work to be done to flesh out how to parse the search strings, possibly using quotation marks(?) or other special characters.

For now, the attribute/value pair cannot have any spaces because I have no way to know when a naked value is associated with a particular attributes, or if it's a stand alone value (and thus belongs in the 'has words' field). The `space` is what delimits one attribute/value pair from another. So if there is no attribute name paired (without a space) with a value, I am assuming it is a stand alone value.

Basically, I'm using the `space` to delimit attribute/value pairs.

2021-02-12 20:37 UTC, jessiehuff reviewed
This looks pretty good so far, Nicole!! It seems pretty decent in VO. I don't notice anything odd on Chrome, but I did find it weird that in Safari when VO gets to the input it just reads "first name John" instead of reading the aria label. I'm not sure why that would happen though.
My only concern is the keyboard interaction. I would expect it to follow more of a dropdown interaction pattern based on the design, and here I have to press space or enter on the button to get to the advanced and then tab to that dropdown before I'm able to interact with the form. I would think that the focus would shift into the dropdown like other implementations. Also, while using Tab to navigate in the dropdown here isn't too bad, typically in a dropdown you'd use up/down arrow keys. The general rule of thumb is that Tab typically navigates between components on a page or from region to region and arrow keys navigate within a component.

2021-02-12 20:38 UTC, mcarrano approved these changes
I am also good to go ahead and merge this. The space issue is indeed a bit odd. @nicolethoen maybe we can have more conversation about that and open a follow-on issue if needed.

@evwilkin I think that your other issue is expected behavior as I don't expect we would recognize a space as part of an attribute vale/name.

2021-02-12 20:42 UTC, evwilkin approved these changes

2021-02-12 21:06 UTC, nicolethoen commented
@jessiehuff I can make it so when the menu toggles open, focus goes to the first element in the menu. no problem!

This is actually a form more than a dropdown - even though it technically drops down.... gah!

2021-02-12 21:12 UTC, tlabaj commented
@nicolethoen can you please open up a follow up issue for the accessibility concerns and we can then merge this one.

2021-02-12 21:15 UTC, jessiehuff commented
> This is actually a form more than a dropdown - even though it technically drops down.... gah!

Yeah, some of these components that combine different interaction patterns can be confusing to know the right path forward. In the situation of a form in a modal, Tab is typically used. In a dropdown, up/down arrows are typically used. So combining them can leave us with a subjective decision on that. I think when Jenn and I discussed it before we were leaning towards arrow keys, but I'm ok with merging for now and maybe just following up later with any updates we iron out. The most pressing issue though is the shift in focus. I think a keyboard user would expect that if they select the advanced options button, they want to interact with it.

2021-02-12 21:16 UTC, jessiehuff approved these changes

2021-02-12 21:27 UTC, nicolethoen commented
@tlabaj issue opened!

2021-02-12 21:30 UTC, merged