feat(InputGroup): add plain input group text variant
patternfly/patternfly-react pull request #5478
Opened 2021-02-17 18:55 UTC by nicolethoen

Closes #5367

2021-02-17 19:01 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5478.surge.sh

2021-02-17 23:16 UTC, mcoker approved these changes
LGTM!

2021-02-24 20:27 UTC, tlabaj requested changes
looks good. can you just update the demo app please

2021-03-01 16:58 UTC, KKoukiou approved these changes

2021-03-01 19:22 UTC, tlabaj approved these changes

2021-03-03 20:49 UTC, merged