feat(LoginPage): enable show or hide password
patternfly/patternfly-react pull request #5481
Opened 2021-02-18 20:24 UTC by nicolethoen

Closes: #5422

2021-02-18 20:29 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5481.surge.sh

2021-02-18 21:52 UTC, mcarrano reviewed
Looks great @nicolethoen . Just missing the screenshot to link to the full page example.

2021-02-18 22:23 UTC, mcoker approved these changes
LGTM! 🥳

2021-02-19 14:11 UTC, nicolethoen commented
@redallen is there a command to run to generate and add full page screen shots?

2021-02-19 14:50 UTC, redallen commented
`yarn build:docs` -> `yarn serve:docs` -> (another terminal) `yarn workspace @patternfly/react-docs screenshots`.

This won't transfer to patternfly.org, though. It's most important to update the screenshots there every release.

2021-02-19 14:59 UTC, nicolethoen commented
@mcarrano I added updating example screenshots to my release to-do list. So that'll happen at release.

2021-02-19 16:57 UTC, jessiehuff submitted a review, later dismissed
LGTM! 🙂

2021-02-19 18:25 UTC, mcarrano submitted a review, later dismissed
> @mcarrano I added updating example screenshots to my release to-do list. So that'll happen at release.

I will approve then.

2021-02-24 20:12 UTC, tlabaj commented on packages/react-core/src/components/LoginPage/LoginForm.tsx
> +  showPasswordLabel?: string;
It looks like this prop and the one below are used for aria-label.  If that is the case I suggest `showPasswordAriaLabel` and `hidePasswordAriaLabel

2021-02-24 20:17 UTC, tlabaj commented on packages/react-core/src/components/LoginPage/LoginForm.tsx
> +          <TextInput
this is pretty much duplicate of lines 114-122.  can you make cont of that code and use that instead?

2021-02-24 20:18 UTC, tlabaj requested changes
just  a couple of comments

2021-03-01 19:20 UTC, tlabaj approved these changes

2021-03-02 15:01 UTC, jessiehuff approved these changes

2021-03-02 19:15 UTC, mcoker approved these changes

2021-03-02 19:30 UTC, merged

2021-03-02 19:43 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.10.5
 - @patternfly/react-code-editor@4.1.28
 - @patternfly/react-console@4.3.5
 - @patternfly/react-core@4.98.0
 - @patternfly/react-docs@5.16.8
 - @patternfly/react-inline-edit-extension@4.6.39
 - demo-app-ts@4.76.0
 - @patternfly/react-integration@4.77.0
 - @patternfly/react-table@4.23.5
 - @patternfly/react-topology@4.7.37
 - @patternfly/react-virtualized-extension@4.6.38

Thanks for your contribution! :tada: