remove unused dep
patternfly/patternfly-react pull request #5507
Opened 2021-03-02 20:31 UTC by redallen

**What**: As far as I can tell, charts and table don't need to use `@patternfly/patternfly`.

**Additional issues**:

2021-03-02 20:48 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5507.surge.sh

2021-03-04 18:47 UTC, dlabrecq approved these changes

2021-03-04 18:50 UTC, dlabrecq commented on packages/react-charts/package.json
> -    "@patternfly/patternfly": "4.90.0",
I don't believe we're using it to build, but it is a run-time dependency.

2021-03-04 18:57 UTC, dlabrecq requested changes
Should this be a peer dependency?

2021-03-04 19:08 UTC, redallen commented
@dlabrecq `@patternfly/patternfly` is not a runtime dependency unless you choose to use null-loader on `@patternfly/react-styles/css/*` (in which case you could argue its a peer dependency, but `@patternfly/react-*` releases on the same cadence `@patternfly/patternfly` does). I don't think optional peer dependencies belong in dependencies.

The only dependencies for styles for `@patternfly/react-table` and `@patternfly/react-charts` are `@patternfly/react-styles` and `@patternfly/react-tokens`. We can safely remove `@patternfly/patternfly`.

2021-03-05 01:35 UTC, dlabrecq commented
Ok. I see that `@patternfly/patternfly` isn't a dependency of `@patternfly/react-core` either.

2021-03-05 01:35 UTC, dlabrecq approved these changes

2021-03-05 14:19 UTC, tlabaj approved these changes

2021-03-05 14:19 UTC, merged

2021-03-05 14:39 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-charts@6.14.5
 - @patternfly/react-code-editor@4.2.0
 - @patternfly/react-docs@5.16.15
 - @patternfly/react-inline-edit-extension@4.6.46
 - demo-app-ts@4.80.0
 - @patternfly/react-integration@4.81.0
 - @patternfly/react-table@4.23.12

Thanks for your contribution! :tada: