Chore: release notes 2021.03
patternfly/patternfly-react pull request #5527
Opened 2021-03-08 16:06 UTC by tlabaj

**What**: Closes #5526

2021-03-08 16:08 UTC, redallen commented
Still waiting on https://github.com/patternfly/patternfly/pull/3909 and then a core bump.

2021-03-08 18:01 UTC, nicolethoen commented
@tlabaj could we also regenerate the example screen shots as part of this release-notes PR?

2021-03-08 18:04 UTC, redallen commented
After the core bump the commands to update the screenshots are:
1. `yarn build:docs && yarn serve:docs`
2. (new terminal) `yarn workspace @patternfly/react-docs screenshots` (you can add `"screenshots": "yarn workspace @patternfly/react-docs screenshots"` to the root `package.json` to just have to run `yarn screenshots` in the future)

2021-03-09 18:39 UTC, redallen commented
We'll need to fix https://app.circleci.com/pipelines/github/patternfly/patternfly-react/11541/workflows/21c9cda3-a75d-46a9-8250-57c06de19d60/jobs/54794, update the version numbers here, and then finally merge it.

2021-03-09 18:43 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5527.surge.sh

2021-03-09 20:25 UTC, redallen requested changes
syntax

2021-03-09 20:25 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +- [@patternfly/react-table@4.23.13]4](https://www.npmjs.com/package/@patternfly/react-table/v/4.23.14)
`13]4]` :(

2021-03-09 20:42 UTC, redallen approved these changes
LGTM!

2021-03-09 20:45 UTC, nicolethoen approved these changes

2021-03-09 20:56 UTC, merged

2021-03-09 21:13 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.16.18

Thanks for your contribution! :tada: