feat(textarea): add auto resizing
patternfly/patternfly-react pull request #5568
Opened 2021-03-24 14:14 UTC by redallen

**What**: Closes #5497 using https://github.com/patternfly/patternfly/pull/3883 and https://gomakethings.com/automatically-expand-a-textarea-as-the-user-types-using-vanilla-javascript/

**Additional issues**:

2021-03-24 14:20 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5568.surge.sh

2021-03-24 17:24 UTC, nicolethoen commented
I am not seeing any auto-resizing when I test it...
![Mar-24-2021 13-23-48](https://user-images.githubusercontent.com/26305082/112355617-36fce280-8ca4-11eb-9e8f-de2d7af7b29f.gif)

2021-03-24 17:33 UTC, redallen commented
@nicolethoen if you touch the borrom-right resizer it will stay whatever size you adjust it to. If you just type in the input you should see it autoresize, though:
![autoresize](https://user-images.githubusercontent.com/47335686/112357000-842d8400-8ca5-11eb-97cb-66f7ac266bc4.gif)

2021-03-24 17:51 UTC, nicolethoen approved these changes
ah yes

2021-03-25 12:58 UTC, tlabaj requested changes
looks good so far.  Can you add to demo-app and cypress test.

2021-03-25 13:56 UTC, mcarrano approved these changes
This looks great @redallen .

@andrewballantyne Does this behave as you expected?

2021-03-25 14:12 UTC, andrewballantyne commented
> This looks great @redallen .
> 
> @andrewballantyne Does this behave as you expected?

Yup! That performs just as expected. We use `rows={1}` prop as well in our use-case and I just tested that out here and it works well. Thanks for the support of the prop!

2021-03-25 14:13 UTC, tlabaj approved these changes
Looks great!

2021-03-25 14:59 UTC, merged