feat(Form): Added support for field groups
patternfly/patternfly-react pull request #5569
Opened 2021-03-24 15:14 UTC by tlabaj

**What**: Closes #5023 

**Additional issues**:

2021-03-24 15:43 UTC, jessiehuff reviewed
Looking good so far! 🙂  The only thing I noticed is that I think you're trying to include the toggle in the `aria-labelledby`, but the id you used to associate it is on the outer div (the `id="form-field-group-toggle140"`). If you want the "Details" `aria-label` on the button to be announced, the id should be on the button and then use that id in the `aria-labelledby`. So the `aria-labelledby` would still look like this: `aria-labelledby="field-group1-titleText-id form-field-group-toggle140"`, but the id would be on the button where the action is happening and that "Details" `aria-label` is.

2021-03-24 17:19 UTC, nicolethoen approved these changes

2021-03-24 19:27 UTC, mcarrano approved these changes
Looks great @tlabaj !

2021-03-24 20:52 UTC, jessiehuff approved these changes

2021-03-25 16:09 UTC, mcoker requested changes
Looks great @tlabaj! Just one comment about the toggle icon.

2021-03-25 16:09 UTC, mcoker commented on packages/react-core/src/components/Form/FormFieldGroupToggle.tsx
> +        {isExpanded ? <AngleDownIcon aria-hidden="true" /> : <AngleRightIcon aria-hidden="false" />}
If you wrap this in `span.pf-c-form__field-group-toggle-icon`, then you only need to include the right angle, and the CSS will rotate it with the expanded class on the field group parent element. That will also enable the transition animation of the icon rotating when toggling the expanded state.

Also why is `aria-hidden="false"` with one icon and not the other?

2021-03-25 20:11 UTC, mcoker submitted a review, later dismissed

2021-03-25 20:40 UTC, jessiehuff reviewed
Just a few updates to get the a11y tests working and fix the screen reader issues. 🙂

2021-03-25 20:40 UTC, jessiehuff commented on packages/react-core/src/components/Form/examples/Form.md
> +        <FormGroup label="Label 2" isRequired fieldId="form-expandable-field-groups-label2 ">
Here's one of the spaces causing one of the errors. On the `fieldId`.

2021-03-25 20:40 UTC, jessiehuff commented on packages/react-core/src/components/Form/examples/Form.md
> +        <FormGroup label="Label 4" isRequired fieldId="form-expandable-field-groups-label4 ">
I think this is the other space issue, on the `fieldId` again.

2021-03-25 20:40 UTC, jessiehuff commented on packages/react-core/src/components/Form/examples/Form.md
> +                id="form-expandable-field-groups-field-group1-label"
This is where one of the issues is coming from. See how the id and name don't match up with the fieldId for the label 1? You can see how the FormGroup below it matches. I think if you get these matching (maybe "form-expandable-field-groups-field-group1-label1), it'll fix that issue.

2021-03-25 21:23 UTC, tlabaj commented
Thanks Jessie!

2021-03-26 13:24 UTC, jessiehuff approved these changes
LGTM!

2021-03-26 14:58 UTC, kmcfaul commented
`FormFieldGroup` props should match `InternalFormFieldGroup` props so our docs show them (since the internal component isn't exported/picked up by our docs). Unless those extra props are all just for internal use?

2021-03-26 15:01 UTC, kmcfaul approved these changes

2021-03-26 15:48 UTC, mattnolting commented
Looks good! Side note, all the `input` s in https://patternfly-react-pr-5569.surge.sh/components/form#basic have the same ID.

2021-03-26 16:01 UTC, dlabrecq approved these changes

2021-03-26 17:51 UTC, mattnolting approved these changes
👍 👍

2021-03-26 18:29 UTC, merged

2021-03-26 18:48 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.10.26
 - @patternfly/react-code-editor@4.2.15
 - @patternfly/react-console@4.3.26
 - @patternfly/react-core@4.105.0
 - @patternfly/react-docs@5.16.31
 - @patternfly/react-inline-edit-extension@4.6.61
 - demo-app-ts@4.84.0
 - @patternfly/react-integration@4.85.0
 - @patternfly/react-table@4.23.27
 - @patternfly/react-topology@4.8.12
 - @patternfly/react-virtualized-extension@4.6.59

Thanks for your contribution! :tada: