feat(ExpandableSection): add detached variant, update tests
patternfly/patternfly-react pull request #5643
Opened 2021-04-09 14:59 UTC by kmcfaul

**What**: Closes #5581

- Adds `ExpandableSectionToggle` component for detached expandable sections.
- Adds `isDetached` flag to `ExpandableSection`. This removes the built in toggle and adds the appropriate styling.
- Adds `contentId` property to both components to populate `aria-controls` label. There might be a better name for this property?
- `isExpanded` must be passed in to both components (there is no uncontrolled variation for detached section).

Also updated tests + added to integration/cypress.

2021-04-09 15:05 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5643.surge.sh

2021-04-09 20:01 UTC, nicolethoen submitted a review, later dismissed
Looks great!

2021-04-13 15:22 UTC, jessiehuff submitted a review, later dismissed
So theoretically the `aria-controls` attribute should associate the toggle with the content for the screen reader so that when the button is pressed the user should be aware of the content. However, I had a hard time getting this to work in testing. I looked up support for the attribute and since it's supposed to be supported strongest in JAWS, I tested in JAWS 2019 with Chrome and Firefox and couldn't seem to see the effect. So it might be worth looking into in the future if there's anything else we can do, but theoretically we're associating everything correctly. 


I also attempted using `aria-labelledby` like we do with Tab, but that overrides the button text and makes much less sense. We could also add an `aria-label` (like `aria-label="Show more above"`) that would override the button text to make it clearer with the direction, but it's possible users will understand this already in context. I think this one might just depend on the use case and context. In our code editor, for example, it might already make sense that when you're selecting the show more button, the text should appear above in the code editor. This one feels difficult/subjective to say without talking to actual users. So I think we can move forward with this for now until we have more information.

2021-04-13 15:24 UTC, kmcfaul commented
Thanks for looking into this! @jessiehuff

2021-04-14 23:45 UTC, mcarrano reviewed
This looks good to me, although I'm not really sure I would understand what this was for without further documentation. @kmcfaul @mcoker @tlabaj do you think the term "Detached" will be meaningful to developers on it's own?

2021-04-15 14:07 UTC, tlabaj commented
@mcarrano this is in support of the expandable content of the Code block component.

2021-04-15 14:09 UTC, tlabaj approved these changes
looks great Katie!

2021-04-15 14:22 UTC, mcarrano commented
> @mcarrano this is in support of the expandable content of the Code block component.

I understand that. Just not sure how I would know that by looking at the example. Are there any other use cases where this might be useful?

2021-04-15 14:52 UTC, tlabaj commented
@mcarrano got it.  Detached makes sense to me from development perspective.  I would be interested in other opinions as well.  
Do you think that we need to had more verbiage so designers would also know the intention?

2021-04-15 15:49 UTC, kmcfaul commented
Detached makes sense to me, because the `ExpandableToggle` is not attached to the `ExpandableSection` and floats separately in the DOM. 

`Separated` would also make sense to me if we're looking for other terms. But maybe we can expand the `isDetached` prop description if it's unclear?

2021-04-15 16:15 UTC, mcarrano submitted a review, later dismissed
@kmcfaul @tlabaj if both of you think "Detached" makes sense then I am ok to stick with it.

2021-04-15 18:22 UTC, mcoker requested changes
This looks great! Just one comment about the toggle arrow direction. The toggle arrow shouldn't change direction by default - should only change if the user has specified they want to point the toggle arrow up because the expanded content is above the toggle.

2021-04-15 18:22 UTC, mcoker commented on packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx
> +      <span className={css(styles.expandableSectionToggleIcon, isExpanded && styles.modifiers.expandTop)}>
`styles.modifiers.expandTop` should probably be added via a prop that the user sets to indicate that the expanded content is above the toggle. By default, it's fair to assume the content is below the toggle (just like in the default use of the component), so the toggle arrow should point down when expanded.

2021-04-15 20:07 UTC, tlabaj approved these changes

2021-04-15 21:01 UTC, mcoker approved these changes
Looks great!

2021-04-15 22:13 UTC, nicolethoen approved these changes

2021-04-15 22:14 UTC, merged

2021-04-15 23:36 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.10.41
 - @patternfly/react-code-editor@4.2.31
 - @patternfly/react-console@4.4.0
 - @patternfly/react-core@4.110.0
 - @patternfly/react-docs@5.17.18
 - @patternfly/react-inline-edit-extension@4.6.78
 - demo-app-ts@4.89.0
 - @patternfly/react-integration@4.90.0
 - @patternfly/react-table@4.25.4
 - @patternfly/react-topology@4.8.27
 - @patternfly/react-virtualized-extension@4.7.14

Thanks for your contribution! :tada: