Release notes 2020 5
patternfly/patternfly-react pull request #5696
Opened 2021-04-20 19:28 UTC by tlabaj

**What**: Closes #5695 

**Additional issues**:

2021-04-20 19:34 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5696.surge.sh

2021-04-21 13:12 UTC, redallen requested changes
Looking good!

2021-04-21 13:12 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +Removed unused dependency ([#5645](https://github.com/patternfly/patternfly-react/pull/5645))
Add `- `

2021-04-21 13:36 UTC, redallen approved these changes

2021-04-21 19:59 UTC, nicolethoen commented
The versions need to get pumped one after one fix was merged: 
"@patternfly/patternfly": "4.102.1",
"@patternfly/react-catalog-view-extension": "4.11.6",
"@patternfly/react-charts": "6.14.16",
"@patternfly/react-code-editor": "4.2.40",
"@patternfly/react-core": "4.115.1",
"@patternfly/react-icons": "4.10.1",
"@patternfly/react-inline-edit-extension": "4.6.87",
"@patternfly/react-styles": "4.10.1",
"@patternfly/react-table": "4.26.6",
"@patternfly/react-tokens": "4.11.2",
"@patternfly/react-topology": "4.8.36",
"@patternfly/react-virtualized-extension": "4.7.23"

2021-04-22 14:14 UTC, redallen approved these changes

2021-04-22 15:12 UTC, redallen approved these changes

2021-04-22 15:12 UTC, merged

2021-04-22 15:33 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.18.7

Thanks for your contribution! :tada: