fix(tooltip): change default entry and exit delay
patternfly/patternfly-react pull request #5746
Opened 2021-05-05 15:28 UTC by redallen

**What**: Closes #5745

**Additional issues**:

2021-05-05 15:36 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5746.surge.sh

2021-05-05 16:13 UTC, KKoukiou commented
@redallen I tried it interactively now, I am not really happy with this change. I feel that if I was a user, hovering over a button, I would not leave my mouse there for more than a second to see that.

In addition, In cockpit I can't think of any scenario where this change makes sense, so we would need to change the properties to the previous state. 

So, since the properties are exposed, the reporter of the issue can adjust them for their scenario. And I honestly don't see the severeness of the reported issue, if the user scrolls with the mouse, and tooltips get activated, they can move the mouse slightly to the side.

2021-05-05 16:42 UTC, redallen commented
The way tooltips work in most design systems is that there is some delay. This solves bugs when scrolling through tooltips like this:
![image](https://user-images.githubusercontent.com/47335686/117177657-455c1500-ad9f-11eb-9147-c62ddf5b0eb4.png)

I'm thinking about adding a check to see if there is a single Button/Icon element and setting it to 0 in that case.

2021-05-05 17:13 UTC, redallen commented
@KKoukiou I've added the check. Are there cases other than buttons or icons where you'd expect no delay?

2021-05-05 17:18 UTC, KKoukiou reviewed
I will think about thoroughly tomorrow if there is no need for this to be merged today.

2021-05-05 17:18 UTC, KKoukiou commented on packages/react-core/src/components/Tooltip/Tooltip.tsx
> +    if (['button', Button as any, 'svg', 'g'].includes(children.type)) {
Checkbox, Radio we also use tooltips to 'explain' why elements are disabled. 

So when we disable a checkbox, we always wrap it with a tooltip and say 'Please blabla to enable this feature'

2021-05-07 17:22 UTC, kmcfaul reviewed
Would this be considering breaking as the default values are changing?

2021-05-13 13:29 UTC, tlabaj requested changes
@redallen I agree with Katie.  I believe this is a breaking change.  I would be ok changing the defaults for the beta components only.

2021-05-13 13:35 UTC, redallen commented
When would this lead to unexpected behavior @tlabaj or @kmcfaul ? I consider it a bug that PatternFly tooltips show up instantly when in most operating systems and JS frameworks they have some delay. This leads to weird scenarios where pages can show more than one tooltip.

If you can think of cases where you expect a no-delay tooltip I can add them to the `isButtonOrIcon` check to leave them untouched.

2021-05-25 18:30 UTC, mcarrano commented
After discussing further with @redallen @tlabaj and @kmcfaul we have decided to set the default delay before showing a tooltip on hover to be 500ms. As was stated above, this is expected behavior for tooltips and is consistent with what is seen for most web applications and operating systems. The initial delay of 1 second (1000ms) was probably too long so at half a second it's enough time to sense that the user has stopped mouse movement over an element while preventing tootips from firing as the user is just moving the mouse over the screen. While I recognize that this is technically breaking I view the current behavior as an oversight vs intended.

2021-05-26 13:29 UTC, tlabaj approved these changes

2021-05-26 18:19 UTC, kmcfaul approved these changes

2021-05-26 20:37 UTC, nicolethoen approved these changes

2021-05-26 22:25 UTC, mcarrano approved these changes
Looks great. Thanks @redallen !

2021-05-27 13:21 UTC, merged