feat(LogViewer): refactor toolbar functionality
patternfly/patternfly-react pull request #5769
Opened 2021-05-11 19:11 UTC by kmcfaul

**What**: Continues work on LogViewer (#5341)

In this PR:
- Removes `LogViewerCustomControl`, `LogViewerToolbar`
- Adds `LogViewerSearch` containing search input
- Adds `toolbar` property to `LogViewer` (replacing `hasToolbar` and `customControls`)
- Adds `LogViewerToolbarContext` to wire up `LogViewerSearch` wherever it is passed within a toolbar

Notes:
- The `toolbar` property could possibly be named `header` instead, as this prop represents all content passed under the `pf-c-log-viewer__header`. Any preferences?
- `LogViewerSearch` will only function properly when passed into `LogViewer` via the `toolbar` prop due to the position of the context used to pass relevant data.

Todos (either here or in a follow-up):
- Allow persisted `searchedInput`
- More complex toolbar example

2021-05-12 13:47 UTC, nicolethoen commented on packages/react-log-viewer/src/LogViewer/examples/LogViewer.md
> +              <ToolbarGroup>
I dont think you need to wrap the SearchInput in a ToolbarGroup

2021-05-12 13:47 UTC, nicolethoen commented on packages/react-log-viewer/src/LogViewer/examples/LogViewer.md
> +              <ToolbarGroup>
same here

2021-05-12 14:31 UTC, kmcfaul commented
Extends SearchInputProps so user can hook into the component a bit better. Props are spread before several functions to allow users to hook into change/click events without overriding internal wireup.

2021-05-12 14:54 UTC, tlabaj approved these changes

2021-05-12 16:37 UTC, nicolethoen approved these changes

2021-05-12 16:54 UTC, nicolethoen reviewed
the searches actually are not working atm. The values do not update

2021-05-12 16:55 UTC, nicolethoen requested changes
the searches are not working atm in the examples

2021-05-12 17:21 UTC, nicolethoen commented
Looks good - only question is why does it automatically put focus into the second example's search?

2021-05-12 17:27 UTC, kmcfaul commented
Do you mean the automatic scroll to the first match? It did that before, but I think we can adjust it if that isn't the desired behavior.

2021-05-12 17:45 UTC, nicolethoen approved these changes

2021-05-13 12:57 UTC, tlabaj approved these changes

2021-05-13 13:42 UTC, merged