feat(Menu): filter tree demo
patternfly/patternfly-react pull request #5824
Opened 2021-05-24 16:57 UTC by kmcfaul

**What**: Closes #5655

First pass on filter tree demo. 
PR also:
- Allows TreeView leaf nodes to have badges if `customBadgeContent` is defined
- Fixes a console error for TreeView if a flat tree (no folders/children) is rendered
- Updates to cleaner logic check for composable menu toggling closed via click/keyboard
<br />

@mcoker I think this will need a css update as TreeView currently doesn't expect leaf nodes on the top level (so there isn't any spacing to keep the checkboxes inline). If we can add a modifier/flag for top level leaf nodes, I can flag them individually (as the data is known prior to rendering).

@jessiehuff Keyboard navigation in this demo is currently wonky due to the multiple TreeViews. The keyboard handling works the same per single checkbox TreeView, but that already uses Tab to go between the toggle/checkbox elements which isn't ideal in a Menu context. You currently also have to `Tab` to get to a following TreeView block. I'm still playing around with it, but I think the demo may have to implement its own handler for everything. Time depending, this might be a follow up issue.

2021-05-24 17:03 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5824.surge.sh

2021-05-25 20:00 UTC, mcarrano reviewed
@kmcfaul this is looking good with the exception of the issues you mentioned. @mcoker is it a quickly fix for the menu alignment problem or do we need to open a new issue for that?

2021-05-26 00:04 UTC, mcoker commented
@kmcfaul @mcarrano I've put up a core PR with the change here - https://github.com/patternfly/patternfly/pull/4104

2021-05-27 20:11 UTC, tlabaj requested changes

2021-05-27 20:11 UTC, tlabaj commented on packages/react-core/src/demos/ComposableMenu.md
> +class BasicComposableMenu extends React.Component {
the name of the class should be changed

2021-05-27 20:54 UTC, kmcfaul commented
Updated the demo name and rebased with master, which contains the version bump to fix the styling.

2021-06-01 17:37 UTC, mcoker approved these changes
LGTM. I'd like to review the markup and see if we need some sort of container for components that can go in the menu. Opened a core issue here for that - https://github.com/patternfly/patternfly/issues/4116

2021-06-01 20:14 UTC, mcarrano approved these changes
This looks great. Thanks @kmcfaul .

2021-06-02 17:29 UTC, tlabaj approved these changes

2021-06-02 17:42 UTC, merged

2021-06-02 18:04 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.11.39
 - @patternfly/react-code-editor@4.2.73
 - @patternfly/react-console@4.8.15
 - @patternfly/react-core@4.127.0
 - @patternfly/react-docs@5.18.48
 - @patternfly/react-inline-edit-extension@4.6.122
 - demo-app-ts@4.103.3
 - @patternfly/react-log-viewer@4.1.16
 - @patternfly/react-table@4.27.21
 - @patternfly/react-topology@4.8.69
 - @patternfly/react-virtualized-extension@4.8.20

Thanks for your contribution! :tada:

2021-06-02 18:22 UTC, dlabrecq reviewed
LGTM