fix(DatePicker, TimePicker): Pass additional props to input
patternfly/patternfly-react pull request #5848
Opened 2021-05-27 14:35 UTC by xprazak2

**What**: Closes #5846

2021-05-27 16:46 UTC, redallen requested changes
Typescript is picky about its types.

2021-05-27 16:46 UTC, redallen commented on packages/react-core/src/components/DatePicker/DatePicker.tsx
> +  inputProps?: object;
Try `TextInputProps`. You'll need to add `import { TextInputProps } from '../TextInput';` to the top of the file.

2021-05-27 16:46 UTC, redallen commented on packages/react-core/src/components/TimePicker/TimePicker.tsx
> +  inputProps?: object;
Try `TextInputProps`. You'll need to add `import { TextInputProps } from '../TextInput';` to the top of the file.

2021-06-02 11:14 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5848.surge.sh

2021-06-07 14:23 UTC, xprazak2 commented
Updated, tests are passing now.

2021-06-08 13:06 UTC, redallen requested changes
Can you please use the more accurate type `inputProps?: TextInputProps`? This will allow VSCode and other editors suggest the correct props.

2021-06-09 07:51 UTC, xprazak2 commented
`inputProps` now use `TextInputProps` as a type.

2021-06-09 12:51 UTC, redallen approved these changes
Thank you!

2021-06-16 07:33 UTC, tbrisker commented
@redallen hi, is anything else needed to get this merged? We need this fix for the Foreman project's usage of these components.

2021-06-16 13:03 UTC, redallen commented
Just need another reviewer @tbrisker .

2021-06-16 17:49 UTC, kmcfaul approved these changes
lgtm!

2021-06-16 17:51 UTC, merged

2021-06-16 18:09 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.11.46
 - @patternfly/react-code-editor@4.2.81
 - @patternfly/react-console@4.8.22
 - @patternfly/react-core@4.128.6
 - @patternfly/react-docs@5.18.60
 - @patternfly/react-inline-edit-extension@4.6.130
 - demo-app-ts@4.104.6
 - @patternfly/react-log-viewer@4.1.23
 - @patternfly/react-table@4.27.29
 - @patternfly/react-topology@4.8.77
 - @patternfly/react-virtualized-extension@4.8.27

Thanks for your contribution! :tada: