chore: Remove beta component console warnings from promoted components
patternfly/patternfly-react pull request #5990
Opened 2021-07-06 19:43 UTC by nicolethoen

Closes #5989

2021-07-06 19:48 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5990.surge.sh

2021-07-06 19:48 UTC, redallen approved these changes

2021-07-06 19:48 UTC, redallen requested changes
Can you also remove `static hasWarnBeta = false;`?

2021-07-08 17:38 UTC, redallen approved these changes

2021-07-08 18:33 UTC, tlabaj approved these changes

2021-07-08 18:33 UTC, merged