feat(charts): Add Prometheus chart demo
patternfly/patternfly-react pull request #5997
Opened 2021-07-08 14:01 UTC by DaoDaoNoCode

**What**: Closes #5996

2021-07-08 14:18 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-5997.surge.sh

2021-07-09 19:59 UTC, wojta commented
@DaoDaoNoCode Is it meant to be with that big question mark? 
![image](https://user-images.githubusercontent.com/2912228/125130164-d41f4200-e100-11eb-8c26-22017baa3f2c.png)
However the proper demo is available in a new window by clicking the question mark.

2021-07-12 21:42 UTC, dlabrecq requested changes
FYI, codesandbox.io couldn't load the mock data.

2021-07-12 21:42 UTC, dlabrecq commented on packages/react-core/src/demos/Chart/PrometheusChart.md
> +                  };
You shouldn't need to define the color style, unless overriding colors. The chart will iterate over the color scale defined by the multiUnordered theme.

2021-07-12 21:42 UTC, dlabrecq commented on packages/react-core/src/demos/Chart/PrometheusChart.md
> +  const colors = theme.line.colorScale;
Unless you are changing the theme, you don't need this. You can simply define the chart's color scale using:

`themeColor={ChartThemeColor.multiUnordered}`

2021-07-12 21:42 UTC, dlabrecq commented on packages/react-core/src/demos/Chart/PrometheusChart.md
> +                    <ChartComponent data={values} groupComponent={<g />} key={i} name={metric.cpu} style={style} />
Is there a reason to override the `groupComponent`?

2021-07-12 21:42 UTC, dlabrecq commented on packages/react-core/src/demos/Chart/PrometheusChart.md
> +  NavList,
These components don't appear to be in use

2021-07-12 21:42 UTC, dlabrecq commented on packages/react-core/src/demos/Chart/PrometheusChart.md
> +  );
Not sure if we need to include the PatternFly avatar in the page header? The other demos don't seem to use it?

2021-07-13 18:11 UTC, nicolethoen commented
@DaoDaoNoCode To generate the snapshots so that the big question mark goes away:

yarn build:docs && yarn serve:docs
(new terminal) yarn workspace @patternfly/react-docs screenshots (you can add "screenshots": "yarn workspace @patternfly/react-docs screenshots" to the root package.json to just have to run yarn screenshots in the future)

Let me know if you have questions

2021-07-13 19:08 UTC, DaoDaoNoCode commented
@wojta @dlabrecq After checking with Jan, this demo might not be the solution we are looking for. We actually want a UXD extension like the QuickStart, to easily use the Prometheus chart across different managed applications and keep the styles aligned. More details to be discussed.
And thanks for the hint @nicolethoen ! BTW, Would you like to give us a brief introduction about the UXD extension as you mentioned this morning in the team meeting after we decide the next step?
I will close this PR for now, thanks 🙂

2021-07-14 18:55 UTC, closed without merging