SearchInput: allow hasWordAttrLabel to be React.ReactNode as well
patternfly/patternfly-react pull request #6037
Opened 2021-07-15 16:00 UTC by KKoukiou

In cockpit we want to use this component variant, but the 'Has words' field needs explanation. For this reason we want to use a helpicon popover as seen in the screenshot.

![search-box-label](https://user-images.githubusercontent.com/14921356/125819467-3a3a4691-48f9-45a3-938a-8d782e2f6f1f.jpg)

2021-07-15 16:29 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6037.surge.sh

2021-07-15 20:22 UTC, nicolethoen submitted a review, later dismissed

2021-07-19 13:17 UTC, dlabrecq submitted a review, later dismissed

2021-07-19 13:52 UTC, tlabaj requested changes

2021-07-19 13:52 UTC, tlabaj commented on packages/react-core/src/components/SearchInput/SearchInput.tsx
> +  hasWordsAttrLabel?: string | React.ReactNode;
the type `React.ReactNode` includes `string` so you can remove that here

2021-07-19 15:26 UTC, tlabaj submitted a review, later dismissed

2021-07-20 19:04 UTC, redallen submitted a review, later dismissed
Looks good, just need to fix conflicts.

2021-07-21 15:32 UTC, nicolethoen approved these changes

2021-07-21 16:30 UTC, redallen approved these changes

2021-07-21 16:30 UTC, merged

2021-07-21 16:59 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.12.23
 - @patternfly/react-code-editor@4.3.9
 - @patternfly/react-console@4.10.24
 - @patternfly/react-core@4.140.2
 - @patternfly/react-docs@5.19.28
 - @patternfly/react-inline-edit-extension@4.7.31
 - demo-app-ts@4.111.2
 - @patternfly/react-log-viewer@4.2.23
 - @patternfly/react-table@4.29.24
 - @patternfly/react-topology@4.9.29
 - @patternfly/react-virtualized-extension@4.8.61

Thanks for your contribution! :tada: