feat(LogViewer): Add dark theme
patternfly/patternfly-react pull request #6044
Opened 2021-07-16 13:18 UTC by nicolethoen

Closes #5930 

The first log viewer example now has a checkbox for toggling dark theme.

2021-07-16 13:21 UTC, redallen submitted a review, later dismissed

2021-07-16 13:29 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6044.surge.sh

2021-07-16 16:01 UTC, mcoker approved these changes
LGTM!

2021-07-17 10:55 UTC, mfocko commented on packages/react-log-viewer/src/LogViewer/examples/LogViewer.md
> +      <LogViewer hasLineNumbers={false} height={300} data={data.data} isDarkTheme={isDarkTheme} />;
```suggestion
      <LogViewer hasLineNumbers={false} height={300} data={data.data} isDarkTheme={isDarkTheme} />
```
It has a different meaning to the previous usage? Cause I can't see it in the main branch right now, but preview for this PR shows the semicolon.

2021-07-19 13:06 UTC, nicolethoen commented
@mfocko Nice eye! It was left over and I totally missed it. :)

2021-07-19 15:06 UTC, redallen submitted a review, later dismissed

2021-07-28 14:10 UTC, kmcfaul approved these changes

2021-07-28 14:17 UTC, dlabrecq submitted a review, later dismissed

2021-07-28 14:27 UTC, dlabrecq commented
FYI, the sandbox has a syntax error. It doesn't look like it can handle empty <> tags and needs a React.Fragment.

<img width="751" alt="Screen Shot 2021-07-28 at 10 25 39 AM" src="https://user-images.githubusercontent.com/17481322/127340002-d24666b8-0bcf-42d0-a33f-1702405d7a95.png">

2021-07-28 14:32 UTC, nicolethoen commented
> FYI, the sandbox has a syntax error. It doesn't look like it can't handle empty <> tags and needs a React.Fragment.

Good catch!

2021-07-28 14:51 UTC, tlabaj requested changes

2021-07-28 14:51 UTC, tlabaj commented on packages/react-log-viewer/src/LogViewer/LogViewer.tsx
> +  isDarkTheme?: boolean;
I wonder if we should follow other components like pageSidebar and Nav 
` theme?: 'dark' | 'light';`

2021-07-29 14:41 UTC, nicolethoen commented
I opened an issue to fix the codesandbox examples. The code sandbox needs to be given the javascript files with the large data. Right now it's not included. But i think that will require some investigation.
https://github.com/patternfly/patternfly-react/issues/6086

2021-07-29 14:57 UTC, redallen approved these changes
Still LGTM!

2021-07-30 11:18 UTC, tlabaj approved these changes

2021-07-30 15:15 UTC, mcarrano approved these changes
Looks great (and dark)!

2021-07-30 16:53 UTC, dlabrecq approved these changes

2021-07-30 19:29 UTC, merged