Release notes 2021.10
patternfly/patternfly-react pull request #6117
Opened 2021-08-04 12:00 UTC by tlabaj

**What**: Closes #6116

2021-08-04 12:09 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6117.surge.sh

2021-08-04 15:22 UTC, nicolethoen commented
Plus regenerate screenshots :)

2021-08-04 19:24 UTC, nicolethoen approved these changes

2021-08-04 19:26 UTC, redallen requested changes

2021-08-04 19:33 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +- **Navigation:** Updated incorrect prop descriptions ([#5980](https://github.com/patternfly/patternfly-react/pull/5980))
Move description to new indented line with bullet point

```suggestion
- **Navigation:**
  - Updated incorrect prop descriptions ([#5980](https://github.com/patternfly/patternfly-react/pull/5980))
```

2021-08-04 19:34 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  -Fixed to respect props in useCallback ([#5969](https://github.com/patternfly/patternfly-react/pull/5969))
Missing a space after the hyphen

```suggestion
  - Fixed to respect props in useCallback ([#5969](https://github.com/patternfly/patternfly-react/pull/5969))
```

2021-08-04 19:40 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +- **Alert Group:**
Sentence case

```suggestion
- **Alert group:**
```

2021-08-04 19:41 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Made dynamic alerts more accessible ([#5946](https://github.com/patternfly/patternflg-react/pull/5946))
Link is broken due to typo

```suggestion
  - Made dynamic alerts more accessible ([#5946](https://github.com/patternfly/patternfly-react/pull/5946))
```

2021-08-04 19:45 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Added form group label info ([#6053](https://github.com/patternfly/patternfly-react/pull/6053))
Do we also want to call out the password strength demo added here?
`feat(Form): add form group label info & docs(Form): add password strength demo #6053`

2021-08-04 19:49 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +- **Search input:**
1. This can be combined with the `Search input` note above `Select`.
2. Past tense - "Updated to allow hasWordAttrLabel..."

2021-08-04 19:50 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +-  Fixed Custom className override ([#6094](https://github.com/patternfly/patternfly-react/pull/6094))
```suggestion
-  Fixed custom className override ([#6094](https://github.com/patternfly/patternfly-react/pull/6094))
```

2021-08-04 19:51 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Fixed OnInputChange always being set to valid ([#5982](https://github.com/patternfly/patternfly-react/pull/5982))
```suggestion
  - Fixed onInputChange always being set to valid ([#5982](https://github.com/patternfly/patternfly-react/pull/5982))
```

2021-08-04 19:54 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Added Keyboard handling helper ([#5972](https://github.com/patternfly/patternfly-react/pull/5972))
```suggestion
  - Added keyboard handling helper ([#5972](https://github.com/patternfly/patternfly-react/pull/5972))
```

2021-08-04 19:55 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Added form group label info ([#6053](https://github.com/patternfly/patternfly-react/pull/6053))
Nevermind - see this listed under the "Demos" section.

2021-08-04 19:55 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Fixed broken link in tokens readme ([#5938](https://github.com/patternfly/patternfly-react/pull/5938)
Missing closing paren

```suggestion
  - Fixed broken link in tokens readme ([#5938](https://github.com/patternfly/patternfly-react/pull/5938))
```

2021-08-05 12:07 UTC, nicolethoen approved these changes

2021-08-05 12:14 UTC, redallen approved these changes

2021-08-05 13:24 UTC, evwilkin approved these changes
LGTM

2021-08-05 13:24 UTC, merged

2021-08-05 13:45 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.20.3

Thanks for your contribution! :tada: