feat(Search input): Added support for submit button
patternfly/patternfly-react pull request #6178
Opened 2021-08-17 17:05 UTC by tlabaj

**What**: Closes #5963

2021-08-17 17:13 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6178.surge.sh

2021-08-17 21:02 UTC, mcarrano reviewed
Looks good @tlabaj . Is this coded so that either pressing enter or clicking the new submit button will trigger the search?

2021-08-17 21:32 UTC, nicolethoen commented
the a11y tests are failing because `aria-expanded="true"` is being applied to the nodes that don't have children and are not actually expandable. That may be a bug related to the `defaultAllExpanded` prop. It should only use `aria-expanded` if it has children to expand/collapse.

2021-08-18 19:34 UTC, mcoker requested changes
Looks great! Just one change to match the core example - https://pf4.patternfly.org/components/search-input/#with-submit-button

2021-08-18 19:34 UTC, mcoker commented on packages/react-core/src/components/SearchInput/SearchInput.tsx
> +            <Button
This should be a child of the `<InputGroup>`, not `<div className={css(styles.searchInputBar)}>`

2021-08-18 20:48 UTC, nicolethoen submitted a review, later dismissed
Once the tests pass and the structure is updated, looks good to me!

2021-08-18 21:24 UTC, tlabaj commented
> Looks good @tlabaj . Is this coded so that either pressing enter or clicking the new submit button will trigger the search?
@mcarrano Katerina added that in PR #6145

2021-08-19 16:12 UTC, kmcfaul approved these changes

2021-08-19 20:00 UTC, mcarrano approved these changes
Looks great. Thanks @tlabaj !

2021-08-19 20:24 UTC, mcoker approved these changes
LGTM!!

2021-08-19 20:39 UTC, evwilkin approved these changes
LGTM

2021-08-19 20:39 UTC, merged

2021-08-19 21:43 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.12.49
 - @patternfly/react-charts@6.15.17
 - @patternfly/react-code-editor@4.3.35
 - @patternfly/react-console@4.11.17
 - @patternfly/react-core@4.151.0
 - @patternfly/react-docs@5.21.6
 - @patternfly/react-icons@4.11.11
 - @patternfly/react-inline-edit-extension@4.7.57
 - demo-app-ts@4.118.0
 - @patternfly/react-integration@4.119.0
 - @patternfly/react-log-viewer@4.4.14
 - @patternfly/react-styles@4.11.11
 - @patternfly/react-table@4.29.50
 - @patternfly/react-tokens@4.12.12
 - @patternfly/react-topology@4.9.55
 - @patternfly/react-virtualized-extension@4.9.24

Thanks for your contribution! :tada:

2021-08-20 14:14 UTC, dlabrecq reviewed
LGTM