feat(Table): Add hoverable and selectable rows
patternfly/patternfly-react pull request #6233
Opened 2021-08-26 15:24 UTC by nicolethoen

**What**: Closes #5444 

Changes:

- I removed the rowClickHandler piece from a different TableComposable example
- I added a new `Composable: Row click handler, hoverable & selected rows` example to TableComposable
- I updated the Legacy Table's `Row click handler and header cell tooltips/popovers` example to include hoverable/selectable features.
- I added keyboard handling to the `onRowClick` prop so that the event can be triggered using keyboard and not just mouse click

2021-08-27 14:52 UTC, mcoker submitted a review, later dismissed
LGTM!

2021-08-27 15:12 UTC, kmcfaul submitted a review, later dismissed

2021-08-31 19:27 UTC, jessiehuff reviewed
Looks pretty good to me! I think the only question I have is how to notify screen reader users that the item is selectable or selected. I've often questioned this in other components as well such as with the [Selectable Datalist](https://www.patternfly.org/v4/components/data-list#selectable-rows). With that one though, we had it in the name of the example so it at least had some indication that it was selectable (perhaps not an ideal solution though). I'm thinking there might be a better way to go about it but might have to research to see if there's an established practice. Open to suggestions for it though. :)

2021-09-10 13:41 UTC, nicolethoen commented
I opened issue: https://github.com/patternfly/patternfly-react/issues/6295 to track communicating hoverable/selectable rows for screen readers.

2021-09-10 14:52 UTC, CooperRedhat requested changes
Can you change the title of the legacy example to indicate it includes hoverable/selectable?

Otherwise LGTM with accessibility issue opened.

2021-09-10 15:38 UTC, kmcfaul approved these changes
lgtm with the follow up opened for the remaining accessibility changes

2021-09-10 18:14 UTC, mturley commented
In the description for the existing checkbox-selectable example we use the term "selectable" with the assumption that we mean checkboxes:

> To make a row selectable, the table needs a selection column.

Should we maybe be a little bit more clear about the distinction? Maybe we can add a note to the new example saying something like "There are two ways to make a row selectable: by applying a style on the whole row with `isRowSelected` or by using checkboxes (see example below)" and then we could change "To make a row selectable" to "To make rows selectable with checkboxes".

2021-09-10 18:29 UTC, mcarrano commented
@mturley The primary use case for this was in something like a primary-detail view where you would select a row that represents some object and then inspect it's details in a drawer or similar container. This should not be confused with checkbox select to select multiple rows for taking action. It is a bit confusing the way this is presented now. Not sure what the best way is to clarify.

2021-09-13 15:45 UTC, mcarrano commented
@nicolethoen Can we do this to try and clarify a bit?

1. Move this example to fall AFTER the "Composable: selectable with checkbox" and Composable: selectable with radio input" examples since those represent the more typical support for selectable rows.

2. Add descriptive text to this example that reads, "Use when a table is used to present a list of objects in a Primary-detail view." Or something like that.

2021-09-13 19:04 UTC, kmcfaul approved these changes

2021-09-13 19:40 UTC, CooperRedhat approved these changes

2021-09-14 14:23 UTC, mcarrano approved these changes
Looks great! Thanks for making those changes @nicolethoen .

2021-09-14 14:48 UTC, tlabaj approved these changes

2021-09-14 14:48 UTC, merged