docs: refactor demos to use Masthead
patternfly/patternfly-react pull request #6274
Opened 2021-09-07 16:11 UTC by kmcfaul

**What**: Closes #6174

Refactors:
- [ ] DashboardHeader
- [ ] Page
- [ ] Nav
- [ ] NotificationDrawer
- [ ] Wizard

`PageHeader` is integrated with a `Page` context to provide the managed nav toggle trigger / aria-expanded state. To maintain this functionality I added a `PageToggleButton` component that extends our `Button` component and contains the context consumer.

2021-09-07 16:16 UTC, kmcfaul commented
@tlabaj @nicolethoen 

For `Page` demos do we still want to use `PageHeader`? I'm unsure whether to refactor those. 

For `Nav` demos, I'm unsure where the actual nav component that is embedded in `PageHeader` is supposed to go within `Masthead` or the masthead's `Toolbar`. Placing the nav in the toolbar causes the bottom stacked masthead section to overflow on a small screen.

2021-09-07 16:17 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6274.surge.sh

2021-09-08 19:57 UTC, kmcfaul commented
Opened #6281 for Page specific refactoring. Taking another look at `Nav`.

2021-09-09 13:23 UTC, nicolethoen approved these changes
LGTM

2021-09-09 17:26 UTC, mattnolting requested changes
Looking good, @kmcfaul! In each of the examples, `avatar` should be inside the dropdown.

2021-09-09 17:26 UTC, mattnolting commented on packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
> +          <ToolbarGroup alignment={{ default: 'alignRight' }}>
need to add spaceItems={{ default: 'spacerNone' }}

2021-09-09 17:26 UTC, mattnolting commented on packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
> +            <Avatar src={imgAvatar} alt="Avatar image" />
Avatar should be part of the dropdown `https://www.patternfly.org/v4/components/dropdown#dropdown-with-image-and-text`

2021-09-09 20:15 UTC, mattnolting submitted a review, later dismissed
LPTM!

2021-09-10 15:26 UTC, nicolethoen approved these changes

2021-09-10 15:31 UTC, kmcfaul commented
Nav refactoring will need additional work - masthead currently doesn't quite support containing a nav. Putting the nav inside the toolbar prevents the scrolling/shrinking from behaving properly, and putting it outside the toolbar but also in the content yields most of the space to the toolbar instead of the nav, making it look very squished (but scroll buttons do work). I tried to get the alignment and spacing working with `Flex` but couldn't get all the way there. It looks like `PageHeader` used a grid layout with a separate container div, but MastheadContent is already a flex so I'm unsure if we can/want to nest those.

2021-09-10 16:17 UTC, mcarrano commented
@kmcfaul As we discussed the other day, I'm fine with keeping the Horizontal Nav demo (https://www.patternfly.org/v4/components/navigation#horizontal-only-in-pageheader) as is for now unless @mattnolting you can think of a solution to this problem. AFAIK this pattern is rarely used, if at all. @redallen are you able to tell if anyone is using the Horizontal Nav variant? It might be a good candidate to deprecate.

2021-09-10 16:22 UTC, mcarrano approved these changes
Looks great!

2021-09-10 18:58 UTC, tlabaj requested changes
Since we have the new `PageToggleButton` component,  I would had that to the demo app.  I am ok with doing that in a follow up PR.  
I however would add the component to the `Page.md` file propComponents so that it is exposed in the docs.

2021-09-10 19:11 UTC, kmcfaul commented
@tlabaj Added `PageToggleButton` to the props docs and updated #6281 to include adding a Page-Masthead-PageToggleButton demo to integration

2021-09-10 20:51 UTC, tlabaj approved these changes

2021-09-10 21:28 UTC, mturley approved these changes
LGTM

2021-09-13 13:20 UTC, nicolethoen approved these changes

2021-09-13 13:20 UTC, merged

2021-09-13 13:44 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.12.64
 - @patternfly/react-code-editor@4.3.51
 - @patternfly/react-console@4.11.32
 - @patternfly/react-core@4.155.1
 - @patternfly/react-docs@5.21.30
 - @patternfly/react-inline-edit-extension@4.7.74
 - demo-app-ts@4.120.1
 - @patternfly/react-log-viewer@4.6.4
 - @patternfly/react-table@4.29.67
 - @patternfly/react-topology@4.9.70
 - @patternfly/react-virtualized-extension@4.9.39

Thanks for your contribution! :tada: