(Menu): Added context selector demo using Menu
patternfly/patternfly-react pull request #6283
Opened 2021-09-08 22:38 UTC by tlabaj

**What**: Closes #6019

2021-09-08 22:44 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6283.surge.sh

2021-09-08 23:02 UTC, mcoker requested changes
LGTM, only difference I see is that the context menu has a max height of 200px on the menu list.

2021-09-08 23:02 UTC, mcoker commented on packages/react-core/src/demos/ComposableMenu.md
> +      <MenuContent>
```suggestion
      <MenuContent  maxMenuHeight="200px">
```

2021-09-09 12:44 UTC, nicolethoen commented
LGTM - Just wondering in VO how to get to the menu items? I can use the tab + arrow keys easily, but VO does not prompt me to do that and I cannot seem to find a VO controls path into the menu - @jessiehuff is it set up like you'd expect?

2021-09-09 13:21 UTC, mcarrano approved these changes
Looks good other than the issues/questions that have already been raised.

2021-09-09 14:18 UTC, kmcfaul approved these changes
lgtm other than the VO question. Keyboard navigation looks good

2021-09-09 14:48 UTC, mcoker approved these changes

2021-09-10 13:05 UTC, CooperRedhat approved these changes
LGTM

2021-09-10 13:59 UTC, jessiehuff reviewed
I tested with VO, JAWS, and NVDA, and I'm able to get into the menu items in each as I'd expect. With VO, I navigated with ctr + option + arrow keys, and I think it was ok. I'm curious what your experience was, @nicolethoen! Maybe you can screen record and send it to me to see if I can replicate?

The only thing that I saw that I would consider changing is the keyboard interaction. Based on [the keyboard interaction doc](https://docs.google.com/document/d/1m9nICFRgCXnXeHYN487BMX9MHw4DjvOln2B5p8yJa70/edit#heading=h.1lr7m0rc8a6s) that Jenn and I created awhile back, menu items should be navigated by arrow keys instead of Tab. I know that we already have an [open issue](https://github.com/patternfly/patternfly-react/issues/3205) for that though so we can do these separately if we want.

2021-09-10 17:29 UTC, jessiehuff approved these changes

2021-09-10 17:51 UTC, nicolethoen approved these changes
I tried again - I mistakenly thought I had to have the VO buttons pressed while trying to navigate the menu and was finding that the VO focus was getting trapped in the button. I'm still learning the controls. When I use the arrow keys without having the VO buttons pressed, i'm able to move the VO focus into the menu no problem.

2021-09-10 17:51 UTC, merged