Card: Added demos for log and event views
patternfly/patternfly-react pull request #6289
Opened 2021-09-09 14:39 UTC by tlabaj

**What**: Closes #6287 
Closes #6288

2021-09-09 15:04 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6289.surge.sh

2021-09-09 18:38 UTC, mcarrano reviewed
These look good @tlabaj . But in comparing with the core implementations, I see a difference in font sizes for the log view card. I also referenced the original design and it looks like your implementation is closer to that. @mattnolting can you take a look at this? Do we need to fix the core implementation? Here is the design I'm looking at for reference:

![Events card](https://user-images.githubusercontent.com/6619860/132743795-ca0fd823-d383-473f-a1f3-07c9b04e95f1.png)

2021-09-10 15:23 UTC, mcoker commented
@mcarrano to confirm, to match the design we should also update the font size in the view card in this PR, as well as add a divider between the card body/footer? It would look like this:

<img width="420" alt="Screen Shot 2021-09-10 at 10 22 23 AM" src="https://user-images.githubusercontent.com/35148959/132878000-c4dbafd8-d4ec-40dc-93f5-e7183f12f5f4.png">

2021-09-10 19:21 UTC, mcarrano commented
@tlabaj @mcoker Yes, that's correct.

2021-09-10 20:08 UTC, mcoker commented
Created a core issue to update the demos - https://github.com/patternfly/patternfly/issues/4368

2021-09-10 20:37 UTC, mcoker requested changes

2021-09-10 20:37 UTC, mcoker commented on packages/react-core/src/demos/CardDemos.md
> +              <DescriptionListTerm className=" pf-u-font-size-lg">
```suggestion
              <DescriptionListTerm>
```

2021-09-10 20:37 UTC, mcoker commented on packages/react-core/src/demos/CardDemos.md
> +              <DescriptionListTerm className=" pf-u-font-size-lg">
```suggestion
              <DescriptionListTerm>
```

2021-09-10 20:37 UTC, mcoker commented on packages/react-core/src/demos/CardDemos.md
> +              <DescriptionListTerm className=" pf-u-font-size-lg">
```suggestion
              <DescriptionListTerm>
```

2021-09-10 20:37 UTC, mcoker commented on packages/react-core/src/demos/CardDemos.md
> +              <DescriptionListTerm className=" pf-u-font-size-lg">
```suggestion
              <DescriptionListTerm>
```

2021-09-10 22:50 UTC, mcoker approved these changes
LGTM!

2021-09-13 15:08 UTC, mcarrano approved these changes
These look great!

2021-09-13 15:43 UTC, kmcfaul approved these changes
lgtm

2021-09-13 16:21 UTC, nicolethoen approved these changes

2021-09-13 16:21 UTC, merged