Chore: release notes 2021.12
patternfly/patternfly-react pull request #6324
Opened 2021-09-15 21:03 UTC by tlabaj

**What**: Closes #6323

2021-09-15 21:13 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6324.surge.sh

2021-09-15 21:22 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Added plain variant, add expandable inline ([#6236](https://github.com/patternfly/patternfly-react/pull/6236))
Change "add" to past tense "added"
```suggestion
  - Added plain variant, added expandable inline ([#6236](https://github.com/patternfly/patternfly-react/pull/6236))
```

2021-09-15 21:22 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Convert examples to typescript ([#6228](https://github.com/patternfly/patternfly-react/pull/6228))
Change "Convert" to past tense "Converted"

2021-09-15 21:23 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Make useEffect respect validators ([#6315](https://github.com/patternfly/patternfly-react/pull/6315))
Change "Make" to past tense "Made"
```suggestion
  - Made useEffect respect validators ([#6315](https://github.com/patternfly/patternfly-react/pull/6315))
```

2021-09-15 21:24 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Introduced Back to Top component and demos ([#6282](https://github.com/patternfly/patternfly-react/pull/6282))
Fix capitalization of component name - "back to top"
```suggestion
  - Introduced back to top component and demos ([#6282](https://github.com/patternfly/patternfly-react/pull/6282))
```

2021-09-15 21:29 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Added Support for disabled state tabs ([#6261](https://github.com/patternfly/patternfly-react/pull/6261))
Change "Support" to lowercase
```suggestion
  - Added support for disabled state tabs ([#6261](https://github.com/patternfly/patternfly-react/pull/6261))
```

2021-09-15 21:35 UTC, evwilkin requested changes
A handful of nits, mostly tense and capitalization tweaks

2021-09-16 13:34 UTC, evwilkin submitted a review, later dismissed
LGTM - thanks! 🔥

2021-09-16 14:49 UTC, redallen approved these changes

2021-09-16 14:50 UTC, redallen requested changes
Product testing came back negative, had to merge #6325

2021-09-16 14:50 UTC, redallen commented on packages/react-docs/RELEASE-NOTES.md
> +- [@patternfly/react-virtualized-extension@4.9.47](https://www.npmjs.com/package/@patternfly/react-virtualized-extension/v/4.9.47)
You'll have to change these in a second.

2021-09-16 19:02 UTC, evwilkin reviewed
LGTM

2021-09-16 19:02 UTC, redallen approved these changes
Thanks for updating the versions!

2021-09-16 19:02 UTC, merged

2021-09-16 20:23 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.21.40

Thanks for your contribution! :tada: