Sidebar(docs): added tabindex to scrollable examples
patternfly/patternfly-react pull request #6378
Opened 2021-09-29 20:10 UTC by tlabaj

**What**: Closes #6322

2021-09-29 20:16 UTC, patternfly-build commented
PF4 preview: https://patternfly-react-pr-6378.surge.sh

2021-09-29 20:30 UTC, jessiehuff approved these changes
LGTM! :)

2021-10-01 02:59 UTC, evwilkin commented on packages/react-core/src/components/Sidebar/examples/Sidebar.md
> +A `tabindex` should be added to the `Sidbear` when there is scrollable content in order for the  overflow content to be accessible by keyboard.
Typo: "Sidebar" spelling

```suggestion
A `tabindex` should be added to the `Sidebar` when there is scrollable content in order for the  overflow content to be accessible by keyboard.
```

2021-10-01 03:00 UTC, evwilkin commented on packages/react-core/src/components/Sidebar/examples/Sidebar.md
> +A `tabindex` should be added to the `Sidbear` when there is scrollable content in order for the  overflow content to be accessible by keyboard.
Typo: "Sidebar" spelling

```suggestion
A `tabindex` should be added to the `Sidebar` when there is scrollable content in order for the  overflow content to be accessible by keyboard.
```

2021-10-01 03:00 UTC, evwilkin commented on packages/react-core/src/components/Sidebar/examples/Sidebar.md
> +A `tabindex` should be added to the `Sidbear` when there is scrollable content in order for the  overflow content to be accessible by keyboard.
Typo: "Sidebar" spelling

```suggestion
A `tabindex` should be added to the `Sidebar` when there is scrollable content in order for the  overflow content to be accessible by keyboard.
```

2021-10-01 03:01 UTC, evwilkin requested changes
Typo - `Sidbear` should be `Sidebar` in example captions.

2021-10-01 13:29 UTC, nicolethoen approved these changes
Looks good once the typos are fixed :)

2021-10-01 15:05 UTC, evwilkin approved these changes
LGTM thanks!

2021-10-01 15:50 UTC, jessiehuff approved these changes

2021-10-01 18:04 UTC, merged

2021-10-01 18:23 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.13.3
 - @patternfly/react-code-editor@4.3.70
 - @patternfly/react-console@4.12.3
 - @patternfly/react-core@4.158.3
 - @patternfly/react-docs@5.22.3
 - @patternfly/react-inline-edit-extension@4.7.94
 - demo-app-ts@4.121.12
 - @patternfly/react-log-viewer@4.7.5
 - @patternfly/react-table@4.30.13
 - @patternfly/react-topology@4.9.89
 - @patternfly/react-virtualized-extension@4.9.59

Thanks for your contribution! :tada: