feat(Dropdown): add toggle variants
patternfly/patternfly-react pull request #6651
Opened 2021-11-29 17:01 UTC by kmcfaul

**What**: Closes #6559 & #6600

- Adds `buttonVariant` to `DropdownToggle`. Both `buttonVariant="primary"` and `isPrimary` flags apply the same styling to the toggle.
- Allows action split button toggles to apply primary styling (via `buttonVariant="primary"` or `isPrimary`). This only functions for primary styling and only for action type split button toggles.

2021-11-30 13:34 UTC, nicolethoen reviewed
Is it worth adding one unit test to dropdown to verify the new prop is rendering correctly?

2021-11-30 15:05 UTC, kmcfaul commented
Sure can do

2021-11-30 15:29 UTC, mcarrano reviewed
This looks fine from a form and function standpoint. My only question really is more on the API side. I see that we added a new prop `buttonVariant` but are retaining `isPrimary' so there are two ways to make a primary styled dropdown. Should we make it clear in the documentation that these should not be used together? Also, should people use 'buttonVariant' going forward as the preferred way to modify the toggle?

2021-11-30 21:32 UTC, mcoker reviewed
Looks good to me, just one question.

2021-12-01 10:44 UTC, gabipodolnikova approved these changes

2021-12-01 14:55 UTC, tlabaj commented
> This looks fine from a form and function standpoint. My only question really is more on the API side. I see that we added a new prop `buttonVariant` but are retaining `isPrimary' so there are two ways to make a primary styled dropdown. Should we make it clear in the documentation that these should not be used together? Also, should people use 'buttonVariant' going forward as the preferred way to modify the toggle?

@kmcfaul can we deprecate the `isPrimary` prop?

2021-12-01 15:14 UTC, kmcfaul commented on packages/react-core/src/components/Dropdown/DropdownToggle.tsx
> +  buttonVariant?: 'primary' | 'secondary' | 'default';
I avoided `variant` because we've used that name a lot and it can be overloaded. I agree that `toggleVariant` may fit better here - will update.

2021-12-02 16:14 UTC, tlabaj commented on packages/react-core/src/components/Dropdown/DropdownToggle.tsx
> +  /** @deprecated Whether or not the dropdown toggle button should have primary button styling */
Can you add  "use 'toggleVariant' instead" to the comment.

2021-12-02 16:34 UTC, tlabaj requested changes
just a little tweak needed for the deprecated prop description.

2021-12-02 21:21 UTC, mcoker approved these changes

2021-12-06 14:46 UTC, tlabaj approved these changes
LGTM

2021-12-06 15:03 UTC, merged

2021-12-06 15:14 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.16.0
 - @patternfly/react-catalog-view-extension@4.28.0
 - @patternfly/react-charts@6.30.0
 - @patternfly/react-code-editor@4.18.0
 - @patternfly/react-console@4.28.0
 - @patternfly/react-core@4.177.0
 - @patternfly/react-docs@5.38.0
 - @patternfly/react-icons@4.28.0
 - @patternfly/react-inline-edit-extension@4.22.0
 - demo-app-ts@4.137.0
 - @patternfly/react-integration@4.139.0
 - @patternfly/react-log-viewer@4.22.0
 - @patternfly/react-styles@4.27.0
 - @patternfly/react-table@4.46.0
 - @patternfly/react-tokens@4.29.0
 - @patternfly/react-topology@4.24.0
 - @patternfly/react-virtualized-extension@4.24.0
 - transformer-cjs-imports@4.15.0

Thanks for your contribution! :tada: