fix(Tile): fix selecting tile in tile demo
patternfly/patternfly-react pull request #6653
Opened 2021-11-30 02:45 UTC by nicolethoen

**What**: Closes #6637

Also cleans up some unused imports in the Card examples

2021-11-30 02:56 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-6653.surge.sh

2021-11-30 15:08 UTC, kmcfaul approved these changes

2021-11-30 15:33 UTC, mcarrano requested changes
I still cannot get the tiles to reliably stick in the second demo example (multi-select). Sometime they will sometimes they won't. Testing with Firefox.

2021-12-01 00:58 UTC, nicolethoen commented
@mcarrano good catch! I fixed it

2021-12-01 09:06 UTC, gabipodolnikova approved these changes

2021-12-01 14:32 UTC, mcarrano approved these changes
Looks great!

2021-12-02 16:08 UTC, tlabaj approved these changes

2021-12-02 16:08 UTC, merged

2021-12-02 16:21 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.14.15
 - @patternfly/react-catalog-view-extension@4.26.15
 - @patternfly/react-charts@6.28.15
 - @patternfly/react-code-editor@4.16.15
 - @patternfly/react-console@4.26.15
 - @patternfly/react-core@4.175.15
 - @patternfly/react-docs@5.36.15
 - @patternfly/react-icons@4.26.15
 - @patternfly/react-inline-edit-extension@4.20.15
 - demo-app-ts@4.135.15
 - @patternfly/react-integration@4.137.15
 - @patternfly/react-log-viewer@4.20.15
 - @patternfly/react-styles@4.25.15
 - @patternfly/react-table@4.44.15
 - @patternfly/react-tokens@4.27.15
 - @patternfly/react-topology@4.22.15
 - @patternfly/react-virtualized-extension@4.22.15
 - transformer-cjs-imports@4.13.15

Thanks for your contribution! :tada: