Select crash
patternfly/patternfly-react pull request #6678
Opened 2021-12-07 21:47 UTC by tlabaj

**What**: Closes #6384 

**Additional issues**:

2021-12-07 21:57 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-6678.surge.sh

2021-12-20 20:37 UTC, nicolethoen approved these changes
This is impressive! A one line fix full test suite. 
A good example. We should try and continue addressing select issues like this - to better protect against regressions in the future!

2021-12-23 19:26 UTC, wise-king-sullyman commented
I feel like I'm probably misunderstanding something, but undoing your change to `Select.tsx` doesn't make the integration tests you added fail, is that intentional?

2022-01-05 17:13 UTC, tlabaj commented
> I feel like I'm probably misunderstanding something, but undoing your change to `Select.tsx` doesn't make the integration tests you added fail, is that intentional?

Good catch.  I actually added the wrong demo and test to this PR.

2022-01-10 16:54 UTC, wise-king-sullyman approved these changes

2022-01-10 17:19 UTC, wise-king-sullyman requested changes

2022-01-10 17:19 UTC, wise-king-sullyman commented on packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreTypeaheadGroupedDemo.tsx
> +  options = [
Per our discussion on slack, `options` should be managed in the state since we have option creation functionality.

2022-01-10 18:20 UTC, wise-king-sullyman approved these changes
Looks great!

2022-01-11 18:07 UTC, nicolethoen approved these changes

2022-01-11 18:08 UTC, merged