chore(docs): Release notes 2021_16
patternfly/patternfly-react pull request #6689
Opened 2021-12-09 21:58 UTC by tlabaj

**What**: Closes #6688

2021-12-09 22:07 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-6689.surge.sh

2021-12-13 18:38 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Addedd support for focus trap to be made inactive ([#6638](https://github.com/patternfly/patternfly-react/pull/6638))
Removed extra "d"
```suggestion
  - Added support for focus trap to be made inactive ([#6638](https://github.com/patternfly/patternfly-react/pull/6638))
```

2021-12-13 18:38 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Updaetd to allow date picker users to open the calendar programatically ([#6632](https://github.com/patternfly/patternfly-react/pull/6632))
Spelling typos
```suggestion
  - Updated to allow date picker users to open the calendar programmatically ([#6632](https://github.com/patternfly/patternfly-react/pull/6632))
```

2021-12-13 18:39 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +   Fixed examples with custom steps and input ([#6662](https://github.com/patternfly/patternfly-react/pull/6662))
Missing bullet point
```suggestion
  - Fixed examples with custom steps and input ([#6662](https://github.com/patternfly/patternfly-react/pull/6662))
```

2021-12-13 18:39 UTC, evwilkin requested changes
A few nits

2021-12-13 20:03 UTC, evwilkin approved these changes
LGTM!

2021-12-13 20:16 UTC, nicolethoen approved these changes

2021-12-13 20:16 UTC, merged

2021-12-13 20:25 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.20.2
 - @patternfly/react-catalog-view-extension@4.32.2
 - @patternfly/react-charts@6.34.2
 - @patternfly/react-code-editor@4.22.2
 - @patternfly/react-console@4.32.2
 - @patternfly/react-core@4.181.2
 - @patternfly/react-docs@5.42.2
 - @patternfly/react-icons@4.32.2
 - @patternfly/react-inline-edit-extension@4.26.2
 - demo-app-ts@4.141.2
 - @patternfly/react-integration@4.143.2
 - @patternfly/react-log-viewer@4.26.2
 - @patternfly/react-styles@4.31.2
 - @patternfly/react-table@4.50.2
 - @patternfly/react-tokens@4.33.2
 - @patternfly/react-topology@4.28.2
 - @patternfly/react-virtualized-extension@4.28.2
 - transformer-cjs-imports@4.19.2

Thanks for your contribution! :tada: