fix(Table): use colgroup and nested cols in composable table
patternfly/patternfly-react pull request #6724
Opened 2022-01-02 08:50 UTC by boaz0

**What**: Closes #6642

2022-01-02 08:57 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-6724.surge.sh

2022-01-05 00:20 UTC, nicolethoen reviewed
I'm noticing how the HTML mark up in the core examples for defining `colgroup` and `col` still differs from how it's written in the react.
see this example: https://www.patternfly.org/v4/components/table/html/#nested-column-headers

@mattnolting do you know if there is a better way to do that? Should the span prop go on a colgroup or a col?

2022-01-05 19:13 UTC, mattnolting commented
After discussing next steps w/PF devs, looks like we can remove the `colgroup` and `col` references altogether. [Core followup issue created](https://github.com/patternfly/patternfly/issues/4584).

2022-01-07 17:32 UTC, nicolethoen commented
okay - after the core issue is addressed, this PR can be updated to match.

2022-01-11 12:55 UTC, boaz0 commented
Sounds good to me!

2022-01-18 20:15 UTC, nicolethoen commented
@boaz0 The core PR was merged! :)
Here was the core issue: https://github.com/patternfly/patternfly/issues/4584
Here is the core PR: https://github.com/patternfly/patternfly/pull/4600

So this PR can now be updated to match these changes!

2022-01-21 15:44 UTC, mattnolting commented
Hey @boaz0, thanks for tackling this issue! We've decided to remove `col/colgroup`s altogether, so feel free to make those changes.

2022-01-24 11:35 UTC, boaz0 commented
CI failure is not related to my changes.

2022-02-03 20:19 UTC, nicolethoen approved these changes

2022-02-03 20:25 UTC, mattnolting approved these changes
LGTM👍

2022-02-04 16:19 UTC, tlabaj requested changes

2022-02-04 16:19 UTC, tlabaj commented on packages/react-table/src/components/TableComposable/TableComposable.tsx
> -  nestedHeaderColumnSpans,
I believe you still need this so it does not get spread to the table and cause errors.

2022-02-04 16:21 UTC, tlabaj commented
@mattnolting So, 'nestedHeaderColumnSpans`. and removing it has no impact on consumers correct?

2022-02-04 16:39 UTC, mattnolting commented
> @mattnolting So, 'nestedHeaderColumnSpans`. and removing it has no impact on consumers correct?

If `nestedHeaderColumnSpans` only generates `colgroup/col` markup, then no, it has no impact upon consumers. If it's a shared property, it would affect consumers.

2022-02-07 17:11 UTC, kmcfaul approved these changes
LGTM. `nestedHeaderColumnSpans` is only used to generate the `col/colgroup` setup so it should be fine to deprecate.

2022-02-07 20:02 UTC, nicolethoen approved these changes

2022-02-07 21:15 UTC, tlabaj approved these changes
LGTM

2022-02-07 21:15 UTC, merged