fix(CodeEditor): compare props and state to prevent re-renders
patternfly/patternfly-react pull request #6847
Opened 2022-01-21 22:39 UTC by DaoDaoNoCode

**What**: Closes #6501 

The reason that causes this issue is that when the user defines their own `onChange` function, they will call `setState` to set the `value`, and the `value` will be passed as a prop to the CodeEditor. At the same time, in the CodeEditor component, it will first call `componentDidUpdate` to set the code to the new value, then it will also call the `onChange` function inside the CodeEditor component, where it will use `this.setState` (https://github.com/patternfly/patternfly-react/blob/main/packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx#L279) to set the changed value to the state even the value is already changed, which causes the unnecessary re-renders (Unlike functional component, every time `this.setState` is called, the component will be re-rendered no matter whether the state changed or not).

The way to fix it is to override the `getDerivedStateFromProps` function and check the `prop.code` and `state.value` and don't re-render the component if they are the same. In this way, it will not re-render many times when the `onChange` function is being defined by the users.

2022-01-21 22:49 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-6847.surge.sh

2022-01-24 15:31 UTC, jschuler approved these changes
Thanks for the fix! I tested it out and it works well now

2022-01-24 16:57 UTC, gitdallas requested changes
This is breaking the first example in CodeEditor.md or basically anywhere we aren't holding the value in a state updated onChange and passed into the codeEditor component

2022-01-27 19:10 UTC, DaoDaoNoCode commented
@gitdallas @nicolethoen I didn't really understand the function `getDerivedStateFromProps` before. It's actually just updating the state based on the props, and it will still re-render even if there is no state update. The way we do this is to move what should be done in `componentDidUpdate` into that function so it will only set the state once when the props change. What's more, I added a prop named `prevPropsCode` to record the previous code passed by the props, so we can decide whether the value is updated based on the props code or not.
No need to change the doc examples now and it should work well.

2022-01-27 19:21 UTC, gitdallas approved these changes

2022-01-28 20:09 UTC, tlabaj approved these changes

2022-02-02 14:56 UTC, merged