Rel notes 2022 2
patternfly/patternfly-react pull request #6952
Opened 2022-02-17 21:11 UTC by tlabaj

**What**: Closes #6951

2022-02-17 21:18 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Updated to allow drilldown menu functions ([#6872](https://github.com/patternfly/patternfly-react/pull/6872))
This can be combined with the above "Menu" issue

2022-02-17 21:19 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> + - Fixed documentation build error ([#6937](https://github.com/patternfly/patternfly-react/pull/6937))
Indentation is off, missing 2 spaces
```suggestion
   - Fixed documentation build error ([#6937](https://github.com/patternfly/patternfly-react/pull/6937))
```

2022-02-17 21:19 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +### Topology:**
Remove asterisks
```suggestion
### Topology:
```

2022-02-17 21:20 UTC, evwilkin requested changes
Just a few small issues

2022-02-18 21:36 UTC, evwilkin requested changes
One additional nit - Catalog View Extension indentation

2022-02-21 15:58 UTC, evwilkin approved these changes
LPTM!

2022-02-22 15:12 UTC, nicolethoen requested changes
I approved, then realized this needs a version bump to incorporate the topology update.

2022-02-22 15:46 UTC, nicolethoen approved these changes

2022-02-22 16:50 UTC, evwilkin approved these changes
LGTM

2022-02-22 16:50 UTC, merged