fix(a11y): various aria related updates
patternfly/patternfly-react pull request #7172
Opened 2022-04-02 01:48 UTC by nicolethoen

**What**: Closes #7171

Notes of changes:

- Add `aria-label` prop to ProgressStep documentation
- Add `aria-current=step` to current progress step
- `Aria-current=location` for active jump links
- Tabs - use `tab` role, and `tablist` role (we were already using `tabpanel` role)

2022-04-02 01:57 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7172.surge.sh

2022-04-04 13:53 UTC, thatblindgeye requested changes
Looks good! Really like the addition of the `aria-current` attribute. 

Since `aria-label` has been used elsewhere in the PR, one suggestion I have is passing in something to the `aria-label` prop in the Tabs example(s). Main reason is that right now via VO there's no indication that there is a group of Tab components like there used to be (in the current implementation VO announces "list 6 items" before going to the first Tab item, whereas in this preview build VO goes right to that first tab item). Do you have any other opinion on this?

2022-04-11 17:38 UTC, kmcfaul approved these changes

2022-04-11 17:47 UTC, jessiehuff approved these changes
These all sound great in testing! 😄

2022-04-12 20:06 UTC, merged