feat(Tabs): Add nested, unindented demo
patternfly/patternfly-react pull request #7194
Opened 2022-04-07 20:07 UTC by jenny-s51

**What**: Closes #6861

2022-04-07 20:12 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7194.surge.sh

2022-04-11 16:17 UTC, mcoker requested changes

2022-04-11 16:32 UTC, mmenestr commented
Just for general knowledge, what is an "indented tab" - like how would the demo differ if it wasn't "unindented"?

2022-04-12 18:13 UTC, jenny-s51 commented on packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
> +    <Breadcrumb className="bread">
Nice catch, thank you - updated to use the breadcrumb in `DashboardWrapper`

2022-04-12 18:30 UTC, jenny-s51 commented on packages/react-core/src/demos/examples/Tabs/NestedTabs.tsx
>          </Title>
Thank you @mcoker - great suggestion! Added a `PageTemplateTitle` component and prop to `DashboardWrapper` and updated the demos accordingly  👍

2022-04-12 18:40 UTC, jenny-s51 commented
Hi @mmenestr , great question! The demo for nested tabs wraps all the nested tab content in a card: http://localhost:8002/components/tabs/react-demos/nested-tabs, causing the the nested tab content to have a higher indentation level than the upper tabs.

For the nested, unindented tabs, the tab content is not placed in a card, therefore the nested tabs have the same indentation level as the upper tabs (e.g. "unindented"):  https://patternfly-react-pr-7194.surge.sh/components/tabs/react-demos/nested-unindented-tabs/

2022-04-12 20:41 UTC, mmenestr approved these changes
Ok, thanks for explaining @jenny-s51 ! LGTM

2022-04-14 13:36 UTC, wise-king-sullyman reviewed
I have one nite, other than that it looks great!

2022-04-14 13:36 UTC, wise-king-sullyman commented on packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
> +export const NestedTabs: React.FunctionComponent = () => {
Nit: can you update the component name to match the demo name?

2022-04-14 14:22 UTC, wise-king-sullyman approved these changes

2022-04-14 14:34 UTC, kmcfaul approved these changes

2022-04-14 15:15 UTC, tlabaj requested changes

2022-04-14 15:15 UTC, tlabaj commented on packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
> +      {/* <PageSection variant="light">
Can we remove this commented code?

2022-04-14 19:32 UTC, tlabaj approved these changes

2022-04-14 23:44 UTC, mcoker requested changes
LGTM, just one small change to the example content.

2022-04-14 23:44 UTC, mcoker commented on packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
> +                      </Button>{' '}
```suggestion
                      <a href="#">
                        Download
                      </a>{' '}
```

2022-04-14 23:44 UTC, mcoker commented on packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
> +                      </Button>
```suggestion
                      <a href="#">
                        system requirement
                      </a>
```

2022-04-14 23:44 UTC, mcoker commented on packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
> +                      </Button>{' '}
```suggestion
                      <a href="#">
                        Create
                      </a>{' '}
```

2022-04-18 15:25 UTC, mcoker approved these changes
🚀

2022-04-18 15:54 UTC, merged

2022-04-18 16:20 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.44.0
 - @patternfly/react-catalog-view-extension@4.56.0
 - @patternfly/react-charts@6.58.0
 - @patternfly/react-code-editor@4.46.0
 - @patternfly/react-console@4.56.0
 - @patternfly/react-core@4.205.0
 - @patternfly/react-docs@5.66.0
 - @patternfly/react-icons@4.56.0
 - @patternfly/react-inline-edit-extension@4.50.0
 - demo-app-ts@4.165.0
 - @patternfly/react-integration@4.167.0
 - @patternfly/react-log-viewer@4.50.0
 - @patternfly/react-styles@4.55.0
 - @patternfly/react-table@4.74.0
 - @patternfly/react-tokens@4.57.0
 - @patternfly/react-topology@4.52.0
 - @patternfly/react-virtualized-extension@4.52.0
 - transformer-cjs-imports@4.43.0

Thanks for your contribution! :tada: