Feat(Switch): Adds check + label functionality and demo
patternfly/patternfly-react pull request #7229
Opened 2022-04-12 20:40 UTC by jenny-s51

Extends core work done on https://github.com/patternfly/patternfly/issues/4755

2022-04-12 20:50 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7229.surge.sh

2022-04-13 16:03 UTC, kmcfaul approved these changes

2022-04-13 20:26 UTC, mcarrano approved these changes
This looks great. Thanks @jenny-s51 !

2022-04-14 23:05 UTC, mcoker approved these changes

2022-04-18 13:43 UTC, tlabaj requested changes

2022-04-18 13:43 UTC, tlabaj commented on packages/react-core/src/components/Switch/Switch.tsx
> +  /** Flag to show if the Switch has a check icon. */
nit. sentence case here

2022-04-18 14:05 UTC, tlabaj approved these changes

2022-04-18 14:16 UTC, merged

2022-04-18 14:44 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.42.2
 - @patternfly/react-catalog-view-extension@4.54.2
 - @patternfly/react-charts@6.56.2
 - @patternfly/react-code-editor@4.44.2
 - @patternfly/react-console@4.54.2
 - @patternfly/react-core@4.203.2
 - @patternfly/react-docs@5.64.2
 - @patternfly/react-icons@4.54.2
 - @patternfly/react-inline-edit-extension@4.48.2
 - demo-app-ts@4.163.2
 - @patternfly/react-integration@4.165.2
 - @patternfly/react-log-viewer@4.48.2
 - @patternfly/react-styles@4.53.2
 - @patternfly/react-table@4.72.2
 - @patternfly/react-tokens@4.55.2
 - @patternfly/react-topology@4.50.2
 - @patternfly/react-virtualized-extension@4.50.2
 - transformer-cjs-imports@4.41.2

Thanks for your contribution! :tada: