feat(MenuToggle): Add full width modifier
patternfly/patternfly-react pull request #7232
Opened 2022-04-13 15:16 UTC by nicolethoen

**What**: Closes #7231

2022-04-13 15:25 UTC, mcoker requested changes
just one nit

2022-04-13 15:25 UTC, mcoker commented on packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
> +    <MenuToggle isFullWidth aria-label = "Full width menu toggle" >
```suggestion
    <MenuToggle isFullWidth aria-label="Full width menu toggle" >
```

2022-04-13 15:25 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7232.surge.sh

2022-04-13 15:37 UTC, thatblindgeye approved these changes

2022-04-13 15:43 UTC, jenny-s51 approved these changes

2022-04-13 16:09 UTC, mcoker approved these changes
👏

2022-04-13 22:15 UTC, tlabaj requested changes

2022-04-13 22:15 UTC, tlabaj commented on packages/react-core/src/components/MenuToggle/MenuToggle.tsx
> +  /** Flag indicating the toggle is takes up the full width of its parent */
```suggestion
  /** Flag indicating the toggle takes up the full width of its parent */
```

2022-04-14 13:13 UTC, wise-king-sullyman approved these changes

2022-04-14 14:33 UTC, kmcfaul approved these changes

2022-04-14 20:46 UTC, tlabaj approved these changes

2022-04-14 20:46 UTC, merged

2022-04-14 21:16 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.42.0
 - @patternfly/react-catalog-view-extension@4.54.0
 - @patternfly/react-charts@6.56.0
 - @patternfly/react-code-editor@4.44.0
 - @patternfly/react-console@4.54.0
 - @patternfly/react-core@4.203.0
 - @patternfly/react-docs@5.64.0
 - @patternfly/react-icons@4.54.0
 - @patternfly/react-inline-edit-extension@4.48.0
 - demo-app-ts@4.163.0
 - @patternfly/react-integration@4.165.0
 - @patternfly/react-log-viewer@4.48.0
 - @patternfly/react-styles@4.53.0
 - @patternfly/react-table@4.72.0
 - @patternfly/react-tokens@4.55.0
 - @patternfly/react-topology@4.50.0
 - @patternfly/react-virtualized-extension@4.50.0
 - transformer-cjs-imports@4.41.0

Thanks for your contribution! :tada: