Feat(Table): Adds full screen demo for bulk select
patternfly/patternfly-react pull request #7264
Opened 2022-04-19 17:39 UTC by jenny-s51

**What**: Closes #7262 -

2022-04-19 17:48 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7264.surge.sh

2022-04-25 20:16 UTC, mmenestr approved these changes
LGTM!

2022-05-02 16:12 UTC, mcoker approved these changes
LGTM!

2022-05-03 15:53 UTC, tlabaj requested changes
LGTM

2022-05-03 16:46 UTC, tlabaj approved these changes

2022-05-03 20:32 UTC, kmcfaul approved these changes

2022-05-03 20:32 UTC, merged

2022-05-03 21:00 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.47.6
 - @patternfly/react-catalog-view-extension@4.59.6
 - @patternfly/react-charts@6.61.6
 - @patternfly/react-code-editor@4.49.6
 - @patternfly/react-console@4.59.6
 - @patternfly/react-core@4.208.6
 - @patternfly/react-docs@5.69.6
 - @patternfly/react-icons@4.59.6
 - @patternfly/react-inline-edit-extension@4.53.6
 - demo-app-ts@4.168.6
 - @patternfly/react-integration@4.170.6
 - @patternfly/react-log-viewer@4.53.6
 - @patternfly/react-styles@4.58.6
 - @patternfly/react-table@4.77.6
 - @patternfly/react-tokens@4.60.6
 - @patternfly/react-topology@4.55.6
 - @patternfly/react-virtualized-extension@4.55.6
 - transformer-cjs-imports@4.46.6

Thanks for your contribution! :tada: