chore(docs):release notes 2022.05
patternfly/patternfly-react pull request #7290
Opened 2022-04-22 13:32 UTC by tlabaj

**What**: Closes #2789

2022-04-22 13:41 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7290.surge.sh

2022-04-22 15:25 UTC, evwilkin requested changes
Content looks great, just one small typo 🏆

2022-04-22 15:25 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +- Added Support esm import and export ([#7084](https://github.com/patternfly/patternfly-react/pull/7084))
Small fix
```suggestion
- Added support for esm import and export ([#7084](https://github.com/patternfly/patternfly-react/pull/7084))
```

2022-04-22 18:18 UTC, nicolethoen reviewed
@tlabaj could you also regenerate screenshots?

2022-04-22 23:48 UTC, evwilkin approved these changes
LGTM - thanks!

2022-04-23 17:07 UTC, nicolethoen approved these changes

2022-04-23 17:07 UTC, merged

2022-04-23 17:35 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.45.3
 - @patternfly/react-catalog-view-extension@4.57.3
 - @patternfly/react-charts@6.59.3
 - @patternfly/react-code-editor@4.47.3
 - @patternfly/react-console@4.57.3
 - @patternfly/react-core@4.206.3
 - @patternfly/react-docs@5.67.3
 - @patternfly/react-icons@4.57.3
 - @patternfly/react-inline-edit-extension@4.51.3
 - demo-app-ts@4.166.3
 - @patternfly/react-integration@4.168.3
 - @patternfly/react-log-viewer@4.51.3
 - @patternfly/react-styles@4.56.3
 - @patternfly/react-table@4.75.3
 - @patternfly/react-tokens@4.58.3
 - @patternfly/react-topology@4.53.3
 - @patternfly/react-virtualized-extension@4.53.3
 - transformer-cjs-imports@4.44.3

Thanks for your contribution! :tada: