feat(charts): added PF dark theme support
patternfly/patternfly-react pull request #7310
Opened 2022-04-28 16:59 UTC by mcoker

fixes https://github.com/patternfly/patternfly-react/issues/7188

2022-05-02 15:59 UTC, mcoker commented
Current screenshots:
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 03 AM" src="https://user-images.githubusercontent.com/35148959/166266157-3e6e2395-f367-464f-88e7-26630ba6c294.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 05 AM" src="https://user-images.githubusercontent.com/35148959/166266163-f41220cf-7da5-4cfe-b854-5c49108f082b.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 11 AM" src="https://user-images.githubusercontent.com/35148959/166266166-6cf95085-6144-4baa-a018-a38515f4e3d5.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 14 AM" src="https://user-images.githubusercontent.com/35148959/166266170-2a446fe8-c5b7-415b-b9fb-5a64ab5bb921.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 22 AM" src="https://user-images.githubusercontent.com/35148959/166266173-a0941bf8-9fe6-4d93-814b-08ba05127e65.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 25 AM" src="https://user-images.githubusercontent.com/35148959/166266175-d60cc9da-da0b-4798-883b-968232dfea4c.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 32 AM" src="https://user-images.githubusercontent.com/35148959/166266178-23eee755-e4dd-4c91-91d6-1a84f16d0e36.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 36 AM" src="https://user-images.githubusercontent.com/35148959/166266180-13b6252d-6a7f-4b90-a401-d6034aabbc53.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 39 AM" src="https://user-images.githubusercontent.com/35148959/166266181-ff6c8370-4bae-4fb5-9d02-818d002ece5f.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 43 AM" src="https://user-images.githubusercontent.com/35148959/166266183-5f87c274-4c3b-49d5-9b8a-8df22b72c9ac.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 48 AM" src="https://user-images.githubusercontent.com/35148959/166266185-7801060b-c8f7-4239-9e15-13ebb3394684.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 50 AM" src="https://user-images.githubusercontent.com/35148959/166266188-0ef87f98-40bb-464f-a731-7e82ec27992c.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 29 57 AM" src="https://user-images.githubusercontent.com/35148959/166266193-1bca6d60-3315-471d-9a17-e32967475fea.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 00 AM" src="https://user-images.githubusercontent.com/35148959/166266194-2813a64a-a831-4477-a38f-6cb1c58c5b19.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 03 AM" src="https://user-images.githubusercontent.com/35148959/166266195-0e66a7e3-7e46-4ca4-8d62-4f06e805094c.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 09 AM" src="https://user-images.githubusercontent.com/35148959/166266196-46e103e4-7518-4b15-a7ea-1d05964e0579.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 11 AM" src="https://user-images.githubusercontent.com/35148959/166266199-de1ed0e2-7c87-4efc-85f3-a8717e9a3432.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 13 AM" src="https://user-images.githubusercontent.com/35148959/166266200-31318db6-5d80-4af3-9954-2ab7f05d8a4b.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 17 AM" src="https://user-images.githubusercontent.com/35148959/166266203-d498f0d9-daff-4636-93fb-f6bf7f07bf5a.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 19 AM" src="https://user-images.githubusercontent.com/35148959/166266205-2906974e-3464-4927-aa82-81c0073ecea5.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 22 AM" src="https://user-images.githubusercontent.com/35148959/166266207-2b627dd1-cf24-49f7-85d2-e3d7dd913eb7.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 24 AM" src="https://user-images.githubusercontent.com/35148959/166266209-9f5cb8ce-3375-463e-b296-6171bc465ad0.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 29 AM" src="https://user-images.githubusercontent.com/35148959/166266210-97f95ff3-0e67-4195-80e6-07244a2d22d6.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 31 AM" src="https://user-images.githubusercontent.com/35148959/166266212-8592bf65-d699-4afd-94d6-cf3bbb3ccde3.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 34 AM" src="https://user-images.githubusercontent.com/35148959/166266213-cd3e6cca-44b5-4697-b342-ab3e7a2b8f21.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 36 AM" src="https://user-images.githubusercontent.com/35148959/166266216-d8fc40da-e33f-49d8-b8ce-b4519a238eb9.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 44 AM" src="https://user-images.githubusercontent.com/35148959/166266217-c237991c-cc4b-4fac-994e-db0888073893.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 46 AM" src="https://user-images.githubusercontent.com/35148959/166266221-5ab05e3c-7572-4da8-86bc-3919567e67f1.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 30 50 AM" src="https://user-images.githubusercontent.com/35148959/166266226-118e20ec-b3ed-4c05-83b8-900d8fd66205.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 20 AM" src="https://user-images.githubusercontent.com/35148959/166266228-c1299820-141e-47df-8d23-1964bd7b45cb.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 24 AM" src="https://user-images.githubusercontent.com/35148959/166266229-a8f767ea-7c7d-422f-97df-88eb7c9b3cb1.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 29 AM" src="https://user-images.githubusercontent.com/35148959/166266231-bf458e71-7ddc-479c-907d-c2a3af3ae7e6.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 35 AM" src="https://user-images.githubusercontent.com/35148959/166266232-106fe0a6-fac9-4635-bc5b-bd001404e8b0.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 37 AM" src="https://user-images.githubusercontent.com/35148959/166266235-b48deed5-192e-4677-90eb-f11b1cb19567.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 40 AM" src="https://user-images.githubusercontent.com/35148959/166266237-45393400-f9e3-4ed9-8cb7-4336d6ec8893.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 44 AM" src="https://user-images.githubusercontent.com/35148959/166266238-a77e6450-3705-4e2c-a6e4-a6e5d5478905.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 46 AM" src="https://user-images.githubusercontent.com/35148959/166266240-0a9ba987-8546-4399-856d-5d777f3bd7d4.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 48 AM" src="https://user-images.githubusercontent.com/35148959/166266241-ad65859b-3de1-4134-bbf0-e0569cbc6635.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 54 AM" src="https://user-images.githubusercontent.com/35148959/166266242-0a4e0319-501f-4eeb-b49a-1c0e1af3f94b.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 31 59 AM" src="https://user-images.githubusercontent.com/35148959/166266243-60c67546-da76-4a52-a8e5-b1ed2cecb016.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 32 01 AM" src="https://user-images.githubusercontent.com/35148959/166266244-84a30208-3865-46af-818f-6fc6ef5f2cac.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 32 03 AM" src="https://user-images.githubusercontent.com/35148959/166266247-96d43cd0-1c1f-43fb-b023-92e7b880c3dd.png">
<img width="1541" alt="Screen Shot 2022-05-02 at 10 32 05 AM" src="https://user-images.githubusercontent.com/35148959/166266249-4d87ac11-15db-4653-902b-e4d727195536.png">

This is a custom chart with multiple positive/negative measures to show the palette contrast.

<img width="1541" alt="Screen Shot 2022-05-02 at 10 34 01 AM" src="https://user-images.githubusercontent.com/35148959/166266250-7d7a551f-30e0-4ca8-aa1f-7bfecb95bb17.png">

2022-05-02 18:53 UTC, dlabrecq requested changes
The "Cannot find module" won't succeed until the PatternFly core package is updated.

Alternatively, the new vars for the bullet chart color pallet could be reverted? Doesn't seem like we have vars for all color pallets.

2022-05-02 18:53 UTC, dlabrecq commented on packages/react-charts/src/components/ChartLabel/ChartLabel.tsx
> +        // fill: ChartCommonStyles.label.fill,
This comment can be removed

2022-05-02 18:53 UTC, dlabrecq commented on packages/react-charts/src/components/ChartTheme/themes/base-theme.ts
> -      }
Not sure this `fill` should be removed? 

The `fill` had a value of #4f5255. Not sure what `chart_global_label_Fill.va`r is?

2022-05-02 18:53 UTC, dlabrecq commented on packages/react-charts/src/components/ChartTheme/themes/dark/multi-color-ordered-theme.ts
> +  chart_color_orange_200.var
Michael Celedonia suggested he was having trouble with color pallets and the dark them. I understood he wanted to shift the multi-color pallet by one color.

Are we not going to create vars for all color pallets? 

I see that `chart_bullet_negative_measure_ColorScale_100.var` was used for the bullet chart

2022-05-02 18:53 UTC, dlabrecq commented on packages/react-charts/src/components/ChartTheme/themes/bullet-theme.ts
> +      chart_bullet_negative_measure_ColorScale_500.var
Are we going to use vars for all color pallets? 

Ideally, all color pallets would be implemented similarly. If not, then perhaps this should be reverted?

2022-05-06 15:55 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7310.surge.sh

2022-05-06 18:57 UTC, mceledonia approved these changes

2022-05-07 17:55 UTC, dlabrecq reviewed
Tested locally and within Cost Management and the UIs look good. Not set up to test the dark theme in Cost, tho.

I noticed a few more places where we still reference value for colors

<img width="1236" alt="Screen Shot 2022-05-07 at 1 54 28 PM" src="https://user-images.githubusercontent.com/17481322/167266078-d53f8ac2-f4e4-451c-9f39-275f34560fd8.png">

2022-05-08 22:50 UTC, mcoker commented
@dlabrecq updated those spots to use `var`

2022-05-08 23:47 UTC, dlabrecq approved these changes
LGTM

2022-05-09 21:00 UTC, tlabaj approved these changes
LGTM

2022-05-09 21:01 UTC, merged

2022-05-09 21:26 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.51.0
 - @patternfly/react-catalog-view-extension@4.63.0
 - @patternfly/react-charts@6.65.0
 - @patternfly/react-code-editor@4.53.0
 - @patternfly/react-console@4.63.0
 - @patternfly/react-core@4.212.0
 - @patternfly/react-docs@5.73.0
 - @patternfly/react-icons@4.63.0
 - @patternfly/react-inline-edit-extension@4.57.0
 - demo-app-ts@4.172.0
 - @patternfly/react-integration@4.174.0
 - @patternfly/react-log-viewer@4.57.0
 - @patternfly/react-styles@4.62.0
 - @patternfly/react-table@4.81.0
 - @patternfly/react-tokens@4.64.0
 - @patternfly/react-topology@4.59.0
 - @patternfly/react-virtualized-extension@4.59.0
 - transformer-cjs-imports@4.50.0

Thanks for your contribution! :tada: