fix(Tooltip): make ref variant announced by assistive tech
patternfly/patternfly-react pull request #7332
Opened 2022-05-02 13:51 UTC by thatblindgeye

**What**: Closes #7331

**Additional issues**:
This PR also updates the Tab component that was previously updated in PR #6940.

Additionally, this PR could also resolve issues #7021 and #4446, but only when using the React or selector ref variants (or by using `aria="none"` and `aria-live="polite"` props). So this could potentially require altering how the Tooltip prop is setup or just a larger discussion, depending on if another solution can be found when not using a ref. This I believe was alluded to in another issue in this epic #1655: "One possible alternative is to render the tooltip as an aria-live region."

This PR getting merged would also go towards fixing #7096, as that would be updated to follow the "Icon with dynamic content" Tooltip example in this PR.

2022-05-02 14:00 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7332.surge.sh

2022-05-02 19:13 UTC, jessiehuff reviewed
I think this is definitely a really interesting approach. It likely would eliminate some of the differences we've been seeing across browsers and screen readers. I know that some thought leaders haven't been in favor of this approach (for example, Sarah Higley who works at Microsoft, wrote [this article warning against it](https://sarahmhigley.com/writing/tooltips-in-wcag-21/)). However, I've also read others [like this one](https://pressbooks.library.ryerson.ca/wafd/chapter/tooltips/) that speak to our experience. I think if we're finding that this is the most accessible and consistent across browsers and screen readers, then we should go with what works. Open to what others think. 🙂 I'm wondering if I should test this with other screen readers outside of VO.

2022-05-03 12:43 UTC, thatblindgeye commented
> I think this is definitely a really interesting approach. It likely would eliminate some of the differences we've been seeing across browsers and screen readers. I know that some thought leaders haven't been in favor of this approach (for example, Sarah Higley who works on Microsoft's a11y, wrote [this article warning against it](https://sarahmhigley.com/writing/tooltips-in-wcag-21/)). However, I've also read others [like this one](https://pressbooks.library.ryerson.ca/wafd/chapter/tooltips/) that speak to our experience. I think if we're finding that this is the most accessible and consistent across browsers and screen readers, then we should go with what works. Open to what others think. 🙂 I'm wondering if I should test this with other screen readers outside of VO.

Yeah I think it's really iffy either way. I do agree with that first article in regards to users not being able to opt out when a tooltip uses `aria-live`, but I do feel the preferred method in that article also suffers the drawback of not being reliably read by screen readers (though I think slightly worse when it comes to using refs in React, and then there is also Safari which doesn't seem to read tooltips properly even when used as a wrapper with `aria-describedby`).

It can really come down to not allowing users to opt out of the tooltip content vs not having the tooltip content read whatsoever depending on the browser (which even if tooltip content shouldn't be required for users to understand something, I'm not sure if preventing it from users because of browser is the right move).

2022-05-04 15:03 UTC, kmcfaul requested changes

2022-05-05 01:48 UTC, nicolethoen commented
Testing the changes works great! I just want to sanity check my understanding that the only html markup change with this approach is the aria-live and aria attributes? It doesn't seem too risky of a breaking change unless there is something else I'm missing

2022-05-05 12:13 UTC, thatblindgeye commented
> Testing the changes works great! I just want to sanity check my understanding that the only html markup change with this approach is the aria-live and aria attributes? It doesn't seem too risky of a breaking change unless there is something else I'm missing

@nicolethoen That's correct, ideally this shouldn't cause any breaking issues since it's only adding the optional aria-live prop, and if any consumers are already using that attribute it should still work as they intended.

2022-05-05 12:40 UTC, nicolethoen approved these changes

2022-05-05 18:51 UTC, jessiehuff approved these changes
LGTM! 🙂

2022-05-05 20:15 UTC, thatblindgeye commented
@nicolethoen Per convo with @jessiehuff, the Tooltip and Tabs examples that use the `reference` prop on the Tooltip have the `aria-describedby` attribute added back in. Both JAWS and NVDA didn't announce the tooltip contents with only `aria-live`, so adding the aria-describedby back in resolves that while aria-live helps with VO.

Further tweaking of the Tooltip component may be needed down the line to find a solution that helps with these three main screen readers, but this does help improve things a bit still.

2022-05-05 21:31 UTC, tlabaj approved these changes

2022-05-06 00:54 UTC, nicolethoen approved these changes

2022-05-06 19:12 UTC, kmcfaul approved these changes

2022-05-06 19:13 UTC, merged