feat(table): convert/update fullscreen loading state demo
patternfly/patternfly-react pull request #7370
Opened 2022-05-05 18:53 UTC by jenny-s51

**What**: Closes #7342

2022-05-06 13:48 UTC, mcarrano approved these changes
This looks great @jenny-s51 . Please disregard my comment on your other PR then as I didn't realize you were making these demo changes separately.

2022-05-06 16:01 UTC, mmenestr approved these changes

2022-05-06 19:34 UTC, tlabaj approved these changes

2022-05-24 15:14 UTC, mcoker requested changes
LGTM! Just a couple of small nits.

2022-05-24 15:14 UTC, mcoker commented on packages/react-table/src/demos/Table.md
> +                  <Title size="lg" headingLevel="h4">
Looks like this should be an `<h2>` since the only other heading on the page is an `<h1>`

2022-05-24 17:51 UTC, jenny-s51 reviewed
Thank you @mcoker - updated based on your feedback!

2022-05-24 17:55 UTC, mcoker approved these changes
lgtm!!

2022-05-24 18:26 UTC, merged

2022-05-24 18:56 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.56.0
 - @patternfly/react-catalog-view-extension@4.68.0
 - @patternfly/react-charts@6.70.0
 - @patternfly/react-code-editor@4.58.0
 - @patternfly/react-console@4.68.0
 - @patternfly/react-core@4.217.0
 - @patternfly/react-docs@5.78.0
 - @patternfly/react-icons@4.68.0
 - @patternfly/react-inline-edit-extension@4.62.0
 - demo-app-ts@4.177.0
 - @patternfly/react-integration@4.179.0
 - @patternfly/react-log-viewer@4.62.0
 - @patternfly/react-styles@4.67.0
 - @patternfly/react-table@4.86.0
 - @patternfly/react-tokens@4.69.0
 - @patternfly/react-topology@4.64.0
 - @patternfly/react-virtualized-extension@4.64.0
 - transformer-cjs-imports@4.55.0

Thanks for your contribution! :tada: