refactor(Search Input): use TextInputGroup instead native HTML elements
patternfly/patternfly-react pull request #7414
Opened 2022-05-13 12:25 UTC by bartoval

**What**: Closes #7121

2022-05-13 12:34 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7414.surge.sh

2022-05-17 17:46 UTC, nicolethoen requested changes
The resulting HTML markup of these search input examples should match that of [these text input group examples in the html docs](https://www.patternfly.org/v4/components/text-input-group/html#search-input-group).
Ultimately, you should (hopefully) be able to remove `import styles from '@patternfly/react-styles/css/components/SearchInput/search-input';`

2022-05-18 08:05 UTC, bartoval commented
> The resulting HTML markup of these search input examples should match that of [these text input group examples in the html docs](https://www.patternfly.org/v4/components/text-input-group/html#search-input-group). Ultimately, you should (hopefully) be able to remove `import styles from '@patternfly/react-styles/css/components/SearchInput/search-input';`

Hey!
Thanks for these suggestions 💯

2022-05-18 13:56 UTC, nicolethoen reviewed
This is looking good! There is still an extra wrapper `div` which is always wrapping the text-input-group in the react examples that is not in the html examples. Can we remove that?

2022-05-25 20:51 UTC, tlabaj requested changes

2022-05-25 20:51 UTC, tlabaj commented on packages/react-core/src/components/SearchInput/SearchInput.tsx
> +              <Button variant={ButtonVariant.plain} aria-label="Next" isDisabled={isDisabled} onClick={onNextClick}>
we need the ability to customize this label for localization

2022-05-26 12:47 UTC, tlabaj approved these changes
LGTM

2022-05-26 16:32 UTC, bartoval commented
> This looks great! 👍 A few questions about `disabled` states for buttons.
> 
> Looks like the previous button in [match with navigable options](https://patternfly-react-pr-7414.surge.sh/components/search-input#match-with-navigable-options) should be disabled at match `1`.
> 
> ![Screen Shot 2022-05-26 at 9 06 58 AM](https://user-images.githubusercontent.com/5385435/170494215-ac3e3bf4-bc75-477b-b34f-05e467c444de.png)
> 
> Should the submit button in [With submit button](https://patternfly-react-pr-7414.surge.sh/components/search-input#with-submit-button) and [Advanced](https://patternfly-react-pr-7414.surge.sh/components/search-input#advanced) should be disabled by default as well?
> 
> ![Screen Shot 2022-05-26 at 9 11 28 AM](https://user-images.githubusercontent.com/5385435/170494497-86ccf30d-d083-47de-8141-92a732a6a8da.png)
> 
> ![Screen Shot 2022-05-26 at 9 14 17 AM](https://user-images.githubusercontent.com/5385435/170494914-8d59d175-e480-4565-9ec4-903814191f66.png)

Thanks, @mattnolting, you are right 👍🏼 
So I implemented them.

2022-05-26 17:06 UTC, mattnolting commented
@bartoval Great, thanks! Looks like the [Advanced example](https://patternfly-react-pr-7414.surge.sh/components/search-input/#advanced) has a last glitch.

![Screen Recording 2022-05-26 at 1 02 15 PM](https://user-images.githubusercontent.com/5385435/170538806-69bdc2b8-fa9e-40a4-bd80-e2ea873125ae.gif)

2022-05-26 17:53 UTC, bartoval commented
> @bartoval Great, thanks! Looks like the [Advanced example](https://patternfly-react-pr-7414.surge.sh/components/search-input/#advanced) has a last glitch.
> 
> ![Screen Recording 2022-05-26 at 1 02 15 PM](https://user-images.githubusercontent.com/5385435/170538806-69bdc2b8-fa9e-40a4-bd80-e2ea873125ae.gif) [ ](https://user-images.githubusercontent.com/5385435/170538806-69bdc2b8-fa9e-40a4-bd80-e2ea873125ae.gif) ![Screen Recording 2022-05-26 at 1 02 15 PM](https://user-images.githubusercontent.com/5385435/170538806-69bdc2b8-fa9e-40a4-bd80-e2ea873125ae.gif) [ ](https://user-images.githubusercontent.com/5385435/170538806-69bdc2b8-fa9e-40a4-bd80-e2ea873125ae.gif)

thanks again for your eagle eye 🥇 
Fixed

2022-05-26 19:20 UTC, thatblindgeye reviewed
Awesome work on this!

Similar to @mattnolting comment regarding [match with navigable options](https://patternfly-react-pr-7414.surge.sh/components/search-input#match-with-navigable-options), I think it'd make sense to also add similar functionality to disable next button when the current result is at the last result.

2022-05-26 19:46 UTC, thatblindgeye approved these changes
💪🏼

2022-05-26 20:24 UTC, mattnolting approved these changes
Fantastic! 🚢  it!

2022-05-26 22:08 UTC, bartoval commented
> Looks like we were both pressing a button on this PR at the same time! Approving again just for visibility in the "reviewers" sidebar.

lol https://media.giphy.com/media/TbYgHMnICI1A4/giphy.gif

2022-05-27 13:49 UTC, mmenestr commented
Overall, this looks good to me - I'm just wondering why we decided to disable the submit button in the case, until someone actually types something into the search area? I haven't seen us do that in the past (for example, when we used the input group for search).

I don't think there's anything wrong with that approach, but just wonder why we're changing the usual approach here!

2022-05-27 16:21 UTC, mmenestr commented
Oh, missed that! Ok, from a consistency standpoint, we don't usually do this, but I guess it makes sense, so we can ship it!! :)

2022-05-27 16:21 UTC, mmenestr approved these changes

2022-05-27 23:06 UTC, wise-king-sullyman approved these changes
Looks 🔥

2022-05-31 13:51 UTC, bartoval commented
> > Overall, this looks good to me - I'm just wondering why we decided to disable the submit button in the case, until someone actually types something into the search area? I haven't seen us do that in the past (for example, when we used the input group for search).
> > I don't think there's anything wrong with that approach, but just wonder why we're changing the usual approach here!
> 
> @mattnolting had suggested this above.

I also think this feat improves the accessibility (the aria-l
![Screenshot from 2022-05-31 15-48-10](https://user-images.githubusercontent.com/79913332/171189766-91aedf40-445c-4b23-a5f7-b7e51420c977.png)
abel became true) when you can't proceed

2022-05-31 13:59 UTC, nicolethoen reviewed
The only thing I noticed is that the original advanced search example does not append the advanced form inline. It lays over the code editor and other example controls. In the updated example, it moves those controls down. Is that intended? @mmenestr @mattnolting do you have thoughts on that? I fear that is a change in default behavior that will surprise consumers.

Old example:
![Screen Shot 2022-05-31 at 9 58 55 AM](https://user-images.githubusercontent.com/26305082/171191449-5b37d511-6ca0-4ced-9491-1fa0974d8b60.png)

updated example:
![Screen Shot 2022-05-31 at 9 59 19 AM](https://user-images.githubusercontent.com/26305082/171191548-01200ad7-02e5-434e-a0fd-1c0d0946735a.png)

2022-06-01 13:54 UTC, nicolethoen approved these changes

2022-06-01 13:55 UTC, merged

2022-06-20 14:52 UTC, garrett commented
When attempting to upgrade to the latest release of PatternFly, we spotted an issue due to failing tests. It appears to be related to this PR, as it changes the previous widgets used from HTML to the PF Panel component. Previously, it used the `pf-c-search-input__menu` class, but now it uses these classes: `pf-c-panel pf-m-raised pf-c-search-input__menu`.

However, pf-c-panel makes the popover `position: relative` now, instead of `position: absolute` and the width of the popover is now `auto` instead of being 100% wide.

As a result of the changes, the panel popover for the advanced filter still reserves the space in the toolbar, causing a layout shift when it appears, which looks like this:

![relative whoops](https://user-images.githubusercontent.com/12330670/174309596-425e8af0-ddc0-4bc9-bda4-3a99f1c12c2b.png)

(You can see the panel below the toolbar still... but as it's relative positioning instead of absolute, it now affects the flow of the content in the toolbar.)