refactor(Search Input): use Panel instead Card in composable advanced…
patternfly/patternfly-react pull request #7431
Opened 2022-05-17 07:42 UTC by bartoval

… search demo

**What**: Closes #7340

2022-05-17 07:51 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7431.surge.sh

2022-05-17 12:23 UTC, thatblindgeye approved these changes

2022-05-17 12:36 UTC, nicolethoen requested changes
Could you add `variant='raised'` prop to the panel so it has a drop shadow?

2022-05-17 15:41 UTC, nicolethoen approved these changes

2022-05-26 20:44 UTC, mattnolting approved these changes
Great work, LPTM!

2022-05-27 16:07 UTC, merged