refactor(Helper Text): Convert helper text examples to typescript
patternfly/patternfly-react pull request #7488
Opened 2022-06-01 05:52 UTC by bartoval

**What**: Closes #7481

2022-06-01 06:02 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7488.surge.sh

2022-06-01 16:51 UTC, thatblindgeye requested changes
For the file names, the full component name could be used I think, e.g. `HelperTextDynamic.tsx`. Similar to the comment in the Hint PR, within the examples the exported component names could also match the file names to follow the convention used in other conversions.

2022-06-03 18:13 UTC, wise-king-sullyman approved these changes
🔥

2022-06-07 13:48 UTC, tlabaj approved these changes
LGTM

2022-06-07 13:48 UTC, merged

2022-06-07 14:14 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.60.7
 - @patternfly/react-catalog-view-extension@4.72.7
 - @patternfly/react-charts@6.74.7
 - @patternfly/react-code-editor@4.62.7
 - @patternfly/react-console@4.72.7
 - @patternfly/react-core@4.221.7
 - @patternfly/react-docs@5.82.7
 - @patternfly/react-icons@4.72.7
 - @patternfly/react-inline-edit-extension@4.66.7
 - demo-app-ts@4.181.7
 - @patternfly/react-integration@4.183.7
 - @patternfly/react-log-viewer@4.66.7
 - @patternfly/react-styles@4.71.7
 - @patternfly/react-table@4.90.7
 - @patternfly/react-tokens@4.73.7
 - @patternfly/react-topology@4.68.7
 - @patternfly/react-virtualized-extension@4.68.7
 - transformer-cjs-imports@4.59.7

Thanks for your contribution! :tada: