Release notes 2022.07
patternfly/patternfly-react pull request #7501
Opened 2022-06-02 19:08 UTC by tlabaj

**What**: Closes #7500

2022-06-02 19:19 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7501.surge.sh

2022-06-02 20:19 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Updated tp use text input group instead native HTML elements ([#7414](https://github.com/patternfly/patternfly-react/pull/7414))
Typo "to"
```suggestion
  - Updated to use text input group instead native HTML elements ([#7414](https://github.com/patternfly/patternfly-react/pull/7414))
```

2022-06-02 20:21 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Added custom maxWidth prop ([#7387](https://github.com/patternfly/patternfly-react/pull/7387))
Format prop name to match other props
```suggestion
  - Added custom `maxWidth` prop ([#7387](https://github.com/patternfly/patternfly-react/pull/7387))
```

2022-06-02 20:34 UTC, evwilkin requested changes
Two nits

2022-06-03 16:01 UTC, evwilkin approved these changes
LGTM

2022-06-03 20:15 UTC, nicolethoen approved these changes

2022-06-03 20:15 UTC, merged

2022-06-03 20:42 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.60.5
 - @patternfly/react-catalog-view-extension@4.72.5
 - @patternfly/react-charts@6.74.5
 - @patternfly/react-code-editor@4.62.5
 - @patternfly/react-console@4.72.5
 - @patternfly/react-core@4.221.5
 - @patternfly/react-docs@5.82.5
 - @patternfly/react-icons@4.72.5
 - @patternfly/react-inline-edit-extension@4.66.5
 - demo-app-ts@4.181.5
 - @patternfly/react-integration@4.183.5
 - @patternfly/react-log-viewer@4.66.5
 - @patternfly/react-styles@4.71.5
 - @patternfly/react-table@4.90.5
 - @patternfly/react-tokens@4.73.5
 - @patternfly/react-topology@4.68.5
 - @patternfly/react-virtualized-extension@4.68.5
 - transformer-cjs-imports@4.59.5

Thanks for your contribution! :tada: