fix(Table): update expandable examples to set column widths
patternfly/patternfly-react pull request #7513
Opened 2022-06-04 07:28 UTC by bartoval

**What**: Closes #7460

2022-06-04 07:39 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7513.surge.sh

2022-06-06 13:16 UTC, thatblindgeye requested changes
Awesome job, the examples look great! I think it might be worth also updating the ComposableTableCompoundExpandable example, as testing that one out with the "lorem ipsum..." text has the same column width changing behavior without the set widths.

Another thing might be including the verbiage that was included on the Core example (copy pasted below), but since this is updating multiple examples I'm not sure if we'd want that text repeated 5+ times on the page. If you or anyone else has any thoughts on this they'd be appreciated.

Verbiage from Core example:
>Note: Table column widths will respond automatically when toggling expanded rows. To retain column widths between expanded and collapsed states, column header and/or data cell widths must be set.

2022-06-06 16:02 UTC, thatblindgeye commented
>For the second question, I don't have a strong opinion. I believe people can see the code example easily if they have trouble.
In case we can put this note only for the first one, that represents the main example.
Otherwise, we can move these examples and group them under the title expandable (like in the HTML example, but I don't know if currently we are following a logic to order our examples)

I'd agree with adding the note on the first/main expandable example. Depending what you think, another option in addition to adding the note on the main example could be to add onto the `isExpanded` prop description on the `Tr` component to include something along the lines of, "To prevent column widths from responding automatically when expandable rows are toggled, the width prop must also be passed into either the th or td component" (though I don't feel super strong about it, more just an additional option).

2022-06-06 16:45 UTC, bartoval commented
> To prevent column widths from responding automatically when expandable rows are toggled, the width prop must also be passed into either the th or td component

👍🏼  I think is a good idea to add this info into the TR doc

2022-06-15 17:54 UTC, kmcfaul approved these changes

2022-06-17 12:44 UTC, tlabaj approved these changes

2022-06-17 12:44 UTC, merged