fix(Table): account for added columns with expandable
patternfly/patternfly-react pull request #7529
Opened 2022-06-08 18:24 UTC by kmcfaul

**What**: Closes #3613

Updates collapsible transform logic to account for additional added columns (actions, selectable, etc). Currently using the internal `firstUserColumnIndex` flag but more fine grained control can be added by checking each feature flag individually instead.

2022-06-08 18:34 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7529.surge.sh

2022-06-13 13:57 UTC, nicolethoen requested changes
The Legacy table looks great!!

I'm not sure if the updates conflict with the composable table example, or if the expandable composable table examples just need a little work - It looks like colspan is calculated by the consumer in the example.

[This code sandbox](https://codesandbox.io/s/qjh5k8) was built using your PR, and highlights the fact that colspan is not being calculated the same way in the composable examples.

2022-06-14 19:08 UTC, nicolethoen commented
Should we fix the composable examples as part of this issue, @kmcfaul ?

2022-06-14 20:08 UTC, kmcfaul commented
@nicolethoen I'm having trouble tracing how the example is trying to apply the colspans. Will update if I can find a fix before freeze.

2022-06-16 17:14 UTC, nicolethoen approved these changes

2022-06-17 14:27 UTC, tlabaj approved these changes

2022-06-17 14:27 UTC, merged

2022-06-17 14:54 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.61.12
 - @patternfly/react-catalog-view-extension@4.73.12
 - @patternfly/react-charts@6.75.12
 - @patternfly/react-code-editor@4.63.12
 - @patternfly/react-console@4.73.12
 - @patternfly/react-core@4.222.12
 - @patternfly/react-docs@5.83.12
 - @patternfly/react-icons@4.73.12
 - @patternfly/react-inline-edit-extension@4.67.12
 - demo-app-ts@4.182.12
 - @patternfly/react-integration@4.184.12
 - @patternfly/react-log-viewer@4.67.12
 - @patternfly/react-styles@4.72.12
 - @patternfly/react-table@4.91.12
 - @patternfly/react-tokens@4.74.12
 - @patternfly/react-topology@4.69.12
 - @patternfly/react-virtualized-extension@4.69.12
 - transformer-cjs-imports@4.60.12

Thanks for your contribution! :tada: