Iss7312
patternfly/patternfly-react pull request #7658
Opened 2022-07-06 15:09 UTC by jenny-s51

**What**: Closes #7312 

Added some work here that applies towards #7657 - this demo now supports bulk select, and the ability to delete cards. 

However in order to fully align this demo with core, a lot of additional logic/functionality is required, which is out of scope of the original issue to use the new raised variant for the card. For that reason I opened #7657

**Additional issues**: #7657

2022-07-11 20:32 UTC, jenny-s51 commented on packages/react-core/src/demos/PrimaryDetail.md
> +    this.deleteItem = item => _event => {
Nice catch @nicolethoen - thank you! Updated.

2022-07-12 11:30 UTC, nicolethoen approved these changes
LGTM!

2022-07-15 10:39 UTC, nicolethoen commented
@mmenestr this is the direct URL to the updated demo: https://patternfly-react-pr-7658.surge.sh/demos/primary-detail/react-demos/primary-detail-card-view/

2022-07-21 12:44 UTC, thatblindgeye reviewed
Overall looks good! A couple of things I'm noticing (which these may be better as followup issues) are:

- When clicking anywhere in the card, the drawer gets toggled open. This includes clicking the checkbox or kebab toggle. The expectation I'd have is clicking either of those would only trigger those specific elements, and clicking anywhere else in the card would select it.
- This I can create a spinoff issue for since it might require tweaking the logic of selectable cards a bit, but should we have the card drawers closable in ways other than the "close" button? When navigating via keyboard, once I click a card to open the drawer it remains open and blocks other cards completely, and you'd have to tab through every single card to get to the close button.

@jenny-s51 what do you think?

2022-07-21 17:55 UTC, jenny-s51 reviewed
Thank you for your awesome feedback @thatblindgeye !! 

> * When clicking anywhere in the card, the drawer gets toggled open. This includes clicking the checkbox or kebab toggle. The expectation I'd have is clicking either of those would only trigger those specific elements, and clicking anywhere else in the card would select it.

Definitely makes sense to have the checkbox, drawer toggle, and kebab toggles all behave independently! I've updated the code to separate all the different toggling behaviors you listed here. 

> * This I can create a spinoff issue for since it might require tweaking the logic of selectable cards a bit, but should we have the card drawers closable in ways other than the "close" button? When navigating via keyboard, once I click a card to open the drawer it remains open and blocks other cards completely, and you'd have to tab through every single card to get to the close button.

Nice catch!! I fixed this by making sure the drawer closes if a user selects the card a second time either via mouse or keyboard. Seems like a good, working solution for this! WDYT @thatblindgeye ?

2022-07-21 18:57 UTC, thatblindgeye requested changes
The latest updates work great @jenny-s51! Just had one minor addition noted below based on these updates.

2022-07-21 18:57 UTC, thatblindgeye commented on packages/react-core/src/demos/PrimaryDetail.md
>        }
Updating the `activeCard` state to `null` when the drawer gets closed when clicking a selected card again, to remove the card styling/uncheck the hidden radio button.

2022-07-21 18:57 UTC, thatblindgeye commented on packages/react-core/src/demos/PrimaryDetail.md
> +        }
Same thing here

2022-07-21 20:48 UTC, jenny-s51 reviewed
Thank you @thatblindgeye ! Updated 👍

2022-07-25 15:19 UTC, thatblindgeye approved these changes
🎉 Awesome job on this demo!

2022-07-25 18:41 UTC, merged