chore(Charts): clean up a11y violations in docs
patternfly/patternfly-react pull request #7682
Opened 2022-07-11 19:25 UTC by nicolethoen

**What**: Closes #7675 

Duplicate IDs in axis labels and/or legend labels
- Stack chart
- Tooltip chart
- Scatter chart
- Line chart
- Bullet chart
- Area chart
- Legend chart
- Bar chart
- Pie chart
- Donut chart

Duplicate id due to reused example names:
- Donut utilization chart

SVGs need accessible text
- Tooltip chart
- Sparkline chart
- Bullet chart

Legend chart examples - interactive controls cannot be nested. Fixed this by updating the ChartContainer's rendered svg's role from 'img' to 'group'

2022-07-12 13:25 UTC, dlabrecq requested changes

2022-07-12 13:36 UTC, dlabrecq requested changes

2022-07-12 13:36 UTC, dlabrecq commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartContainer role="group" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
This needs to be `ChartVoronoiContainer` to show tooltip values related to x and y coordinates.

In addition, I envisioned adding `role="group"` as a default.

2022-07-12 13:36 UTC, dlabrecq commented on packages/react-charts/src/components/ChartAxis/ChartAxis.tsx
> +      tickLabelComponent={<VictoryLabel id={axisLabelId} />}
We would want to use our own ChartLabel here. 

We also need to clone the given `tickLabelComponent` here, so we don't override a devs component properties.

2022-07-12 13:46 UTC, dlabrecq requested changes

2022-07-12 13:46 UTC, dlabrecq commented on packages/react-charts/src/components/ChartPoint/ChartPoint.test.tsx
> +      <ChartLegend dataComponent={<ChartPoint />} titleComponent={<ChartLabel id="test" />} />
This is another case where we must clone the `titleComponent`, so we don't override the dev's given properties

2022-07-12 13:46 UTC, dlabrecq commented on packages/react-charts/src/components/ChartPoint/ChartPoint.test.tsx
> +      titleComponent={<ChartLabel id="test2" />}
Same here. We must clone the `titleComponent`, so we don't override the dev's given properties

2022-07-12 14:02 UTC, dlabrecq commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartContainer role="group" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
It appears that Victory uses role="img" as the default to describe the SVG element

2022-07-14 13:39 UTC, thatblindgeye approved these changes
Looks good! I did note an issue I noticed below, but because what I noted *might* involve more investigation/possible larger changes, I wouldn't block over it.

2022-07-15 10:50 UTC, nicolethoen commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartVoronoiContainer role="figure" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
hm - yeah, @thatblindgeye do you mind opening an issue to address this? It's helpful and overall, charts could use a bit more a11y evaluation. I think it's just a bit out of scope here.

Once you do that, I think you or @dlabrecq could probably merge this

2022-07-15 20:27 UTC, dlabrecq commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartVoronoiContainer role="figure" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
We have a couple a11y investigation issues open already for charts. In fact, our team was responsible for exposing the role attributes in the Victory upstream. There is some follow up work to add default roles, but SVGs will always have a11y quirks.

2022-07-18 15:48 UTC, dlabrecq commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartVoronoiContainer role="figure" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
Not sure if this is helpful, but Christy suggested we might use `role=table`.
See https://github.com/patternfly/patternfly-react/issues/4135#issuecomment-625441882

VO announces the `desc` and `title` for `<svg role="table"`, but it identifies the chart as a table with zero rows. Screen readers won't read nested elements under `<svg role="img"`.

2022-07-18 17:21 UTC, dlabrecq commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartVoronoiContainer role="figure" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
FYI, I tried using `containerId`, but didn't seem to work with `aria-describedby` and `aria-labelledby`. Using `aria-label` seemed to work a little better, but VO didn't announce `aria-details`.

```
<figure aria-describedby="chart" aria-labelledby="chart">
  <Chart
    ariaDesc="This is a descripton"
    ariaTitle="This is a title"
    containerComponent={<ChartContainer containerId="chart" role="figure" />}
  >
  ...
</figure
```

2022-07-19 00:08 UTC, dlabrecq commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartVoronoiContainer role="figure" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
@nicolethoen This seems to work fairly well.

![Screen Shot 2022-07-18 at 7 56 56 PM](https://user-images.githubusercontent.com/17481322/179636680-17a6c8a2-9b28-4e1f-8651-3eefc082ab4a.png)

Note that I'm using `containerId="chart"` with `ChartVoronoiContainer`. This allows me to add aria-`describedby="chart-desc"` and `aria-labelledby="chart-title"` to the outermost `div` tag.

VO now reads this chart's description and title, similar to `role=img`. Still using `role="figure"` with `ChartVoronoiContainer`, so VO can read each link.

VO recording:
https://user-images.githubusercontent.com/17481322/179636793-4daa6a16-615a-4163-adc8-5af8aff109b1.mov

2022-07-19 12:17 UTC, nicolethoen commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartVoronoiContainer role="figure" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
nice!

2022-07-19 13:03 UTC, thatblindgeye commented on packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
> +          containerComponent={<ChartVoronoiContainer role="figure" labels={({ datum }) => `${datum.name}: ${datum.y}`} constrainToVisibleArea />}
>nice!

Echoing this. The updates made by Nicole + the tweaks shown in the above comment make for a definite improvement of the current behavior.

2022-07-19 14:23 UTC, dlabrecq approved these changes
LGTM

2022-07-19 14:36 UTC, thatblindgeye approved these changes

2022-07-19 15:19 UTC, merged