docs(ProgressStepper): add examples to show alignment modifiers working together
patternfly/patternfly-react pull request #7727
Opened 2022-07-21 15:25 UTC by kmcfaul

**What**: Closes #7617

- Adds new examples showing vertical and center alignment working together for basic and compact progress stepper.
- Converts examples to TSX.
- Also adjusts examples to cut down on page length (combining the 3 separate alignment examples into a single alignment example with flags for basic and a single compact example for compact). If we want these use cases (vertical only, center only, vertical and center together) to be separate examples I still have them stashed locally and can adjust them back.

2022-07-25 20:58 UTC, mcarrano approved these changes
This looks great @nicolethoen !

2022-07-26 13:02 UTC, mattnolting approved these changes
Looks fantastic, nice work! 👍

2022-07-26 13:21 UTC, thatblindgeye requested changes
Looks great! For the following files listed, they're missing the `export....: React.FunctionComponent` syntax:

- ProgressStepperBasic
- ProgressStepperBasicFailure
- ProgressStepperBasicIssue
- ProgressStepperBasicWithDescription
- ProgressStepperIcons

2022-07-26 13:21 UTC, thatblindgeye commented on packages/react-core/src/components/ProgressStepper/examples/ProgressStepperHelpPopover.tsx
> +export const PopoverProgressStep = () => (
```suggestion
export const ProgressStepperHelpPopover: React.FunctionComponent = () => (
```

2022-07-26 13:21 UTC, thatblindgeye commented on packages/react-core/src/components/ProgressStepper/examples/ProgressStepperIcons.tsx
> +<ProgressStepper>
As a nitpick in addition to adding the `export...`, naming the file/export as "ProgressStepperCustomIcons" is slightly more fitting

2022-07-26 16:32 UTC, thatblindgeye approved these changes

2022-07-26 17:53 UTC, nicolethoen requested changes

2022-07-26 17:53 UTC, nicolethoen commented on packages/react-core/src/components/ProgressStepper/examples/ProgressStepperBasic.tsx
> +    <ProgressStep variant="info" isCurrent id="basic-step2" titleId="basic-step2-title" aria-label="step with info">
The ids in this example need to be unique - could they reference alignment rather than basic?

2022-07-27 13:54 UTC, nicolethoen approved these changes

2022-07-27 14:04 UTC, merged

2022-07-27 14:41 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.66.2
 - @patternfly/react-catalog-view-extension@4.78.2
 - @patternfly/react-charts@6.80.2
 - @patternfly/react-code-editor@4.68.2
 - @patternfly/react-console@4.78.2
 - @patternfly/react-core@4.227.2
 - @patternfly/react-docs@5.88.2
 - @patternfly/react-icons@4.78.2
 - @patternfly/react-inline-edit-extension@4.72.2
 - demo-app-ts@4.187.2
 - @patternfly/react-integration@4.189.2
 - @patternfly/react-log-viewer@4.72.2
 - @patternfly/react-styles@4.77.2
 - @patternfly/react-table@4.96.2
 - @patternfly/react-tokens@4.79.2
 - @patternfly/react-topology@4.74.2
 - @patternfly/react-virtualized-extension@4.74.2
 - transformer-cjs-imports@4.65.2

Thanks for your contribution! :tada: