chore(Popover) convert examples to TypeScript
patternfly/patternfly-react pull request #7770
Opened 2022-07-28 14:33 UTC by Dominik-Petrik

**What**: Closes #7751

2022-07-28 14:39 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7770.surge.sh

2022-07-29 12:38 UTC, nicolethoen commented
It looks like the build is failing because you have an extra `"` before an `isBeta` flag on one of your examples?
either that or it's unable to parse the `isBeta` before the file name.

2022-08-01 12:46 UTC, tompsota commented
> It looks like the build is failing because you have an extra `"` before an `isBeta` flag on one of your examples? either that or it's unable to parse the `isBeta` before the file name.

Seems like there is missing `"` on L61, the `isBeta` flag before filename shouldn't cause any problems. Although it is better to follow this syntax: `ts file='<<filename>>' isBeta`

2022-08-01 16:25 UTC, thatblindgeye requested changes
This is looking good! Had some comments below for changes

2022-08-01 16:25 UTC, thatblindgeye commented on packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx
> +          id="check-3"
Just to avoid possible duplicate ID's in the future:

```suggestion
          id="popover-advanced-check-1"
```

2022-08-01 16:25 UTC, thatblindgeye commented on packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx
> +          id="check-4"
Same as above:

```suggestion
          id="popover-advanced-check-2"
```

2022-08-01 16:25 UTC, thatblindgeye commented on packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx
> +          appendTo={() => document.body}
I don't think we need this `appendTo` line, it should be appending to the document body by default.

2022-08-01 16:25 UTC, thatblindgeye commented on packages/react-core/src/components/Popover/examples/PopoverWithIconInTheTitle.tsx
> +      aria-label="Alert popover"
```suggestion
      aria-label="Popover with icon in the title example"
```

2022-08-03 12:49 UTC, tompsota requested changes
Good job! :) Just have some comments.

2022-08-03 12:49 UTC, tompsota commented on packages/react-core/src/components/Popover/examples/Popover.md
> +```ts isBeta file="./PopoverWithIconInTheTitle
In addition to the previous comment, you are missing also file extension

2022-08-03 12:49 UTC, tompsota commented on packages/react-core/src/components/Popover/examples/PopoverAlert.tsx
> +    <div>
You can use `<React.Fragment>` (or `<>`) instead of wrapper `<div>`

2022-08-15 16:33 UTC, thatblindgeye approved these changes
🎉

2022-08-16 10:07 UTC, tompsota requested changes
One last nit:

2022-08-16 10:07 UTC, tompsota commented on packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx
> +    <div>
```suggestion
    <>
```

2022-08-16 10:07 UTC, tompsota commented on packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx
> +    </div>
```suggestion
    </>
```

2022-08-16 11:07 UTC, Dominik-Petrik commented on packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx
> +    </div>
On it!

2022-08-16 11:59 UTC, tompsota approved these changes
Thanks!

2022-08-18 13:42 UTC, tlabaj approved these changes
LGTM

2022-08-18 13:42 UTC, merged