fix(Select): apply aria-describedby to correct element
patternfly/patternfly-react pull request #7790
Opened 2022-08-04 13:55 UTC by tompsota

**What**: Closes #7476

2022-08-08 16:48 UTC, thatblindgeye requested changes
🎉 In addition to removing the `{...(ariaDescribedby &&...` from line 1291, we could also remove it from line 1270 as well (within `popperContainer`) since that shouldn't really have the attribute either.

2022-08-16 12:12 UTC, thatblindgeye approved these changes
🎉

2022-08-16 23:15 UTC, tlabaj approved these changes
lgtm

2022-08-16 23:15 UTC, merged

2022-08-16 23:51 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.71.3
 - @patternfly/react-catalog-view-extension@4.83.3
 - @patternfly/react-charts@6.85.3
 - @patternfly/react-code-editor@4.73.3
 - @patternfly/react-console@4.83.3
 - @patternfly/react-core@4.232.3
 - @patternfly/react-docs@5.93.3
 - @patternfly/react-icons@4.83.3
 - @patternfly/react-inline-edit-extension@4.77.3
 - demo-app-ts@4.192.3
 - @patternfly/react-integration@4.194.3
 - @patternfly/react-log-viewer@4.77.3
 - @patternfly/react-styles@4.82.3
 - @patternfly/react-table@4.101.3
 - @patternfly/react-tokens@4.84.3
 - @patternfly/react-topology@4.79.3
 - @patternfly/react-virtualized-extension@4.79.3
 - transformer-cjs-imports@4.70.3

Thanks for your contribution! :tada: