fix(TimePicker): clean up menuAppendTo feature
patternfly/patternfly-react pull request #7865
Opened 2022-08-18 18:20 UTC by nicolethoen

**What**: Closes #7864

2022-08-18 18:30 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7865.surge.sh

2022-08-18 20:46 UTC, tlabaj approved these changes
LGTM

2022-08-19 15:44 UTC, wise-king-sullyman requested changes
Could you add a quick test for the bug fix to make sure that we don't have a regression here in the future?

I think just something that checks that an error isn't getting thrown under the conditions that would've previously caused one would be adequate.

2022-08-19 15:55 UTC, thatblindgeye approved these changes
🎉 Definitely a great improvement! Works well in my testing with keyboard and VO as well.

2022-08-22 13:39 UTC, wise-king-sullyman approved these changes

2022-08-22 13:43 UTC, merged

2022-08-22 14:20 UTC, patternfly-build commented
Your changes have been released in: 
 - eslint-plugin-patternfly-react@4.72.1
 - @patternfly/react-catalog-view-extension@4.84.1
 - @patternfly/react-charts@6.86.1
 - @patternfly/react-code-editor@4.74.1
 - @patternfly/react-console@4.84.1
 - @patternfly/react-core@4.233.1
 - @patternfly/react-docs@5.94.1
 - @patternfly/react-icons@4.84.1
 - @patternfly/react-inline-edit-extension@4.78.1
 - demo-app-ts@4.193.1
 - @patternfly/react-integration@4.195.1
 - @patternfly/react-log-viewer@4.78.1
 - @patternfly/react-styles@4.83.1
 - @patternfly/react-table@4.102.1
 - @patternfly/react-tokens@4.85.1
 - @patternfly/react-topology@4.80.1
 - @patternfly/react-virtualized-extension@4.80.1
 - transformer-cjs-imports@4.71.1

Thanks for your contribution! :tada: