feat(OverflowMenu): allow breakpoint on container width
patternfly/patternfly-react pull request #7913
Opened 2022-08-31 14:54 UTC by thatblindgeye

**What**: Closes #7376

**Additional issues**:

2022-09-02 00:59 UTC, mcoker reviewed
Hopefully I'm reading this correctly! If not, please disregard :D It looks like  `hasBreakpointOnContainer` sets the observer on the `.pf-c-overflow-menu` parent element width? If so, it looks like in order for that to work, the `.pf-c-overflow-menu` needs some kind of (always fluid?) width that allows it to shrink. Otherwise, by default the overflow menu is only as wide as its contents since it's an `inline-flex` box, and it won't shrink below its content width since all of the component children that are flex children are using the default `min-width: min-content` size, which keeps them and the parent from shrinking in size. So basically it never changes in size.

A use case showing an issue with that might just be the component example box. As I shrink the page down, the example container (`.ws-preview`) shrinks in size, but the overflow menu doesn't (I didn't give it a fluid width) - so watching the overflow menu's width won't help here unless it's fluid - like the example added in this PR. But you may not want it to have 100% width, like if you want to place something beside the overflow menu inline with it or whatever.

<img width="569" alt="Screen Shot 2022-09-01 at 7 42 44 PM" src="https://user-images.githubusercontent.com/35148959/188035720-d33adde6-bf5d-4160-b8b8-8ef19256fc8f.png">

<img width="602" alt="Screen Shot 2022-09-01 at 7 42 40 PM" src="https://user-images.githubusercontent.com/35148959/188035722-69dbcda1-a97e-4425-b5ba-f1da241a7105.png">

The ability to observe the overflow menu component's box may be a valid/useful use case, but I'm wondering if it makes more sense to watch the overflow menu's parent's container size (whatever wraps the overflow menu). Or even the parent's parent (grandparent) - implying the ability to specify which element's size to watch to trigger the overflow component. If you could specify the element, you could just specify the overflow menu if you have the use case shown in this new PR's example.

A use case where you might want to watch the grandparent is if the overflow menu's parent is a basic flex child, so it is only as wide as the overflow menu. Watching the grandparent flex container size might work better. Or maybe the grandparent is also a flex child, or has `display: contents;`, so you want to watch the great-grandparent, or this is part of a sub-grid layout, in which case who knows what parent you might want to watch.

2022-09-02 12:45 UTC, thatblindgeye commented
@mcoker Ah that's a good point about the flex containers! I can update things to allow specifying a specific element to observe rather than only the overflow menu itself

2022-09-06 20:18 UTC, nicolethoen requested changes
I imagine we'd want some tests to verify this behavior

2022-09-08 00:47 UTC, mcoker reviewed
Hmm... this works great, but I think I was expecting something else though I may just be a bit confused. From the original issue:

> Exactly the same as it is now but relative to container width. When I resize the container, overflowing elements are sent to the overflow menu.

I read that as relative to container width _instead of breakpoint values_ - meaning when the container width is less than the width of the overflow items, we trigger the overflow menu to show. Though the way you've done it seems perfectly valid, too.

Curious what others think. Maybe we should tag the user that opened the issue as a reviewer?

2022-09-09 14:30 UTC, tlabaj requested changes

2022-09-09 14:30 UTC, tlabaj commented on packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx
> +    const reference = this.getBreakpointRef();
should this only be called if `props.breakpointReference`

2022-09-09 14:30 UTC, tlabaj commented on packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx
> +      breakpointRef: null
can it be undefined?

2022-09-22 20:31 UTC, thatblindgeye commented
@nicolethoen @tlabaj pushed updates based on the last version of the PR, adding tests and making suggested changes.

@mcoker based on the conversation in the PR and what was discussed when we sat down to go over some local code I had wanted to show, were there any updates you wanted to see in this PR? Or would a followup issue to potentially extend the component's functionality make sense?

2022-09-23 20:26 UTC, nicolethoen approved these changes
I like it

2022-09-29 13:18 UTC, tlabaj reviewed
LGTM

2022-09-29 14:11 UTC, wise-king-sullyman reviewed
This looks solid and that demo seems really slick! I have one nit on the tests then I'd be ready to approve.

2022-09-29 14:11 UTC, wise-king-sullyman commented on packages/react-core/src/components/OverflowMenu/__tests__/OverflowMenu.test.tsx
> +    expect(resizeObserver.mock.calls[1]).toEqual(undefined);
Nit: per our discussion on Slack I think the usage of `.mock.calls` could be made a bit more readable using the `toHaveBeenNthCalledWith` matcher. This also applies to lines 68 and 81.

2022-09-29 16:07 UTC, wise-king-sullyman approved these changes
🔥

2022-09-29 18:46 UTC, tlabaj approved these changes

2022-09-29 19:34 UTC, mcoker approved these changes
This is awesome!

2022-09-29 20:41 UTC, merged