feat(checkbox): add required variant
patternfly/patternfly-react pull request #7951
Opened 2022-09-08 15:19 UTC by Dominik-Petrik

**What**: Closes #7830

2022-09-08 15:29 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7951.surge.sh

2022-09-08 17:30 UTC, mcoker reviewed
LGTM! Just a couple of comments.

2022-09-08 18:33 UTC, mattnolting commented on packages/react-core/src/components/Checkbox/Checkbox.tsx
> +                &#42;
@mcoker from what I can gather, html entities benefit content authors when using hard to find characters. As long as they're ASCII conformant, I believe either is fine.

2022-09-08 18:45 UTC, thatblindgeye requested changes
I only had the one comment below, but otherwise looks good!

2022-09-08 18:45 UTC, thatblindgeye commented on packages/react-core/src/components/Checkbox/examples/CheckboxRequired.tsx
> +    aria-label="Required input"
Since the checkbox will be linked to the visible text label, we can remove this `aria-label`.

2022-09-08 20:00 UTC, mcarrano reviewed
This looks fine from my perspective, but for some reason the Props are not showing in the preview.

2022-09-09 13:57 UTC, tlabaj commented
> This looks fine from my perspective, but for some reason the Props are not showing in the preview.

I see the props.  You may need to refresh the page.

2022-09-09 13:59 UTC, tlabaj commented on packages/react-core/src/components/Checkbox/Checkbox.tsx
> +                &#42;
@mcoker I like the idea of using constants.  That way things are consistent.
@Dominik-Petrik Can you please update to use the constant.

2022-09-09 16:05 UTC, kmcfaul reviewed
lgtm outside of the few open feedback comments

2022-09-09 20:23 UTC, tlabaj commented
@Dominik-Petrik Looks great!  I update the couple of small issues that were commented on above so we can merge this.

2022-09-09 20:30 UTC, gitdallas approved these changes

2022-09-09 20:38 UTC, thatblindgeye approved these changes

2022-09-09 20:45 UTC, mcarrano approved these changes
Looks great. Thanks @Dominik-Petrik !

2022-09-09 21:15 UTC, mcoker approved these changes
LGTM!

2022-09-09 21:23 UTC, kmcfaul approved these changes

2022-09-12 13:23 UTC, merged