docs: Remove incorrect terminology in alert group example output
patternfly/patternfly-react pull request #7956
Opened 2022-09-09 13:14 UTC by gefgu

**What**: 
The examples "Singular dynamic alert group" and "Singular dynamic alert group with overflow message" in the [alert group React examples](https://www.patternfly.org/v4/components/alert-group) output messages that say "Toast" even though these are not toast alert examples. "Toast" is removed from all success, danger, and info alert simulation messages in these examples.
Closes #7799

2022-09-09 13:23 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-7956.surge.sh

2022-09-09 14:54 UTC, thatblindgeye requested changes
This looks good so far! We also just need the AlertGroupSingularDynamicOverflow example updated similarly.

2022-09-09 17:04 UTC, gefgu commented
Thanks for the feedback. Already updated the AlertGroupSingularDynamicOverflow :)

2022-09-09 17:39 UTC, thatblindgeye approved these changes
Looks good! 🎉 Thank you for the contribution! 🙂

2022-09-19 19:59 UTC, mcarrano approved these changes
Looks good. Thanks for making this change @gefgu !

2022-09-20 14:20 UTC, nicolethoen approved these changes

2022-09-20 14:20 UTC, merged