feat(NotificationBadge): added expanded state
patternfly/patternfly-react pull request #8010
Opened 2022-09-19 18:33 UTC by thatblindgeye

**What**: Closes #7379, closes #6142 

- Added an `isExpanded` prop to the Notification Badge component
- Updated the examples so that they match Core (showing read, unread, and attention variants)
- Updated the examples so that the onClick handler updates the expanded state, rather than the variant
- Updated Notification Drawer demos to use this new expanded state 
- Reordered the props alphabetically

**Additional issues**:
N/A

2022-09-19 18:41 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8010.surge.sh

2022-09-20 14:09 UTC, nicolethoen approved these changes
Looks good to me!

2022-09-21 23:31 UTC, mcoker approved these changes
LGTM! One comment about the `aria-label`.

And this is pre-existing, but if it's an easy fix, core shows an attention notification badge if there is an unread attention notification in the notification drawer - https://www.patternfly.org/v4/components/notification-drawer/html-demos#expanded-attention. @mcarrano can confirm if that is the intended use and if these should match.

2022-09-21 23:31 UTC, mcoker commented on packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeWithCount.tsx
> +        aria-label="Notification badge with count and read variant"
Just a nit but I might name these more consistently between the two examples. Something like

Basic - `aria-label="Notification badge with [read/unread/attention] variant"`
Count - `aria-label="Notification badge with count and [read/unread/attention] variant"`

or

Basic - `aria-label="[Read/Unread/Attention] notification badge"`
Count - `aria-label="[Read/Unread/Attention] notification badge with count"`

2022-09-23 19:21 UTC, tlabaj requested changes

2022-09-23 19:21 UTC, tlabaj commented on packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx
> +  /** Flag for indicating whether the notification badge is expanded. */
I would update this comment to say it applies expanded styling to the badge.  The badge is not actually expanded here.  It was a little unclear to me at first to what the prop was doing.

2022-09-23 19:26 UTC, tlabaj commented
@thatblindgeye and @mcoker shouldn't there be a new "expanded". example,  Or at least a way to switch the basic? example?

2022-09-27 16:39 UTC, thatblindgeye commented
@tlabaj @mcarrano it might depend whether we intend for the Notification Badge to ever be used without the Notification Drawer (maybe instead of a drawer, the badge links to a "notifications" page or something)? I could either add in something like:

`The following example.... The isExpanded property is also passed in to visually indicate that the badge is expanded, for use-cases as seen in our [notification drawer](...) demos.`

Or if we intend for the badge to be used independently of the drawer, I could revert the current examples a bit and add a new one for this new prop (with similar verbiage as above).

2022-09-27 18:30 UTC, mcarrano commented
@thatblindgeye I think that the text you proposed would be helpful to convey what's going on here.

It's a good question whether this might ever be used for something other than the drawer. To that extent I wonder if calling this an "expanded" state is a bit misleading. It's really more like a selected or active state that can be more generally used to reflect state. @mcoker what do you think of that? I think "expanded" came from our discussion of the need to visually reflect state of masthead items, but is this the right semantic?

2022-09-27 19:46 UTC, mcoker commented
@mcarrano good question... I don't see why it would necessarily need to be tied to the notification drawer. It's basically just a plain variant button with unique background/text color. It could be used as tabs or something, too, or maybe some sort of filter.

It's worth noting that besides the naming being more flexible between selected and expanded, there is a bit of a code difference between the two, in that at a minimum, an expanded toggle would have `aria-expanded="true"` and a selected toggle, at least in some circumstances, would not. So it may be useful to have both - or maybe that's confusing? I'm curious @thatblindgeye's thoughts on that.

2022-09-27 20:18 UTC, thatblindgeye commented
I suppose in the case of the badge being selected in a tab-like scenario, another prop could be introduced to apply the same styling (or apply "selected" styling that is default the same), but apply possibly different aria attributes. That would I assume require a Core PR first to add styling for a selected (or whichever, there may be a better name for that sort of badge) modifier.

I think expanded works for this particular use-case of a badge causing a drawer to open or close. If we anticipate (or if we just want to offer the option for) a notification badge being used outside of a drawer, I can update this PR so that:

1. The current examples are somewhat reverted, basically just removing the `isExpanded` prop
2. A new example gets added, describing when to use the isExpanded prop and linking to notification drawer demos

2022-09-28 12:46 UTC, thatblindgeye commented
@tlabaj @mcarrano Updated the example descriptions to mention the isExpanded prop. Also updated the prop description to mention the expanded styling as well as it setting the `aria-expanded` attribute.

2022-09-28 15:16 UTC, mcarrano reviewed
@thatblindgeye this looks great. However I'm wondering if this statement should say something other than the badge is expanded:

The isExpanded property is also passed in to indicate that the badge is expanded, for use-cases as seen in our [notification drawer react demos](https://patternfly-react-pr-8010.surge.sh/components/notification-drawer/react-demos).

Would it be more correct to say "indicate the drawer is expanded?"

2022-09-28 16:32 UTC, thatblindgeye commented
> Would it be more correct to say "indicate the drawer is expanded?"

@mcarrano  It's definitely a little trickier here since the badge *does* get the aria-expanded attribute set based on this prop, but it also isn't technically the badge that is expanding.

Maybe, "...set the aria-expanded attribute on the notification badge and to indicate that a notification drawer is expanded"?

2022-09-28 17:49 UTC, mcarrano commented
How about, "...set the aria-expanded attribute and apply visual styling on the notification badge and to indicate that a notification drawer is expanded"?

2022-09-29 13:52 UTC, mcarrano approved these changes
Looks great, Thanks for making that update @thatblindgeye .

2022-09-29 13:55 UTC, merged