Fix(Contributing Guide): Outline links not working
patternfly/patternfly-react pull request #8032
Opened 2022-09-21 18:48 UTC by gefgu

**What**: These 3 links are not working in the [contribution guidelines](https://github.com/patternfly/patternfly-react/blob/main/CONTRIBUTING.md).
![screenshot](https://user-images.githubusercontent.com/53129852/191585983-c06824e1-7cb4-41f7-8f33-35faf713f1f6.png)

2022-09-21 18:58 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8032.surge.sh

2022-09-21 20:24 UTC, tlabaj commented
@gefgu can you please link an issue to this PR for tracking purposes.  thanks

2022-09-22 14:40 UTC, thatblindgeye requested changes
Thanks for catching this! In addition to the above comment and my own change request below, a more fitting commit type in your commit message could be `docs` instead of `fix`. The comment at https://github.com/patternfly/patternfly/pull/5102#pullrequestreview-1112868383 actually goes into some difference between them.

2022-09-22 14:40 UTC, thatblindgeye commented on CONTRIBUTING.md
> +  - [How do I lose maintainers status?](#how-do-i-lose-maintainers-status?)
We would also need to remove the trailing question marks `?` at the end of the URLs here.

2022-09-22 17:34 UTC, gefgu commented
@thatblindgeye thanks for guiding me on how to improve my commit messages. Already implemented the changes :)

2022-09-22 18:57 UTC, thatblindgeye approved these changes

2022-09-23 19:41 UTC, tlabaj approved these changes

2022-09-23 19:42 UTC, merged