chore(table): update column management demo with new data
patternfly/patternfly-react pull request #8044
Opened 2022-09-22 19:59 UTC by jenny-s51

**What**: Closes #7991 

Bonus updates!!:
- Converted to function component with hooks 🪝
- Converted to use `TableComposable` which is the PF recommendation over legacy table 
- Moved demo to standalone file which is the convention we are following for other PF components/demos
- Cleaned up the demo! Now 500 lines shorter/cleaner 🧼

**Demo link for convenience:** [waiting for docs build to complete]

2022-09-22 20:10 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8044.surge.sh

2022-09-23 18:45 UTC, mcarrano commented
@jenny-s51 This looks good to me. But I'll defer to @mmenestr as I believe she worked on the original design.

2022-09-23 20:07 UTC, mmenestr commented
This looks good as far as the manage column function goes! I would just add a Page header to the page because it looks a bit weird to just have breadcrumbs

2022-09-23 20:23 UTC, jenny-s51 reviewed
Thanks @mmenestr , nice catch! Updated the demo to include a main section.

2022-09-26 13:31 UTC, nicolethoen reviewed
This looks great! Wow!

It may benefit consumers to include a few more comments within the demo code to guide a consumer through the features/considerations made to implement the various bits. I found that when I read 'setFilteredRows' I began looking for the implementation of the 'Name' select filter. But that's not what 'setFilteredRows' is referring to. So, clarity, even just with additional comments, might be helpful in the `fitlerData` function - and maybe also to clearly separate the pagination logic from the column management logic in the code?

I'm curious if there should be a way to manage the columns in the mobile/smaller viewport screen widths? I'm not sure where the 'manage columns' button would go.

2022-09-26 13:36 UTC, nicolethoen commented
I also spent some time wondering if there was a better way to control column widths so that the widths dont jump around as you paginate. I'm not sure, because since the columns obviously change as they are being managed.

My only instinct is to use the width prop on columns that might change size so they are always wide enough to fit the longest content (in our case) - specifically, that means 'servers', 'status', and 'location' i think. Not sure if that would work?

2022-09-26 15:51 UTC, mmenestr approved these changes

2022-09-27 13:01 UTC, jenny-s51 reviewed
Thank you @nicolethoen for your awesome suggestions!! The additional documentation will definitely be super helpful for consumers and the static column widths were a great idea 🙌

2022-09-28 19:17 UTC, thatblindgeye requested changes
Awesome work on this! 🎉 I just had a few really quick changes below. Also had the following comments:

- When viewing the demo, two instances of "Loading..." text are being rendered:
    ![Double loading text in demo](https://user-images.githubusercontent.com/70952936/192867817-8f69672b-cff4-4928-b627-041a3899bb05.png)

    If I stop the page load in time, this is what it looks like in my dev tools:

    ![double loading text dev tools](https://user-images.githubusercontent.com/70952936/192868091-db298f6d-c525-412c-af0c-a9e97faf85f9.png)

    Are you by chance seeing this at all?
- If this has already been brought up just let me know (pretty sure this topic was mentioned somewhat recently, but can't place it..), but the column widths end up truncating when there may not be a need to. If I update the table so only the URL column is visible, it still truncates despite there being plenty of space. Not necessarily a blocker, though, since it could be out of scope/something that would more be up to the consumer to handle.

2022-09-28 19:17 UTC, thatblindgeye commented on packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
> +  matchSelectedColumnNameToAttr = name => {
```suggestion
  const matchSelectedColumnNameToAttr = name => {
```

2022-09-28 19:17 UTC, thatblindgeye commented on packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
> +  unfilterAllData = () => {
```suggestion
  const unfilterAllData = () => {
```

2022-09-28 19:17 UTC, thatblindgeye commented on packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
> +  handleChange = (checked, event) => {
```suggestion
  const handleChange = (checked, event) => {
```

2022-09-28 19:17 UTC, thatblindgeye commented on packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
> +  renderModal = () => {
```suggestion
  const renderModal = () => {
```

2022-09-29 13:34 UTC, nicolethoen commented
@thatblindgeye @jenny-s51 The issue with an extra `Loading...` has been reported :)
https://github.com/patternfly/patternfly-org/issues/3209

2022-09-29 13:39 UTC, jenny-s51 reviewed
Thank you for your review and feedback @thatblindgeye ! Applied your code suggestions 👍

2022-09-29 15:27 UTC, nicolethoen approved these changes

2022-09-29 15:56 UTC, thatblindgeye approved these changes
Looks good! Awesome work again on this demo!

2022-09-30 13:12 UTC, tlabaj approved these changes
LGTM

2022-09-30 13:12 UTC, merged

2022-09-30 13:36 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.92.20
 - @patternfly/react-code-editor@4.82.20
 - @patternfly/react-console@4.92.20
 - @patternfly/react-core@4.246.0
 - @patternfly/react-docs@5.102.23
 - @patternfly/react-inline-edit-extension@4.86.20
 - demo-app-ts@4.202.1
 - @patternfly/react-log-viewer@4.87.15
 - @patternfly/react-table@4.110.20
 - @patternfly/react-topology@4.88.20
 - @patternfly/react-virtualized-extension@4.88.20

Thanks for your contribution! :tada: