feat: add ouia support to dropdown next
patternfly/patternfly-react pull request #8135
Opened 2022-10-03 00:05 UTC by gefgu

**What**: Closes #8046

Did implementation similar to `Button` component.

2022-10-03 00:13 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8135.surge.sh

2022-10-12 17:48 UTC, jenny-s51 approved these changes

2022-10-12 18:49 UTC, tlabaj requested changes
The current dropdown component also has the OUIAId on the dropdownItem.  Can you please aadd there as well.

2022-10-21 20:21 UTC, tlabaj approved these changes
LGTM

2022-10-21 20:21 UTC, merged

2022-10-21 20:45 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.92.46
 - @patternfly/react-code-editor@4.82.46
 - @patternfly/react-console@4.92.46
 - @patternfly/react-core@4.255.0
 - @patternfly/react-docs@5.102.53
 - @patternfly/react-inline-edit-extension@4.86.47
 - demo-app-ts@4.204.1
 - @patternfly/react-log-viewer@4.87.41
 - @patternfly/react-table@4.111.24
 - @patternfly/react-topology@4.90.1
 - @patternfly/react-virtualized-extension@4.88.46

Thanks for your contribution! :tada: