TextArea test revamp
patternfly/patternfly-react pull request #8150
Opened 2022-10-04 14:39 UTC by Dominik-Petrik

**What**: Closes #7976

2022-10-04 14:50 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8150.surge.sh

2022-10-11 15:29 UTC, wise-king-sullyman requested changes
Good work on this so far! As we discussed earlier today I'd like to see some tests added for default behavior related to each prop and the following specific items addressed:

2022-10-13 20:43 UTC, wise-king-sullyman commented on packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx
> +  const user = userEvent.setup();
Oh also I think you missed this comment on your last round of changes @Dominik-Petrik

2022-10-14 13:48 UTC, wise-king-sullyman approved these changes
🚀

2022-10-14 14:19 UTC, nicolethoen approved these changes

2022-10-14 14:20 UTC, merged

2022-10-14 14:45 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-catalog-view-extension@4.92.37
 - @patternfly/react-code-editor@4.82.37
 - @patternfly/react-console@4.92.37
 - @patternfly/react-core@4.251.3
 - @patternfly/react-docs@5.102.44
 - @patternfly/react-inline-edit-extension@4.86.38
 - demo-app-ts@4.202.18
 - @patternfly/react-log-viewer@4.87.32
 - @patternfly/react-table@4.111.15
 - @patternfly/react-topology@4.88.37
 - @patternfly/react-virtualized-extension@4.88.37

Thanks for your contribution! :tada: