chore(Banner): update tests to new react testing library standards
patternfly/patternfly-react pull request #8160
Opened 2022-10-05 03:16 UTC by samuelatefah

**What**: Closes #8094 

**Additional issues**:

2022-10-05 03:24 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8160.surge.sh

2022-10-05 20:03 UTC, wise-king-sullyman requested changes
Really great work! Two small comments (as discussed in our meeting) then it should be good.

2022-10-05 20:03 UTC, wise-king-sullyman commented on packages/react-core/src/components/Banner/__tests__/Banner.test.tsx
> +test('Renders screenReaderText as "default banner" by default', () => {
Can you add one more test for that generated screen reader text behavior?

2022-10-05 20:38 UTC, wise-king-sullyman requested changes

2022-10-05 20:38 UTC, wise-king-sullyman commented on packages/react-core/src/components/Banner/__tests__/Banner.test.tsx
> +  expect(screen.getByText('Custom screen reader text')).toHaveTextContent(/^Custom screen reader text$/);
Can you change the matcher here to `toBeInTheDocument` rather than `toHaveTextContent` since the text content is now being used in the query?

2022-10-05 20:38 UTC, wise-king-sullyman commented on packages/react-core/src/components/Banner/__tests__/Banner.test.tsx
> +
Also can you add a test to make sure the `screenReaderText` has the `pf-u-screen-reader` class? Missed that on my first review.

2022-10-06 17:44 UTC, wise-king-sullyman approved these changes
🔥

2022-10-12 13:30 UTC, tlabaj approved these changes
LGTM

2022-10-12 13:30 UTC, merged