chore(Slider): converted examples to typescript
patternfly/patternfly-react pull request #8164
Opened 2022-10-05 17:16 UTC by andyyvo

**What**: Closes #8063 

**Additional issues**:

2022-10-05 17:35 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8164.surge.sh

2022-11-17 20:02 UTC, thatblindgeye requested changes

2022-11-17 20:02 UTC, thatblindgeye commented on packages/react-core/src/components/Slider/examples/SliderDiscrete.tsx
> +        name="value1"
This `name` prop could be removed since it's only being applied to a `<div>`

2023-01-05 14:07 UTC, thatblindgeye requested changes

2023-01-05 14:07 UTC, thatblindgeye commented on packages/react-core/src/components/Slider/examples/SliderActions.tsx
> +      <LockIcon />
There's another lint error  for line 56, but the icon to render just needs to be a based on isDisabled for LockIcon and LockOpenIcon.

2023-01-09 21:04 UTC, thatblindgeye approved these changes

2023-01-17 18:58 UTC, tlabaj approved these changes
LGTM

2023-01-17 18:58 UTC, merged