chore(docs): Release notes 2022.13
patternfly/patternfly-react pull request #8168
Opened 2022-10-05 18:26 UTC by tlabaj

**What**: Closes #

**Additional issues**:

2022-10-05 21:41 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8168.surge.sh

2022-10-06 13:52 UTC, evwilkin commented
@tlabaj it looks like one of the integration tests failed for this PR
```
<testcase name="Tab Demo Test Adjusts tabs showing on resize" time="0.0000" classname="Adjusts tabs showing on resize">
    <failure
        message="Timed out retrying after 4000ms: Expected to find content: &apos;Tab item 6&apos; but never did." 
        type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Tab item 6' but never did.
    at eval (http://localhost:3000/__cypress/tests?p=cypress/integration/tabshorizontaloverflow.spec.ts:142:37)
at Array.forEach (<anonymous>)
    at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/tabshorizontaloverflow.spec.ts:141:96)]]>
    </failure>
</testcase>
```

2022-10-06 17:25 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +Added prop `initialIndexWidth` to support custom line number column size ([#7939](https://github.com/patternfly/patternfly-react/pull/7939))
```suggestion
- Added prop `initialIndexWidth` to support custom line number column size ([#7939](https://github.com/patternfly/patternfly-react/pull/7939))
```

2022-10-06 17:25 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Added content to dropdown examples. ([#7784](https://github.com/patternfly/patternfly-react/pull/7784))
```suggestion
  - Added content to dropdown examples ([#7784](https://github.com/patternfly/patternfly-react/pull/7784))
```

2022-10-06 17:26 UTC, evwilkin requested changes
Missing bullet point under Log viewer section, and added a note to delete a period for consistency.

2022-10-06 17:55 UTC, evwilkin approved these changes
LGTM

2022-10-11 14:36 UTC, nicolethoen approved these changes

2022-10-11 14:36 UTC, merged

2022-10-11 15:01 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.102.33

Thanks for your contribution! :tada: