chore(Tooltip) remove deprecated props
patternfly/patternfly-react pull request #8231
Opened 2022-10-14 12:04 UTC by Dominik-Petrik

**What**: Closes #8096

2022-10-14 12:12 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8231.surge.sh

2022-10-14 18:27 UTC, thatblindgeye requested changes

2022-10-14 18:27 UTC, thatblindgeye commented on packages/react-integration/demo-app-ts/src/components/demos/TooltipDemo/TooltipDemo.tsx
>          </Tooltip>
This tooltip should be able to be removed completely, as the test file doesn't look to be testing anything with it.

2022-10-20 12:16 UTC, thatblindgeye approved these changes

2022-10-20 19:42 UTC, tlabaj approved these changes
lgtm

2022-10-20 19:42 UTC, merged