chore(docs): Added release notes 2022.14
patternfly/patternfly-react pull request #8301
Opened 2022-10-27 19:01 UTC by tlabaj

**What**: Closes #8300 

**Additional issues**:

2022-10-27 19:13 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8301.surge.sh

2022-10-28 01:09 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Used `codeEditorControls` and cleaned up[#7931](https://github.com/patternfly/patternfly-react/pull/7931))
Missing space & parenthesis
```suggestion
  - Used `codeEditorControls` and cleaned up ([#7931](https://github.com/patternfly/patternfly-react/pull/7931))
```

2022-10-28 01:10 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +  - Add support for forward ref and updated documentation for dropdown next. ([#8142](https://github.com/patternfly/patternfly-react/pull/8142))
Remove period
```suggestion
  - Add support for forward ref and updated documentation for dropdown next ([#8142](https://github.com/patternfly/patternfly-react/pull/8142))
```

2022-10-28 01:12 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> + Update aria-labels to include label text ([#8192](https://github.com/patternfly/patternfly-react/pull/8192))
Missing line break & bullet point, fix tense
```suggestion
  - Updated aria-labels to include label text ([#8192](https://github.com/patternfly/patternfly-react/pull/8192))
```

2022-10-28 01:13 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +   Converted examples to TypeScript ([#8137](https://github.com/patternfly/patternfly-react/pull/8137))
Line break/bullet point missing
```suggestion
  - Converted examples to TypeScript ([#8137](https://github.com/patternfly/patternfly-react/pull/8137))
```

2022-10-28 01:15 UTC, evwilkin commented on packages/react-docs/RELEASE-NOTES.md
> +-  **Chore**
Extra space looks to be breaking indentation of 3 following lines
```suggestion
- **Chore**
```

2022-10-28 01:16 UTC, evwilkin requested changes
Typo nits

2022-11-01 15:14 UTC, nicolethoen approved these changes

2022-11-01 15:15 UTC, merged