fix: forward given role to chip component
patternfly/patternfly-react pull request #8383
Opened 2022-11-22 17:37 UTC by erkanercan

I wasn't sure if we needed to forward all props like `{...this.props}`, so I only added the role into the component.

**What**: Closes #8353

**Additional issues**: -

2022-11-28 14:20 UTC, nicolethoen commented
> I wasn't sure if we needed to forward all props like `{...this.props}`

This is a good question. I feel as though we usually do want to spread the props - but the props interface extends HTMLDivElement and the chip allows for customization of the chip component. I think changing the interface definition is a breaking change, but maybe something we should do. WDYT @wise-king-sullyman ?

2022-11-28 18:42 UTC, wise-king-sullyman commented
@nicolethoen I'm generally in favor of spreading props on any component that we export, and it looks like we spread props to customizable components in at least a few places already (Card, Helper Text, and Page Section as examples) so I agree that it would make sense to do the same here.

Regarding needing a breaking change in the interface I'm honestly not sure. The Page Section interface extends HTMLDivElement as well, and that doesn't seem to cause any type errors 🤔

2022-11-28 20:46 UTC, nicolethoen commented
@erkanercan Rather than passing only the role, which is not a declared prop of the Chip, let's spread all props and see if any type issues get raised.

2022-12-14 20:03 UTC, erkanercan commented
I spread the props, can you retake a look at it? @nicolethoen

2022-12-19 15:05 UTC, nicolethoen requested changes

2022-12-19 15:05 UTC, nicolethoen commented on packages/react-core/src/components/Chip/Chip.tsx
> +        {...this.props}
let's spread the props at the end of the component. That way if the consumer wants to override the `type` or other attributes of the component, they can.

2022-12-19 15:05 UTC, nicolethoen commented on packages/react-core/src/components/Chip/Chip.tsx
> +        {...this.props}
same here, we should spread the props at the end

2023-01-06 16:41 UTC, nicolethoen commented
@erkanercan let me know if you're able to make these updates. If not, I'm happy to help move it along

2023-01-07 09:19 UTC, erkanercan commented
Hi again @nicolethoen, sorry for the late answer.
I've spread the props at the end like you mentioned, please let me know if any changes are needed and I'll do them ASAP.

2023-01-07 09:34 UTC, erkanercan commented
Hmm, it seems like when we spread the props at the end, it overrides some of the props. 
I guess we cannot accept this happening, any idea? Do you want me to give the class names manually(I also guess that is not the right method)? @nicolethoen

2023-01-09 18:38 UTC, nicolethoen commented
... hm. It's possible we need to pull out some of the props and set them more intentionally if things are getting overwritten.

oh! i think I see it. On lines 86 and 98 such as in this snippet
```
const { children, className, onClick, closeBtnAriaLabel, isReadOnly, component, ouiaId } = this.props;
```
I think we want to actually update it to the following:
```
const { children, className, onClick, closeBtnAriaLabel, isReadOnly, component, ouiaId, ...props } = this.props;
```
Then, when we spread the props, we will want to spread them with `...props` rather than `...this.props`. This will make sure that we are not overriding any of the props that you've pulled out, such as `children`, `className`, etc...

2023-01-09 20:47 UTC, erkanercan commented
> 

I didn't know about it, thanks for pointing it out! I refactored the code as you mentioned.

2023-01-10 14:59 UTC, nicolethoen approved these changes

2023-01-19 16:00 UTC, tlabaj approved these changes

2023-01-19 16:04 UTC, merged