Menu toggle 8211
patternfly/patternfly-react pull request #8410
Opened 2022-12-02 21:56 UTC by CodeDuchess

**What**: Closes #

**Additional issues**:

2022-12-02 22:02 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8410.surge.sh

2022-12-06 20:02 UTC, jenny-s51 commented on packages/react-core/src/next/components/Select/examples/Select.md
> +propComponents: ['Select', SelectGroup, 'SelectOption', 'SelectList'git, 'MenuToggle']
```suggestion
propComponents: ['Select', SelectGroup, 'SelectOption', 'SelectList', 'MenuToggle']
```

2022-12-06 20:13 UTC, jenny-s51 requested changes
Thank you for your contribution @CodeDuchess, this is a great start!

- Can we update the PR title to match the syntax as recommended in our [Developers Guide](https://docs.google.com/document/d/1z6rDcWfovN9hLym4wcDiA_L8uCwNZzXvoJ8UztXDv1w/edit#)? E.g. "fix(menu, select): added MenuToggle to props table". This format gives us a good idea of what to expect in the PR. You can do this by clicking the "Edit" button to the right of the title.

- The issue number (#8211) can be moved to the description after "Closes". This will automatically close the corresponding issue once your PR is merged.

Left some code suggestions below as well, which will likely fix your build!

2022-12-06 20:13 UTC, jenny-s51 commented on packages/react-core/src/next/components/Dropdown/examples/Dropdown.md
> +propComponents: ['Dropdown', DropdownGroup, 'DropdownItem', 'DropdownList', 'Menutoggle']
```suggestion
propComponents: ['Dropdown', DropdownGroup, 'DropdownItem', 'DropdownList', 'MenuToggle']
```

2023-01-09 18:00 UTC, nicolethoen commented
This issue might be blocked until https://github.com/patternfly/patternfly-org/issues/3331 is addressed

2023-01-11 16:26 UTC, CodeDuchess commented on packages/react-core/src/next/components/Dropdown/examples/Dropdown.md
> +propComponents: ['Dropdown', DropdownGroup, 'DropdownItem', 'DropdownList', 'Menutoggle']
@jenny-s51 Thanks so much, Jenny!

2023-01-12 20:45 UTC, CodeDuchess commented
@nicolethoen @jenny-s51 I think all necessary edits have been made. I am accustomed to GitLab, so I am still getting used to this UI. So forgive me if I have overlooked something. Thanks so much for your assistance!!

2023-01-12 21:17 UTC, jenny-s51 reviewed
Awesome, this is really close now @CodeDuchess!

If you click the "Commit Suggestion" and then "Commit changes" for each of those two comments above, it should fix your build.

Then this will be good to go once https://github.com/patternfly/patternfly-org/issues/3331 is completed and merged.

2023-01-14 18:48 UTC, CodeDuchess commented
@jenny-s51 This PR is ready for merge and publish. Thanks so much for your guidance and patience!

2023-04-03 01:45 UTC, nicolethoen commented
Closing in favor of this issue being addressed in the v5 branch in the following PRs:
https://github.com/patternfly/patternfly-react/pull/8825
https://github.com/patternfly/patternfly-react/pull/8835

2023-04-03 01:45 UTC, closed without merging