chore(Dropdown next) add testing
patternfly/patternfly-react pull request #8446
Opened 2022-12-14 18:02 UTC by Dominik-Petrik

**What**: Closes #7964  

**Additional issues**: there seems to be a bug in Dropdown. When no onOpenChange prop is passed and esc or tab key is pressed when dropdown is open, it throws an error onOpenChange is not a function. This is not optimal because onOpenChange prop is not a required prop.

2022-12-14 18:10 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8446.surge.sh

2023-01-09 22:04 UTC, wise-king-sullyman requested changes
🔥 🔥 🔥 really awesome work on this! Just a few small comments.

2023-01-23 17:00 UTC, thatblindgeye requested changes
This is looking nice! Other than Austin's comments, had a couple more below

2023-01-31 14:50 UTC, tlabaj commented
Can you make the base of you PR "v5" instead of "main" please.  Main is now feature frozen.

2023-01-31 15:59 UTC, closed without merging