fix: aria label added to ungrouped simple list
patternfly/patternfly-react pull request #8507
Opened 2023-01-07 09:31 UTC by erkanercan

**What**: Closes #8249

**Additional issues**:

2023-01-07 09:41 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8507.surge.sh

2023-01-09 13:25 UTC, thatblindgeye requested changes
Thanks for making the update! Just one suggestion below

2023-01-09 20:57 UTC, erkanercan commented on packages/react-core/src/components/SimpleList/SimpleList.tsx
> +          {!isGrouped && <ul aria-label={props['aria-label']}>{children}</ul>}
Refactored it to the pointed-out version. Also added a description for it.

2023-01-10 02:24 UTC, nicolethoen approved these changes

2023-01-11 13:46 UTC, thatblindgeye approved these changes

2023-01-11 14:33 UTC, merged

2023-01-11 14:56 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@4.82.92
 - @patternfly/react-console@4.93.26
 - @patternfly/react-core@4.268.1
 - @patternfly/react-docs@5.103.36
 - @patternfly/react-inline-edit-extension@4.86.96
 - demo-app-ts@4.206.4
 - @patternfly/react-log-viewer@4.87.87
 - @patternfly/react-table@4.112.17
 - @patternfly/react-topology@4.91.4
 - @patternfly/react-virtualized-extension@4.88.92

Thanks for your contribution! :tada: