fix(Card):  set default component to "div" to match core
patternfly/patternfly-react pull request #8601
Opened 2023-01-25 20:22 UTC by jenny-s51

**What**: Closes #8336

2023-01-25 20:33 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8601.surge.sh

2023-01-27 19:43 UTC, thatblindgeye requested changes
Overall this looks good. Just a couple of things:

- The description for the `component` prop needs to be updated
- Can you open a followup in Org to update the a11y docs? That currently references article as the default.

2023-01-27 20:24 UTC, thatblindgeye approved these changes

2023-01-30 21:14 UTC, mcoker approved these changes
L🚀TM!

2023-02-08 16:05 UTC, tlabaj approved these changes
lgtm

2023-02-08 16:05 UTC, merged

2023-02-08 16:36 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-charts@7.0.0-alpha.4
 - @patternfly/react-code-editor@5.0.0-alpha.8
 - @patternfly/react-core@5.0.0-alpha.8
 - @patternfly/react-docs@6.0.0-alpha.9
 - @patternfly/react-table@5.0.0-alpha.8

Thanks for your contribution! :tada: