fix(Popover): updated appendTo to inline by default
patternfly/patternfly-react pull request #8621
Opened 2023-01-30 15:26 UTC by thatblindgeye

**What**: Closes #8599

**Additional issues**:

2023-01-30 15:33 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8621.surge.sh

2023-02-06 21:40 UTC, kmcfaul approved these changes

2023-02-07 01:49 UTC, nicolethoen approved these changes

2023-02-08 13:12 UTC, nicolethoen reviewed
@thatblindgeye does this need some sort of codemod/warning that there is now an extra div if appendTo was not explicitly set? 

Oh, and suddenly another thought. What if people want to put a popover on something that is inline, like a button within a span? then they cannot append inline since it would result in a div being placed in a span. I wonder if the wrapping component should also be something that the user can configure to ensure valid HTML?

2023-02-08 14:53 UTC, thatblindgeye commented
@nicolethoen I can add that in to the codemod PR I currently have up!

Regarding configuring the wrapper component, that might require further updating elements of the Popover since Popover uses `div`s internally in several places, so no matter what a div may end up within a span.

In terms of that extraneous `div`, though, would it make sense to have the logic for placing elements inline placed inside Popper instead? I tweaked the Popper logic locally and it seems like it _may_ result in the outcome we want in most cases.

2023-02-08 15:32 UTC, gitdallas requested changes
small miss

2023-02-08 15:32 UTC, gitdallas commented on packages/react-core/src/components/Popover/Popover.tsx
>    /** The element to append the popover to. Defaults to "document.body". */
```suggestion
  /** The element to append the popover to. Defaults to "inline". */
```

2023-02-08 16:11 UTC, gitdallas approved these changes

2023-02-10 19:30 UTC, nicolethoen approved these changes

2023-02-10 19:35 UTC, kmcfaul approved these changes

2023-02-10 19:35 UTC, merged