feat(misc): update onToggle params
patternfly/patternfly-react pull request #8667
Opened 2023-02-08 20:09 UTC by kmcfaul

**What**: Closes #8664

2023-02-08 20:14 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8667.surge.sh

2023-02-09 18:45 UTC, thatblindgeye requested changes

2023-02-09 19:28 UTC, kmcfaul commented on packages/react-core/src/components/Card/examples/CardWithImageAndActions.tsx
> +              toggle={<KebabToggle onToggle={(_event: any, _isOpen: boolean) => setIsOpen} />}
Will look at it. Probably just needs to be an actual invocation now instead of just the function name

2023-02-09 20:32 UTC, thatblindgeye commented on packages/react-core/src/components/Card/examples/CardWithImageAndActions.tsx
> +              toggle={<KebabToggle onToggle={(_event: any, _isOpen: boolean) => setIsOpen} />}
For the Card files that were updated, we just need to update the `!isOpen` to `isOpen` for the setIsOpen arg.

2023-02-10 16:28 UTC, wise-king-sullyman approved these changes

2023-02-10 16:39 UTC, thatblindgeye approved these changes

2023-02-10 18:34 UTC, nicolethoen commented
@kmcfaul needs a rebase, then i'll merge!

2023-02-10 19:59 UTC, nicolethoen approved these changes

2023-02-10 19:59 UTC, merged