docs(topology): Add props tables to topology docs
patternfly/patternfly-react pull request #8705
Opened 2023-02-16 18:50 UTC by jeff-phillips-18

**What**:
Closes https://github.com/patternfly/patternfly-extension-issues/issues/36

2023-02-16 18:59 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8705.surge.sh

2023-02-16 20:32 UTC, jenny-s51 requested changes
Such an exciting update!! 

Added some suggestions to align the prop descriptions - looks like the PF convention is to use "Flag" whenever describing boolean props. 

Otherwise prop tables are looking awesome @jeff-phillips-18 🎉

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/edges/DefaultEdge.tsx
> +  /** Is the user dragging the edge */
```suggestion
  /** Flag indicating if the user is dragging the edge */
```

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/edges/DefaultEdge.tsx
> +  /** Is the element selected. Part of WithSelectionProps */
```suggestion
  /** Flag indicating if the element is selected. Part of WithSelectionProps */
```

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/nodes/DefaultNode.tsx
> +  /** Is the user dragging the node */
```suggestion
  /** Flag indicating if the user is dragging the node */
```

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/nodes/DefaultNode.tsx
> +  /** Should the node's background indicate status */
```suggestion
  /** Flag indicating whether the node's background color should match the status color */
```

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/nodes/DefaultNode.tsx
> +  /** Should the node be scaled, best on hover of node at lowest scale level */
```suggestion
  /** Flag indicating the node should be scaled, best on hover of node at lowest scale level */
```

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/nodes/DefaultNode.tsx
> +  /** Should the label be shown */
```suggestion
  /** Flag to show the label */
```

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/nodes/DefaultNode.tsx
> +  /** Should the label be scaled, best on hover of node at lowest scale level */
```suggestion
  /** Flag to scale the label, best on hover of node at lowest scale level */
```

2023-02-16 20:32 UTC, jenny-s51 commented on packages/react-topology/src/components/nodes/DefaultNode.tsx
> +  /** Should the status decorator be displayed for the node */
```suggestion
  /** Flag which displays the status decorator for the node */
```

2023-02-17 00:24 UTC, jenny-s51 reviewed
Just needs a few more small edits

2023-02-17 16:53 UTC, jenny-s51 approved these changes
👍

2023-02-20 18:50 UTC, nicolethoen commented on packages/react-topology/src/components/VisualizationProvider.tsx
> +  /** The graph Controller to store in context */
lowercase controller.

2023-02-20 18:50 UTC, nicolethoen commented on packages/react-topology/src/components/VisualizationSurface.tsx
> +  /** state to be passed to the controller */
Capitalize State

2023-02-20 18:50 UTC, nicolethoen commented on packages/react-topology/src/components/nodes/DefaultNode.tsx
> +  /** Label for the node, Defaults to element.getLabel() */
update comma to period

2023-02-20 18:50 UTC, nicolethoen commented on packages/react-topology/src/components/edges/DefaultEdge.tsx
> +  /** ref to use to start the drag of the start of the edge. Part of WithSourceDragProps */
capitalize Ref here and in next comment

2023-02-22 19:45 UTC, kmcfaul approved these changes

2023-02-22 19:56 UTC, jenny-s51 approved these changes

2023-02-22 19:56 UTC, merged

2023-02-22 20:17 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@5.103.74
 - @patternfly/react-topology@4.91.35

Thanks for your contribution! :tada: