feat(Label): truncate by default
patternfly/patternfly-react pull request #8771
Opened 2023-03-02 20:23 UTC by gitdallas

**What**: Closes #8258

2023-03-02 20:32 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8771.surge.sh

2023-03-02 22:39 UTC, mcoker requested changes
Discussed offline, but left a comment about
* removing `isTruncated` 
* adding a prop for a custom truncation length

Also these conditionals should no longer be needed. We can just include the top block - the `span.pf-c-label__text` wrapping `{children}` https://github.com/patternfly/patternfly-react/blob/40e7ec37190544705918eed1fb5dfe79eff43726/packages/react-core/src/components/Label/Label.tsx#L211-L216

2023-03-02 22:39 UTC, mcoker commented on packages/react-core/src/components/Label/Label.tsx
> +  isTruncated = true,
I don't think we need this bool anymore, labels will truncate when they run out of room in their container to display their contents. You can specify a custom truncation length though, so we'll need a prop for that that takes a length and is applied to `.pf-c-label__text` via `style="--pf-c-label__text--MaxWidth: {{ // text max width prop value }}"` - you can see that here https://pf5.patternfly.org/components/label/#filled

2023-03-03 18:18 UTC, mcoker requested changes
Just a couple of test updates that I didn't catch before, otherwise LGTM!

2023-03-03 18:18 UTC, mcoker commented on packages/react-core/src/components/Label/__tests__/Label.test.tsx
> +  });
I don't think you need this anymore.

2023-03-03 18:18 UTC, mcoker commented on packages/react-core/src/components/Label/__tests__/Label.test.tsx
> +      <Label>Something very very very very very long that should be truncated</Label>
This needs a val for `textMaxWidth` to trigger the truncation.

```suggestion
      <Label textMaxWidth="16ch">Something very very very very very long that should be truncated</Label>
```

2023-03-03 18:30 UTC, mattnolting approved these changes

2023-03-03 18:30 UTC, mattnolting commented on packages/react-core/src/components/Label/__tests__/Label.test.tsx
> +      <Label>Something very very very very very long that should be truncated</Label>
I might add to the text content of this label, "textMaxWidth set to 16ch...", otherwise LGTM 👍

2023-03-03 18:44 UTC, nicolethoen reviewed
is there no default value for the `--pf-c-label__text--MaxWidth` variable? this PR is named 'truncate by default' but if it needs `textMaxWidth` prop, then it's not default?

2023-03-03 18:55 UTC, gitdallas commented
@nicolethoen - i believe it could still truncate due to other constraints limiting the size. @mcoker thoughts?

2023-03-03 18:59 UTC, gitdallas commented
@mcarrano - there is another PR to address label/chip restructure

2023-03-03 19:01 UTC, mattnolting commented
> Why are the removable and non-removable labels in the examples displaying at different heights?
> 
> ![Screenshot 2023-03-03 at 1 57 05 PM](https://user-images.githubusercontent.com/6619860/222804278-5efa9ddc-fecc-48b3-8c49-9c1af1109bce.png)

@mcarrano bc the global reset adds `padding: 0` `margin: 0` to `[class*=pf-c-]`, which applies to `button`s. There are buttons inside of those labels.

2023-03-03 19:12 UTC, thatblindgeye approved these changes
Other than a non-blocker below and other comments that have been left, only other thing is whether it'd be worth adding a label to show the default truncation without `textMaxWidth` passed in. That also isn't a blocker, though.

2023-03-03 19:12 UTC, thatblindgeye commented on packages/react-core/src/components/Label/Label.tsx
> +  /** Css property expressed in any valid length unit that is used to modify the label text's max-width, after which any additional text will be truncated */
Nit but not a blocker: Not sure if we necessarily need to mention that this is altering a CSS property:

```suggestion
  /** The max width of the label before it is truncated. */
```

Could also add, "Can be any valid CSS unit, such as '100%', '100px', or '16ch'."

2023-03-03 19:30 UTC, mcoker commented
> @nicolethoen - i believe it could still truncate due to other constraints limiting the size. @mcoker thoughts?

Correct, it will truncate by default now when it runs out of space in its container. Setting the textMaxWidth prop allows for a custom width.

2023-03-03 20:50 UTC, thatblindgeye approved these changes

2023-03-03 20:58 UTC, nicolethoen approved these changes

2023-03-03 21:05 UTC, mcarrano approved these changes
This looks good now. I agree with @thatblindgeye that it would be nice to have an example that explicitly shows the effect of adding a maxWidth, but not a blocker.

2023-03-03 21:27 UTC, mcoker approved these changes
one small nit on a test

2023-03-03 21:27 UTC, mcoker commented on packages/react-core/src/components/Label/__tests__/Label.test.tsx
> +      <Label textMaxWidth="16c">textMaxWidth set at 16h on this very long label that should be truncated</Label>
```suggestion
      <Label textMaxWidth="16ch">textMaxWidth set at 16ch on this very long label that should be truncated</Label>
```

2023-03-03 21:29 UTC, tlabaj requested changes

2023-03-03 21:29 UTC, tlabaj commented on packages/react-core/src/components/Label/Label.tsx
> +  textMaxWidth = '',
Should this be undefined?  if not wont the check on line 218 always be true?

2023-03-03 21:37 UTC, gitdallas commented
@mcarrano @thatblindgeye  - sorry i must have missed that comment, added an example of a parent-constrained label https://patternfly-react-pr-8771.surge.sh/components/label/

2023-03-03 21:46 UTC, tlabaj approved these changes
LGTM

2023-03-04 03:02 UTC, merged

2023-03-04 03:26 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.0.0-alpha.25
 - @patternfly/react-core@5.0.0-alpha.25
 - @patternfly/react-docs@6.0.0-alpha.28
 - demo-app-ts@5.0.0-alpha.8
 - @patternfly/react-integration@5.0.0-alpha.4
 - @patternfly/react-table@5.0.0-alpha.25

Thanks for your contribution! :tada: