Chore/deprecate app launcher
patternfly/patternfly-react pull request #8836
Opened 2023-03-20 20:04 UTC by gitdallas

Closes #8074

2023-03-20 20:13 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8836.surge.sh

2023-03-21 13:03 UTC, thatblindgeye requested changes
The comments below will apply to the other demos that were updated to use the composable menu implementation of an app launcher (the MastheadWithUtilities.... demo and all 4 Page demos I believe)

2023-03-21 14:23 UTC, gitdallas commented on packages/react-core/src/demos/examples/DashboardHeader.js
> +    const menu = (
Makes sense, but I'll use `appLauncherMenu` as it is a level up (the menu with items, rather than just the items themselves)

2023-03-21 15:42 UTC, gitdallas commented
I wonder if I should import DashboardHeader into these to reduce all the duplicate code? The possible reason not to would be... "In the example, we want to show the full code that goes into the Page component."

Thoughts @nicolethoen @thatblindgeye @tlabaj ?

2023-03-21 18:55 UTC, thatblindgeye approved these changes
Keeping the examples as-is rather than importing DashboardHeader makes sense from a "show how someone else can implement the same thing" sort of way. https://github.com/patternfly/patternfly-react/pull/7927 was an update to the Page demos that specifically did not import the Dashboard wrapper at least

2023-03-22 21:29 UTC, nicolethoen reviewed
This all looks like it works. Is there a reason that our examples/demos shouldn't or can't use a Dropdown-next to replace the old application launchers?

2023-03-23 14:38 UTC, gitdallas commented
> #8074

I choose the replacement based on the issue description "Update any demos/examples that use the application launcher to use a recommended solution - the composable menu demo."

2023-03-23 14:41 UTC, nicolethoen commented
It may be worth doing once the dropdown-next is moved out of the dropdown directory. But i think this is fine for now. I'm going to open a follow up issue.

2023-03-23 18:18 UTC, tlabaj approved these changes
LGTM!
I will defer to @mcarrano on wether the demos should be using the Dropdown next, or be built with composable components  as they are in this PR.

2023-03-23 21:02 UTC, nicolethoen commented
I'd argue that if we are able to build any of our deprecated components as they function in demos/examples today using next components, we should (since they will all be promoted with this release) so that products see how to build things out of the box and not unnecessarily try to compose things completely on their own. There are a lot of interaction details to make sure are wired up correctly when they are built completely composably.

I'm working on opening an issue that is keeping track of all the places this might apply.

2023-03-24 15:34 UTC, tlabaj requested changes
@gitdallas We discussed this PR at the leads meeting today and we came to the consensus that we only need to demo the application launcher in the Masthead demo.  That demo should mirror the features we demonstrate in [composable application launcher demo](https://www.patternfly.org/v4/demos/composable-menu#composable-application-launcher) since that is most likely how it is being used in product.

You can remove the application launcher from the other demos.

2023-03-24 15:38 UTC, tlabaj commented on packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx
> +  const appLauncherMenu = (
This is the one we want to keep. We can update it to match the composable menu application launcher demo.

2023-03-24 21:14 UTC, nicolethoen commented
Looks to me that the search in the Masthead demo's App Launcher replacement is filtering out every option every time

2023-03-24 21:37 UTC, gitdallas commented
> Looks to me that the search in the [Masthead demo](https://patternfly-react-pr-8836.surge.sh/components/masthead/react-demos/masthead-with-utilities-and-user-dropdown-menu/)'s App Launcher replacement is filtering out every option every time

looks like that is happening in v5 generally in the composable menu example as well. i saw it was happening locally before my changes, also seen in a surge for a different pr https://patternfly-react-pr-8864.surge.sh/demos/composable-menu

i'm about to head out of town for the weekend but i can see if i can check what's going on when i get where i'm going.. if we want that fix as part of this pr

2023-03-24 21:37 UTC, gitdallas commented
> Looks to me that the search in the [Masthead demo](https://patternfly-react-pr-8836.surge.sh/components/masthead/react-demos/masthead-with-utilities-and-user-dropdown-menu/)'s App Launcher replacement is filtering out every option every time

looks like that is happening in v5 generally in the composable menu example as well. i saw it was happening locally before my changes, also seen in a surge for a different pr https://patternfly-react-pr-8864.surge.sh/demos/composable-menu

i had assumed it just wasn't set up to work, only now did i check pf4 and see it is working there

i'm about to head out of town for the weekend but i can see if i can check what's going on when i get where i'm going.. if we want that fix as part of this pr

2023-03-24 21:40 UTC, tlabaj commented
> i'm about to head out of town for the weekend but i can see if i can check what's going on when i get where i'm going.. if we want that fix as part of this pr

We will need to open an issue for the composable menu demo so we can probably fix it with that if @nicolethoen  agrees.

2023-03-24 21:44 UTC, tlabaj approved these changes
LGTM

2023-03-24 23:58 UTC, nicolethoen approved these changes

2023-03-25 02:45 UTC, gitdallas commented
@nicolethoen @tlabaj  - i pushed a quick fix for the filter issue

2023-03-27 01:03 UTC, nicolethoen approved these changes

2023-03-27 17:02 UTC, merged