fix(Table): rename TdActionsType 'disable' prop to 'isDisabled'
patternfly/patternfly-react pull request #8904
Opened 2023-04-03 15:23 UTC by adamviktora

**What**: Closes #8870

**Additional issues**: 
codemod issue follows: https://github.com/patternfly/pf-codemods/issues/354

2023-04-03 17:24 UTC, kmcfaul approved these changes

2023-04-03 20:09 UTC, jenny-s51 requested changes
Looking good @adamviktora ! Looks like we'll also want to update these examples to use `isDisabled`:

- https://github.com/patternfly/patternfly-react/blob/v5/packages/react-table/src/components/TableComposable/examples/TableSelectable.tsx#L112
- https://github.com/patternfly/patternfly-react/blob/v5/packages/react-table/src/components/TableComposable/examples/TableSelectableRadio.tsx#L54

2023-04-03 20:14 UTC, jenny-s51 approved these changes

2023-04-07 17:48 UTC, merged

2023-04-07 18:11 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@6.0.0-alpha.65
 - @patternfly/react-table@5.0.0-alpha.61

Thanks for your contribution! :tada: