fix(Table) clean up 'Expand collapse all' demo
patternfly/patternfly-react pull request #8988
Opened 2023-04-21 12:25 UTC by Dominik-Petrik

**What**: Closes #8976 

I have also revamped the demo to use functional instead of class component.

2023-04-21 12:33 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-8988.surge.sh

2023-05-03 21:05 UTC, nicolethoen requested changes
I'm also seeing the codesandbox throw an error about the onPageResize not being defined for the dashboardwrapper. i'm also seeing the same issue in other demos in the codesandbox, though so that can be addressed in the future.

2023-05-16 17:59 UTC, kmcfaul commented on packages/react-table/src/docs/demos/table-demos/ExpandCollapseAll.jsx
> +    setAreAllExpanded(expandedServerNames.length == serverData.length);
Adding onto this, can we also check whether the `expandedServerNames` length becomes 0? Currently if you expand a row and then collapse it such that there are no expanded rows, the overall "all expanded" carat isn't updating.

2023-05-18 14:35 UTC, gitdallas approved these changes

2023-05-18 14:38 UTC, kmcfaul reviewed
The state properly updates when a single folder collapse that results in all folders being collapsed updates the bulk select carat, but seeing a bug where expanding/collapsing a second folder is also toggling the bulk select.

2023-05-18 14:47 UTC, gitdallas commented
@kmcfaul - ah that's interesting. i do notice that it is using the state immediately after setting it. it should use the data that is being used to set the state instead of the state itself... or better yet - an effect.

@Dominik-Petrik

2023-05-18 20:31 UTC, nicolethoen approved these changes

2023-05-18 20:38 UTC, kmcfaul reviewed
Do we want the bulk select carat to show as "expanded" when some of the folders are expanded? Right now it's only showing "expanded" when all of the folders are open.

If so then it looks good to me

2023-05-18 20:47 UTC, nicolethoen commented
I think that top carat mean's expand all - so it should be open only when all are expanded?

2023-05-18 23:26 UTC, kmcfaul approved these changes

2023-05-23 15:18 UTC, merged

2023-05-23 15:49 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-docs@6.0.0-alpha.124
 - @patternfly/react-table@5.0.0-alpha.118

Thanks for your contribution! :tada: