chore(Table) bulk select demo cleanup
patternfly/patternfly-react pull request #9095
Opened 2023-05-09 19:49 UTC by Dominik-Petrik

**What**: Closes #8975

2023-05-12 00:49 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9095.surge.sh

2023-05-16 17:21 UTC, jenny-s51 requested changes
This is looking good @Dominik-Petrik ! Left some comments

2023-05-16 17:21 UTC, jenny-s51 commented on packages/react-table/src/docs/demos/table-demos/BulkSelect.jsx
> +  const [isBulkSelectOpen, setIsBulkSelectOpen] = React.useState(false);
Nit
```suggestion
  const [isBulkSelectDropdownOpen, setIsBulkSelectDropdownOpen] = React.useState(false);
```

2023-05-16 17:21 UTC, jenny-s51 commented on packages/react-table/src/docs/demos/table-demos/BulkSelect.jsx
> +          console.log(itemId);
```suggestion
```

2023-05-17 20:00 UTC, kmcfaul approved these changes

2023-05-17 20:27 UTC, merged