chore(deps): update pf core dep
patternfly/patternfly-react pull request #9108
Opened 2023-05-11 17:51 UTC by gitdallas

will close #8993

2023-05-11 17:55 UTC, gitdallas commented on packages/react-core/src/components/Chip/ChipGroup.tsx
> +import styles from '@patternfly/react-styles/css/components/Chip/chip-group';
Had to update this because of this change: https://github.com/patternfly/patternfly/pull/5559

2023-05-11 18:02 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9108.surge.sh

2023-05-11 18:23 UTC, gitdallas commented
@mcoker - do the snapshot updates make sense with recent core changes?

2023-05-11 19:18 UTC, mcoker commented
@gitdallas nope, glad you caught that. It's a bug in core, @mattnolting and I are looking at it now - https://github.com/patternfly/patternfly/issues/5560

2023-05-11 21:00 UTC, wise-king-sullyman approved these changes
It seems like this does resolve the original issue.

2023-05-11 21:01 UTC, wise-king-sullyman requested changes
Wait it looks like an integration test is failing, is that just related to the other core bug mentioned above?

2023-05-11 22:09 UTC, mcoker commented
@gitdallas @wise-king-sullyman this should be fixed now in [5.0.0-alpha.53](https://github.com/patternfly/patternfly/compare/prerelease-v5.0.0-alpha.52...prerelease-v5.0.0-alpha.53)

2023-05-12 14:46 UTC, gitdallas commented on packages/react-core/src/components/Label/Label.tsx
> +import labelGrpStyles from '@patternfly/react-styles/css/components/Label/label-group';
update based on pf core change

2023-05-12 14:46 UTC, gitdallas commented on packages/react-core/src/components/Label/LabelGroup.tsx
> +import styles from '@patternfly/react-styles/css/components/Label/label-group';
update based on pf core change

2023-05-12 14:46 UTC, gitdallas commented on packages/react-icons/scripts/icons/patternflyIcons.mjs
> +import { pfIcons } from '@patternfly/patternfly/icons/pficons.mjs';
update based on pf core change

2023-05-12 14:53 UTC, gitdallas commented
@wise-king-sullyman - right an issue was discovered with pf core while updating

@mcoker  - I've had to make a few other changes (pf-icons => pficons, LabelGroup => Label), i'm not sure what to do with the background image changes. what do you think? 

https://github.com/patternfly/patternfly-react/pull/9108/files#diff-8c26c106b002502c6b636b8af398bb5ac97fbfb9679673f9208dde8dfcfa7750R95

2023-05-15 17:20 UTC, gitdallas commented
Commented out background image related stuff, will be handled with this issue https://github.com/patternfly/patternfly-react/issues/9051

2023-05-15 17:47 UTC, wise-king-sullyman commented
@gitdallas looks like there's just a few unit test that probably just need to be `.skip`ed for now, then I think this should be good.

2023-05-15 18:25 UTC, kmcfaul approved these changes

2023-05-15 19:10 UTC, wise-king-sullyman approved these changes

2023-05-15 19:17 UTC, merged