fix(FileUpload): added DropEvent as a type exported from react-core
patternfly/patternfly-react pull request #9120
Opened 2023-05-15 19:40 UTC by wise-king-sullyman

**What**: Closes #8725

**Additional issues**:

2023-05-15 19:49 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9120.surge.sh

2023-05-16 12:12 UTC, thatblindgeye approved these changes

2023-05-16 14:11 UTC, tlabaj approved these changes
LGTM

2023-05-16 14:12 UTC, gitdallas approved these changes

2023-05-16 14:15 UTC, tlabaj requested changes
can we actually add a description of the newly defined types until this issue is resolved 
https://github.com/patternfly/patternfly-org/issues/3423

2023-05-16 15:18 UTC, wise-king-sullyman commented
@tlabaj is 3f503bd in line with what you had in mind?

2023-05-16 17:34 UTC, kmcfaul approved these changes

2023-05-16 18:46 UTC, tlabaj approved these changes

2023-05-16 18:46 UTC, merged

2023-05-16 19:15 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.0.0-alpha.103
 - @patternfly/react-core@5.0.0-alpha.102
 - @patternfly/react-docs@6.0.0-alpha.110
 - demo-app-ts@5.0.0-alpha.86
 - @patternfly/react-integration@5.0.0-alpha.44
 - @patternfly/react-table@5.0.0-alpha.104

Thanks for your contribution! :tada: