Iss9023 form control icons
patternfly/patternfly-react pull request #9132
Opened 2023-05-16 20:05 UTC by thatblindgeye

**What**: Closes #9023 

- deprecated Select and TreeViewSearch were both using inputs with the `pf-v5-c-form-control` class. These both (or just TreeView?) will end up needing to be updated to use SearchInput instead. For now the styling for TreeViewSearch is different as I hardcoded in markup to render the search icon on the right (rather than the left).
- The autoResize logic in TextArea currently does not work
- Added a FromControlIcon helper component rather than adding a `___Icon` sub-component for TextArea,FormSelect, and TextInput. I can move this to a more applicable directory if need be.

**Additional issues**:

2023-05-16 20:15 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9132.surge.sh

2023-05-17 12:23 UTC, nicolethoen commented
And this will need a code mod, right? 

- props being removed related to iconSprites
- props being changed related to customIcons
- the TextInput's isReadOnly prop being removed
- the new way to handle expandable text areas
- probably more I missed?

2023-05-17 12:24 UTC, nicolethoen commented
> * The autoResize logic in TextArea currently does not work

@thatblindgeye is this a regression? Is it because of the new DOM structure? Can we fix it w/o a breaking change and maybe make a follow up issue or does it require investigation today?

2023-05-17 12:43 UTC, thatblindgeye commented
@nicolethoen Yeah there'll definitely be some codemods needed after this update. I'm going to go through and open an issue(s) for anything I catch.

And I believe it *might* be due to new structure, but I'm going to investigate a bit more into it.

2023-05-17 12:48 UTC, srambach commented
> Do we want to allow multiple icons to be rendered, and if so should it be on all 3 of these components?
I don't know of any place that uses an icon (not a status icon) on a text area or select. @mcoker?
The text input definitely needs to support both a custom icon and a status.

> The autoResize logic in TextArea currently does not work
This is almost definitely due to the new structure - in order to make sure the icon doesn't float off by itself, the resize was moved out onto the wrapper div rather than the text area itself. Then the text area just takes up as much room as there is. Is there a way to manage auto resize with that?

2023-05-17 13:20 UTC, thatblindgeye commented
@nicolethoen @srambach Updated the autoresizing logic. Looks like the previous `heightToken` isn't actually applied to anything in Core anymore, so now just setting the `height` on the `.pf-v5-c-form-control` div.

2023-05-17 14:39 UTC, srambach commented
File upload changed a little

2023-05-17 15:49 UTC, mcoker commented
@mcarrano @srambach @thatblindgeye Looks like we're styling the old form control class for things that need to be updated with to style the right element based on the updates made in core to remove the background images - https://github.com/patternfly/patternfly/issues/5583

2023-05-17 16:56 UTC, thatblindgeye commented
@mcarrano I updated the icon on TimePicker. Looks like the other issues should be covered by the issue @mcoker created in Core above.

2023-05-17 17:28 UTC, nicolethoen approved these changes
the react code here looks solid

2023-05-17 17:48 UTC, mcarrano approved these changes
> @mcarrano I updated the icon on TimePicker. Looks like the other issues should be covered by the issue @mcoker created in Core above.

In that case I approve.

2023-05-17 18:24 UTC, wise-king-sullyman approved these changes

2023-05-17 20:16 UTC, tlabaj requested changes

2023-05-17 20:16 UTC, tlabaj commented on packages/react-core/src/helpers/FormControlIcon.tsx
> +  return customIcon || StatusIcon ? (
I do not know that this check is necessary this is an internal component.

2023-05-17 22:39 UTC, gitdallas approved these changes

2023-05-18 00:11 UTC, tlabaj commented
> @mcarrano @srambach @thatblindgeye Looks like we're styling the old form control class for things that need to be updated with to style the right element based on the updates made in core to remove the background images. That will account for some of these visual bugs you're seeing @mcarrano. I created an issue to fix those - [patternfly/patternfly#5583](https://github.com/patternfly/patternfly/issues/5583)

@mcoker is this good to merge as is or do do we want to wait for core bug to be fixed?

2023-05-18 01:22 UTC, mcoker commented
@tlabaj no need to wait for core IMO, those updates will not need a react follow up.

2023-05-18 13:34 UTC, kmcfaul approved these changes

2023-05-18 15:33 UTC, mcoker approved these changes
LGTM! Just one note about a modifier on `<TextInput>` that I don't think is necessary.

2023-05-18 17:45 UTC, tlabaj approved these changes
LGTM!

2023-05-18 17:45 UTC, merged