fix(react-styles): updated class names to include versions
patternfly/patternfly-react pull request #9173
Opened 2023-05-23 20:10 UTC by wise-king-sullyman

**What**: Closes #9150

**Additional issues**:

2023-05-30 21:44 UTC, mcoker requested changes
None of these classes exist in core, so I tried tracing at least one back and looks like this update should work...

The styles for `.pf-v5-c-table__inline-edit-buttons`, as an example, are converted to a js file and that's read in here, and the class is applied to the markup. So updating the source CSS should also update the markup, at least for that class. I'm assuming the `.pf-v5-c-table__editable-row` `pf-v5-c-console` work the same way? I didn't verify that. Also it's worth noting that I found this snippet in the `main` branch - I'm assuming this inline-edit-extension dir has been moved to another repo? It isn't on v5 as far as I can tell.

https://github.com/patternfly/patternfly-react/blob/a0f857c4de39dd415792a8701e7c6ac7fd853024/packages/react-inline-edit-extension/src/components/ConfirmButtons/ConfirmButtons.tsx#L57

However, the color vars do need to be updated. The format is `--pf-v5-global--palette--[color]-[number]` - just need to remove the extra hyphen between the color name and number.

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  --pf-v5-global--palette--blue--200: #7dc3e8;
```suggestion
  --pf-v5-global--palette--blue-50: #def3ff;
  --pf-v5-global--palette--blue-200: #7dc3e8;
```

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  background: var(--pf-v5-global--palette--blue--50) !important;
```suggestion
  background: var(--pf-v5-global--palette--blue-50) !important;
```

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  border-top: 1px solid var(--pf-v5-global--palette--blue--200) !important;
```suggestion
  border-bottom: 1px solid var(--pf-v5-global--palette--blue-200) !important;
  border-top: 1px solid var(--pf-v5-global--palette--blue-200) !important;
```

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  border-left: 1px solid var(--pf-v5-global--palette--blue--200) !important;
```suggestion
  border-left: 1px solid var(--pf-v5-global--palette--blue-200) !important;
```

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  border-right: 1px solid var(--pf-v5-global--palette--blue--200) !important;
```suggestion
  border-right: 1px solid var(--pf-v5-global--palette--blue-200) !important;
```

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  border-top: 3px solid var(--pf-v5-global--palette--blue--200) !important;
```suggestion
  border-top: 3px solid var(--pf-v5-global--palette--blue-200) !important;
```

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  border-bottom: 3px solid var(--pf-v5-global--palette--blue--200) !important;
```suggestion
  border-bottom: 3px solid var(--pf-v5-global--palette--blue-200) !important;
```

2023-05-30 21:44 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
> +  border: 1px solid var(--pf-v5-global--palette--blue--200);
```suggestion
  background: var(--pf-v5-global--palette--blue-50);
  border: 1px solid var(--pf-v5-global--palette--blue-200);
```

2023-05-31 19:41 UTC, tlabaj reviewed
lgtm
I will defer to css for final approval.

2023-05-31 19:42 UTC, tlabaj approved these changes

2023-05-31 22:21 UTC, mcoker requested changes
one more small one I missed

2023-05-31 22:21 UTC, mcoker commented on packages/react-styles/src/css/components/Table/inline-edit.css
>    border: 1px solid var(--pf-v5-global--BorderColor);
```suggestion
  border: 1px solid var(--pf-v5-global--BorderColor--100);
```

2023-06-01 14:49 UTC, mcoker approved these changes
👍

2023-06-01 18:40 UTC, jpuzz0 approved these changes

2023-06-01 19:12 UTC, gitdallas approved these changes

2023-06-01 19:36 UTC, merged

2023-06-01 20:04 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-charts@7.0.0-alpha.34
 - @patternfly/react-code-editor@5.0.0-alpha.131
 - @patternfly/react-core@5.0.0-alpha.130
 - @patternfly/react-docs@6.0.0-alpha.140
 - demo-app-ts@5.0.0-alpha.114
 - @patternfly/react-styles@5.0.0-alpha.18
 - @patternfly/react-table@5.0.0-alpha.134

Thanks for your contribution! :tada: