fix(PasswordStrength): fix demo to expect event parameter as first
patternfly/patternfly-react pull request #9191
Opened 2023-05-25 19:07 UTC by KKoukiou

2023-05-25 19:19 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9191.surge.sh

2023-05-25 20:25 UTC, jenny-s51 requested changes
Hi @KKoukiou this is looking great - demo is now working as expected. Left a comment. 

Would you mind linking the related issue in the description?

2023-05-25 20:25 UTC, jenny-s51 commented on packages/react-core/src/demos/PasswordStrength.md
> +    this.handlePasswordInput = (_, password) => {
Would be nice to have
```suggestion
    this.handlePasswordInput = (_event, password) => {
```

2023-05-26 05:57 UTC, KKoukiou commented
Closing in favor of #9170 9196

2023-05-26 05:57 UTC, closed without merging