fix(TextInput): swap onChange params in demos
patternfly/patternfly-react pull request #9196
Opened 2023-05-26 05:52 UTC by MariaAga

**What**: Closes #9192

a few function args weren't swapped in https://github.com/patternfly/patternfly-react/pull/9064

2023-05-26 05:59 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9196.surge.sh

2023-05-26 13:20 UTC, jenny-s51 requested changes

2023-05-26 13:20 UTC, jenny-s51 commented on packages/react-core/src/demos/PrimaryDetail.md
> +    this.onInputChange = (_event,, newValue) => {
```suggestion
    this.onInputChange = (_event, newValue) => {
```

2023-05-26 14:37 UTC, MariaAga commented on packages/react-core/src/demos/PrimaryDetail.md
> +    this.onInputChange = (_event,, newValue) => {
fixed, thanks!

2023-05-30 13:46 UTC, tlabaj approved these changes
lgtm

2023-05-30 14:35 UTC, jenny-s51 approved these changes

2023-05-30 14:51 UTC, merged