chore(docs): Updated the Navigation demos to use the masthead instead of the page header
patternfly/patternfly-react pull request #9223
Opened 2023-06-01 22:05 UTC by tlabaj

**What**: Closes #9015

2023-06-01 22:14 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9223.surge.sh

2023-06-02 13:38 UTC, thatblindgeye reviewed
For the Horizontal Nav demo, the breakpoints aren't kicking in at the right time resulting in content overflowing to the right when the viewport is shrunk down:

![Horizontal demo overflow](https://github.com/patternfly/patternfly-react/assets/70952936/8ca3a663-3b6c-4bb9-af51-3e0775cb62e1)

The Horizontal Nav with Horizontal Subnav demo also has a similar overflow issue, except it's overflowing on page load. 

We could adjust the `visibility` of the ToolbarGroup's and set a width for the Nav components in these two examples.

2023-06-02 19:46 UTC, mcarrano requested changes
This still has the issue of the user menu having a lighter background in dark theme.

<img width="466" alt="Screenshot 2023-06-02 at 3 45 29 PM" src="https://github.com/patternfly/patternfly-react/assets/6619860/2bd3fa0f-8cdf-41cd-aecb-a5ff5e5ad45f">

@mcoker I thought that was fixed?

2023-06-02 21:09 UTC, mcoker commented
@mcarrano I have a PR up that fixes it, but it didn't go in until late last night and it was too late to merge - https://github.com/patternfly/patternfly/pull/5643. If we want to try and get it in, I have an open question in the issue here - https://github.com/patternfly/patternfly/pull/5643#issuecomment-1572960124

2023-06-05 13:11 UTC, mcarrano commented
Thanks @mcoker I would try to get this in if we can. As to your question on https://github.com/patternfly/patternfly/pull/5643, I'm not sure what the right answer is and want to get input from @mceledonia . Will reach out on Slack to resolve this ASAP.

@nicolethoen can we still try to get this into the release? The user menu does not look correct without it in dark mode.

2023-06-06 13:12 UTC, tlabaj commented
> 

@thatblindgeye @mcoker it looks like we are missing a "pf-m-overflow-container" on the toolbar item that holds the nav.  React does not currently support that.  I can add it as part of this PR.

2023-06-06 13:25 UTC, tlabaj commented
> > 
> 
> @thatblindgeye @mcoker it looks like we are missing a "pf-m-overflow-container" on the toolbar item that holds the nav. React does not currently support that. I can add it as part of this PR.  It should fix that issue @thatblindgeye  mentions above

2023-06-06 17:24 UTC, thatblindgeye requested changes
Just a quick update below

2023-06-06 17:24 UTC, thatblindgeye commented on packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
> +  /** Flag that modifies the toolbar item to hide overflow and respond to available space. Used for horizontal navigation. */
```suggestion
  /** Flag that modifies the toolbar group to hide overflow and respond to available space. Used for horizontal navigation. */
```

2023-06-06 18:42 UTC, thatblindgeye approved these changes

2023-06-06 20:47 UTC, mcarrano commented
User menu looks good now. Just seeing a couple of additional issues.

* The drilldown nav example seems to be broken: https://patternfly-react-pr-9223.surge.sh/components/navigation/react-demos/drilldown-nav/  I do see that this is broken in the latest release of v4, so not sure when that happened. But we should fix for v5 if possible.

* There are two examples that still use the word "legacy." Can we change this? Perhaps change them to "Tertiary (deprecated)" and "Light nav (deprecated)." Or should we just remove these examples if we don't want demos that use deprecated components. @tlabaj @nicolethoen @mcoker thoughts?

2023-06-06 21:09 UTC, tlabaj commented
> User menu looks good now. Just seeing a couple of additional issues.
> 
> * The drilldown nav example seems to be broken: https://patternfly-react-pr-9223.surge.sh/components/navigation/react-demos/drilldown-nav/  I do see that this is broken in the latest release of v4, so not sure when that happened. But we should fix for v5 if possible.
> * There are two examples that still use the word "legacy." Can we change this? Perhaps change them to "Tertiary (deprecated)" and "Light nav (deprecated)." Or should we just remove these examples if we don't want demos that use deprecated components. @tlabaj @nicolethoen @mcoker thoughts?

@mcarrano there is an issue open for drilldown nav here https://github.com/patternfly/patternfly-react/issues/9183

I updated the demo titles

2023-06-06 23:49 UTC, mcarrano approved these changes
Thanks @tlabaj . I am good to merge this.

2023-06-07 13:33 UTC, kmcfaul approved these changes
lgtm. 

I did notice that the nav drilldown demo looks like it may be broken, but this PR didn't touch that so we may want a follow up issue.

2023-06-07 14:15 UTC, merged