feat(Pagination): add offset example
patternfly/patternfly-react pull request #9232
Opened 2023-06-02 16:12 UTC by MariaAga

**What**: Closes #9231
when having a per_page=20, and offset is 20  (skip the first 20 items ,show item numbers 21,22,23...), page should be calculated to 2, but before this change it was calculated as 1

2023-06-02 16:20 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9232.surge.sh

2023-06-05 19:46 UTC, gitdallas requested changes
lgtm other than the typo below

2023-06-05 19:46 UTC, gitdallas commented on packages/react-core/src/components/Pagination/examples/Pagination.md
> +### Offsest
```suggestion
### Offset
```

2023-06-06 08:28 UTC, MariaAga commented on packages/react-core/src/components/Pagination/examples/Pagination.md
> +### Offsest
Thanks, fixed

2023-06-09 18:13 UTC, gitdallas approved these changes

2023-06-12 13:13 UTC, thatblindgeye approved these changes

2023-06-12 21:02 UTC, mcarrano reviewed
I will defer to others. I'm not really sure what this example is intended to illustrate, but seems to function as expected.

2023-08-07 16:51 UTC, tlabaj approved these changes

2023-08-07 16:51 UTC, merged