chore(ouia) Updated prefix to PF5
patternfly/patternfly-react pull request #9250
Opened 2023-06-06 21:34 UTC by tlabaj

**What**: Closes #9249

2023-06-06 21:44 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9250.surge.sh

2023-06-07 12:13 UTC, thatblindgeye requested changes

2023-06-08 18:04 UTC, kmcfaul approved these changes

2023-06-08 21:21 UTC, evwilkin commented
@tlabaj build is failing after fixing merge conflict - here's the previous PR merge which touched the react-core version, can you help resolve?
- https://github.com/patternfly/patternfly-react/pull/9254/files#diff-f951c25a500d53f9a661f3e19b36a23cf2eecbfa1a8fd4f1fb0adcb7ad153b2aR12

2023-06-09 12:40 UTC, gitdallas approved these changes

2023-06-09 15:40 UTC, merged

2023-06-09 16:05 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.0.0-prerelease.6
 - @patternfly/react-core@5.0.0-prerelease.6
 - @patternfly/react-docs@6.0.0-prerelease.6
 - demo-app-ts@5.0.0-prerelease.4
 - @patternfly/react-table@5.0.0-prerelease.6

Thanks for your contribution! :tada: