Allows NavExpandable to accept ReactNode as a title prop
patternfly/patternfly-react pull request #9264
Opened 2023-06-12 13:32 UTC by dvail

Potential fix for #9261 

Changes the `<NavExpandable>` `title` prop to accept any `ReactNode`. This also adds an example of this to the documentation. (Is this wanted, or is it more of a distraction in it's current location?)

2023-06-12 13:39 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9264.surge.sh

2023-08-16 15:24 UTC, andrew-ronaldson commented
Not sure where this fits into the component (core/react) but I noticed the nav text is centered and the label breaks to a new line. Can this be inline with the rest of the nav item title?
<img width="234" alt="Screenshot 2023-08-16 at 12 21 24 PM" src="https://github.com/patternfly/patternfly-react/assets/28658548/de4cc274-d896-4ef2-a35a-6a36dcd22587">

2023-08-23 18:53 UTC, kmcfaul commented
I think the line break is a result of using `Flex`, it will automatically collapse separate items into a stack when the window narrows. Wrapping both the `span` and `Label` in the example with a `FlexItem` will group the two slightly better (the label is still on a new line but matches the center alignment of the text). Is that close to what you're thinking or is the intent having the label to the right of the text?

2023-08-24 14:06 UTC, mcoker approved these changes
🚀

2023-08-24 18:03 UTC, tlabaj approved these changes

2023-08-24 18:55 UTC, mcoker commented
After chatting with @tlabaj about it, it's probably better if we create a better HTML structure for markup (as opposed to just text) to go in the nav link. I think the main issue with the structure now would because the nav link is a flex layout, its children are going to be flex children, so passing something like "nav text <SomeIcon>" will not display that way since "nav text" and "<SomeIcon>" will be separate flex children. Both of them will be stretched, and the whitespace between them will not be preserved. It would be better if we added a wrapper for the nav link text/content that is not a flex layout, and that will be what holds the nav link text/content.

To do this in a way that isn't breaking and doesn't impact current users passing strings as the nav text, we could do this as an opt-in by changing the markup if anything other than a string is passed via something like:
* Check the type of the value passed as the `title` prop
* If the type is string, leave the markup as it is
* Else, wrap the value of the `title` prop in a `.pf-v5-c-nav__link-text` element

Created a core issue for the initial work to add that element - https://github.com/patternfly/patternfly/issues/5857

2023-08-24 19:22 UTC, tlabaj requested changes
Can we incorporate @mcoker suggestion of checking type and rendering accordingly?

2023-08-29 19:45 UTC, mcoker commented
@tlabaj the core change was merged, though it's worth noting that there are no associated styles for the `.pf-v5-c-nav__link-text` element, so its className will probably need to be hardcoded in the react component - https://github.com/patternfly/patternfly/pull/5868/

2023-09-17 14:10 UTC, andrew-ronaldson approved these changes
Seems good to me. Thank you!

2023-10-11 20:39 UTC, tlabaj commented
I could not push to this PR, so I created a new one to add the nav link text wrapper
https://github.com/patternfly/patternfly-react/pull/9740

2023-10-26 20:48 UTC, tlabaj commented
Closing sicethis was resolved with PR #9740

2023-10-26 20:48 UTC, closed without merging