feat(SimpleList): add ul/li classes
patternfly/patternfly-react pull request #9302
Opened 2023-06-22 17:42 UTC by kmcfaul

**What**: Closes #8482

Adds css classes to the SimpleList ul and li (hardcoded because they're not included in react styles).

2023-06-22 17:51 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9302.surge.sh

2023-06-23 17:52 UTC, jenny-s51 approved these changes
Matches core, LGTM

2023-07-05 15:28 UTC, thatblindgeye approved these changes

2023-08-01 01:53 UTC, mcoker requested changes
Looks good but it's still missing from the group lists - https://github.com/patternfly/patternfly-react/blob/a79102e34357dbe6416783830bd4580c934342d2/packages/react-core/src/components/SimpleList/SimpleListGroup.tsx#L30

2023-08-01 14:48 UTC, mcoker approved these changes

2023-08-01 20:49 UTC, tlabaj approved these changes
lgtm

2023-08-01 20:50 UTC, merged