feat(Drawer): add noBackground to colorVariant
patternfly/patternfly-react pull request #9372
Opened 2023-07-18 13:56 UTC by kmcfaul

**What**: Closes #8548

Adds `no-background` to `colorVariant` props in Drawer.

2023-07-18 14:03 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9372.surge.sh

2023-07-19 19:54 UTC, thatblindgeye requested changes
The `PrimaryDetailContentPadding.tsx` file could also use an update to remove the hardcoded class

2023-07-20 14:56 UTC, thatblindgeye approved these changes

2023-08-01 01:55 UTC, mcoker approved these changes
LGTM! 👍

2023-08-01 20:46 UTC, tlabaj approved these changes

2023-08-01 20:46 UTC, merged