fix(DatePicker): updated onBlur logic for empty date
patternfly/patternfly-react pull request #9373
Opened 2023-07-18 15:39 UTC by thatblindgeye

**What**: Closes #8779 

Originally had added logic to call `setError` if `pristine && isRequired`, but that would have required a consumer to always pass in a validator to `validators` array; something along the lines of `validators={[(date) => !date ? 'Date cannot be blank' : '']}`.

Just adding a new isRequired and emptyDateText props will make it easier for consumers, and it avoids a case of `isRequired` being passed in but an error message never appearing if a validator isn't passed in.

This is somewhat dependent on #9267, but should just require a slight tweak in that PRs code (the `value === '' && setErrorText('')` line)

**Additional issues**:

2023-07-21 14:44 UTC, edonehoo approved these changes
looks good!

2023-07-26 19:31 UTC, kmcfaul approved these changes

2023-08-03 19:26 UTC, nicolethoen approved these changes

2023-08-07 16:46 UTC, tlabaj requested changes

2023-08-07 16:46 UTC, tlabaj commented on packages/react-core/src/components/DatePicker/DatePicker.tsx
> +  /** Flag indicating the date picker is required. */
```suggestion
  /** Flag indicating the date is required. */
```

2023-08-07 16:46 UTC, tlabaj commented on packages/react-core/src/components/DatePicker/DatePicker.tsx
> +  emptyDateText?: string;
I would group this with "isRequired". since it only is used when that is set.

2023-08-08 13:50 UTC, tlabaj approved these changes
lgtm

2023-08-08 13:50 UTC, merged