feat(misc): update screenreader classname
patternfly/patternfly-react pull request #9392
Opened 2023-07-20 14:22 UTC by kmcfaul

**What**: Closes #8295

Updates components to use `pf-screen-reader` class. Because this is a utility class we don't need the `v5` prefix right?

2023-07-20 14:30 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9392.surge.sh

2023-07-25 19:19 UTC, thatblindgeye commented
>Because this is a utility class we don't need the v5 prefix right?

This is one of the ones that does need the `v5` prefix

2023-08-02 19:50 UTC, thatblindgeye requested changes
There's a `pf-v5-u-screen-reader` class being checked for in one of the Banner tests that needs to be updated.

@srambach the preview might not have updated. Checking Katie's branch locally the classes look correct:

![Alert component markup](https://github.com/patternfly/patternfly-react/assets/70952936/6c3b0580-3d30-4da1-9072-06494350a465)

2023-08-02 19:57 UTC, srambach commented
Just wondering also why the screen reader class isn't included in the classmaps. @nicolethoen  found [this PR](https://github.com/patternfly/patternfly-react/pull/5251)that specifically excludes it but that means it's going to need to be manually updated each major version. Maybe you want to make an issue to update to use a classmap if it can?

2023-08-03 13:51 UTC, kmcfaul commented
We do have an accessibilityStyles css object that includes the screenreader class but that's still using the old -u classname. I'm unsure where it's pulling the css from in the react-styles package to update that, or if that would fall under the issue of needing to be excluded like in the linked PR.

2023-08-08 18:49 UTC, thatblindgeye approved these changes

2023-08-09 13:15 UTC, nicolethoen approved these changes

2023-08-16 13:20 UTC, merged