feat(Table): Added isNoInset prop for flat tree tables
patternfly/patternfly-react pull request #9427
Opened 2023-08-01 00:06 UTC by nicolethoen

Closes https://github.com/patternfly/patternfly-react/issues/8604

2023-08-01 00:14 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9427.surge.sh

2023-08-01 18:14 UTC, kmcfaul commented on packages/react-table/src/components/Table/Table.tsx
> +  /** Flag rows will not have the inset typically reserved for expanding/collapsing rows in a tree table. Intended for use on tree tables with no visible rows with children. */
`indicating` missing

2023-08-01 20:35 UTC, tlabaj requested changes

2023-08-01 20:35 UTC, tlabaj commented on packages/react-table/src/components/Table/Table.tsx
> +  isNoInset?: boolean;
maybe `hasNoInset`

2023-08-07 16:37 UTC, tlabaj approved these changes

2023-08-08 19:04 UTC, thatblindgeye approved these changes

2023-08-08 20:41 UTC, mattnolting approved these changes
LGTM 👍 Might add a follow up to showcase feature in an example.

2023-08-15 18:58 UTC, kmcfaul approved these changes
lgtm just needs a few lint errors resolved

2023-08-16 13:36 UTC, merged