chore(NotificationDrawer): demo conversion from JS to TS
patternfly/patternfly-react pull request #9516
Opened 2023-08-17 19:41 UTC by adamviktora

**What**: Closes #9438

2023-08-17 19:55 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9516.surge.sh

2023-08-22 14:59 UTC, nicolethoen commented
I cannot figure out why the ts -> js button is not appearing in the second demo and the site doesn't seem to think the second demo is written in ts... still looking into it, but maybe someone else here knows?

2023-08-22 17:58 UTC, thatblindgeye requested changes
Haven't looked into the above issue that Nicole mentioned, but I'd imagine we could update the `js file=...` to `ts file=...` in the MD file. Do you get the same issue as the Nav demo PR when doing so?

2023-08-22 17:58 UTC, thatblindgeye commented on packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerGrouped.tsx
> +        onClick={(ev: { preventDefault: () => any }) => ev.preventDefault()}
This is causing a Syntax error when opening the demo. Can we type the `ev` as any to match the `onClick` prop in DropdownItem?

```suggestion
        onClick={(ev: any) => ev.preventDefault()}
```

2023-08-22 17:58 UTC, thatblindgeye commented on packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerBasic.tsx
> +export const BasicNotificationDrawer: React.FunctionComponent = () => {
Can we just update these exports to match the file names, similar to our examples? `NotificationDrawerBasic` and `NotificationDrawerGrouped`

2023-08-22 18:59 UTC, thatblindgeye commented
@nicolethoen I wonder if it's just an issue with the preview... I tried editing my Org clone locally to add in the tsx example files to react-core (using `js file=...` in the MD), and the demos rendered with the correct "JS" icon in the example toolbar.

2023-08-23 18:55 UTC, kmcfaul commented
Maybe a rebase/rebuild would iron out the surge?

2023-09-01 02:19 UTC, nicolethoen approved these changes
looks like its all working now!

2023-09-01 12:47 UTC, thatblindgeye approved these changes

2023-09-01 13:28 UTC, merged

2023-09-01 13:58 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.1.1-prerelease.3
 - @patternfly/react-core@5.1.1-prerelease.3
 - @patternfly/react-docs@6.1.1-prerelease.3
 - demo-app-ts@5.1.1-prerelease.2
 - @patternfly/react-table@5.1.1-prerelease.3

Thanks for your contribution! :tada: