chore(Card): convert Card react demos to TS
patternfly/patternfly-react pull request #9561
Opened 2023-08-31 19:59 UTC by jenny-s51

**What**: Closes #9374 

Converted remaining Card react demos to TS and fixed various linting / type errors

2023-08-31 20:09 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9561.surge.sh

2023-09-05 14:05 UTC, thatblindgeye requested changes
Some comments/pretty quick updates below. Could we also create separate files for these demos in a `demos/examples/CardDemos` directory?

2023-09-05 14:05 UTC, thatblindgeye commented on packages/react-core/src/demos/CardDemos.md
>  const AccordionCard: React.FunctionComponent = () => {
```suggestion
const CardWithAccordion: React.FunctionComponent = () => {
```

2023-09-25 18:59 UTC, jenny-s51 commented on packages/react-core/src/demos/CardDemos.md
> +          backgroundImage: 'url(/assets/images/pfbg_992@2x.jpg)'
Thanks, nice catch @thatblindgeye - this needs an absolute url, will update

2023-09-25 19:13 UTC, jenny-s51 commented on packages/react-core/src/demos/CardDemos.md
> +          <Level hasGutter>
Great point @thatblindgeye - I think technically this is out of scope but would be a nice discussion to have. Could be worth tracking this in a separate issue

2023-09-25 20:28 UTC, jenny-s51 commented on packages/react-core/src/demos/CardDemos.md
> +  const handleTabClick = (tabIndex: number) => {
Yes, good idea 👍 updated

2023-10-12 20:20 UTC, tlabaj approved these changes
LGTM. Just needs a rebase.

2023-10-13 11:44 UTC, merged