chore(BackgroundImage): update tests
patternfly/patternfly-react pull request #9584
Opened 2023-09-11 17:38 UTC by kmcfaul

**What**: Closes #9525

2023-09-11 17:46 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9584.surge.sh

2023-09-11 18:19 UTC, thatblindgeye requested changes
One nit below. We should also use the `styles` object for class names, and add a test for spreading additional props

2023-09-11 18:19 UTC, thatblindgeye commented on packages/react-core/src/components/BackgroundImage/__tests__/BackgroundImage.test.tsx
> +  const backgroundImageStyle = screen.getByTestId('test-id').getAttribute('style');
Nit: we could remove this variable altogether and just have the expectation be `expect(screen.getByTestId('test-id')).toHaveAttribute('style', '--pf-v5-c-background-image--BackgroundImage:/image/url.png')` (give or take a space between the CSS var and value)

2023-09-14 14:45 UTC, kmcfaul commented
> We should also use the `styles` object for class names

What do you mean here? 

I've updated with your other feedback.

2023-09-21 14:37 UTC, kmcfaul commented
Updated to use the styles object.

2023-09-21 17:05 UTC, thatblindgeye approved these changes

2023-09-21 19:02 UTC, tlabaj approved these changes

2023-09-21 19:02 UTC, merged