chore(Table) convert demos to ts
patternfly/patternfly-react pull request #9621
Opened 2023-09-13 15:00 UTC by Dominik-Petrik

**What**: Closes #9447 

There are a few import errors when yarn start is run I don't know how to solve.

2023-10-20 19:47 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9621.surge.sh

2023-10-20 20:57 UTC, jenny-s51 reviewed
Fixed build, working on updating the remaining demos to TSX

2023-10-23 20:36 UTC, jenny-s51 reviewed
Update:

Converted remaining table demos to TSX.

`ColumnManagementWithDraggable` demo requires heavy refactoring and  reimplementation using the new Draggable and Droppable components. Working out the remaining logic so we can also close https://github.com/patternfly/patternfly-react/issues/7471

2023-10-25 16:40 UTC, jenny-s51 commented
`ColumnManagementWithDraggable` demo has been converted to TS.

As mentioned above, following more investigation, the `ColumnManagementWithDraggable` logic requires a significant overhaul due to the new DragDrop implementation. Work has been started [here](https://github.com/jenny-s51/patternfly-react/tree/colMgmtWithDnDTableDemo).

Following discussion/consensus in standup today with @thatblindgeye and @kmcfaul... the scope of the DragDrop-related refactoring effort is large, and it is out of scope of this original TS conversion issue, therefore it makes more sense to merge in this PR and track the additional work towards #7471 separately. 

Furthermore, additional changes to the DragDrop implementation are currently in progress (see https://github.com/patternfly/patternfly-react/issues/6317).

2023-11-02 13:04 UTC, thatblindgeye requested changes
In addition to below, I'm also noticing in the bulk select demo that the styling of the split button toggle is off when checked:

![Split button toggle with incorrect styling](https://github.com/patternfly/patternfly-react/assets/70952936/1e293ee7-2cfc-4404-89a6-06be4cc94c33)

It's like this on the staging site as well cc @mcoker looks like it's the `align-self: center` that was added in https://github.com/patternfly/patternfly/pull/5947 ?

2023-11-03 20:01 UTC, jenny-s51 commented on packages/react-table/src/demos/examples/TableBulkSelect.tsx
> +  const [isBulkSelectDropdownOpen, setIsBulkSelectDropdownOpen] = React.useState<boolean>(false);
Good point - updated

2023-11-03 20:08 UTC, jenny-s51 reviewed
Thanks @thatblindgeye for your comments! Following our team discussion in standup yesterday about type inference ... since we have `strict` typing on, I added types to areas where ESLint was inferring the `any` type, and made some corresponding updates to logic.

2023-11-15 14:46 UTC, wise-king-sullyman commented
@jenny-s51 it looks like there's an a11y error being thrown

2023-11-17 15:55 UTC, thatblindgeye commented on packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx
> +                          aria-controls={_isExpanded ? expandableContentId : undefined}
As an FYI, Jenny and I discussed this and I opened https://github.com/patternfly/patternfly-react/issues/9827 as an investigation as to whether this should be a temporary fix or not

2023-11-17 19:49 UTC, tlabaj approved these changes

2023-11-17 19:49 UTC, merged

2023-11-17 20:01 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.2.0-prerelease.31
 - @patternfly/react-core@5.2.0-prerelease.31
 - @patternfly/react-docs@6.2.0-prerelease.31
 - demo-app-ts@5.1.1-prerelease.54
 - @patternfly/react-table@5.2.0-prerelease.31

Thanks for your contribution! :tada: