feat(Drawer): Added start and end to position props, updated resizing to work with RTL
patternfly/patternfly-react pull request #9627
Opened 2023-09-14 21:33 UTC by tlabaj

**What**: Closes #9596

2023-09-14 21:43 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9627.surge.sh

2023-09-15 14:09 UTC, thatblindgeye requested changes
One change below. Unrelated to the linked issue but it seems like some of our examples are redundant? We have a "basic" example which shows the drawer at the end, but also have an "end" example that shows the same behavior, just with the `position` prop explicitly passed in. Same goes for the inline examples.

2023-09-15 14:09 UTC, thatblindgeye commented on packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
> +      newSize = mousePos - start;
Looks like we need to take into account the isRTL var when reassigning newSize here:

```suggestion
    if (position === 'end' || position === 'right') {
      newSize = isRTL ? mousePos - end : end - mousePos;
    } else if (position === 'start' || position === 'left') {
      newSize = isRTL ? start - mousePos : mousePos - start;
```

Right now when I click and hold the splitter to resize the drawer with RTL enabled, it just snaps to the smallest size and I'm unable to resize the drawer. The above I was able to resize things in both RTL and LTR as expected.

2023-09-15 14:54 UTC, mcoker reviewed
LGTM other than Eric's comment about the splitter/resizing in RTL.

2023-09-18 18:11 UTC, thatblindgeye approved these changes

2023-09-19 17:57 UTC, wise-king-sullyman approved these changes

2023-09-19 19:28 UTC, mcoker approved these changes
🤩👍

2023-09-20 15:20 UTC, merged