fix(clipboard-copy): added rtl support
patternfly/patternfly-react pull request #9629
Opened 2023-09-14 22:49 UTC by mcoker

2023-09-14 22:57 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9629.surge.sh

2023-09-15 12:26 UTC, thatblindgeye requested changes
As part of this, we should update the Toggle icon to mirror in RTL. When collapsed, the caret icon should be facing towards the text input.

LTR:

![image](https://github.com/patternfly/patternfly-react/assets/70952936/c67e65eb-cc11-47b3-a639-825e36832a41)

RTL:
![image](https://github.com/patternfly/patternfly-react/assets/70952936/3b2941c2-f0eb-4c3a-9324-a7cf9af21c07)

2023-09-15 12:26 UTC, thatblindgeye commented on packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
> +                    dir={isCode && 'ltr'}
Nit: a lot of places we'll spread an object for a case like this:

```suggestion
                    {...(isCode && { dir: 'ltr' })}
```

Both ways result in the same result, though, with the `dir` attribute not being applied at all if isCode isn't true, so not a blocker.

2023-09-15 14:41 UTC, thatblindgeye approved these changes

2023-09-15 14:42 UTC, thatblindgeye commented
Just needs snapshots updated but otherwise looks good

2023-09-18 14:11 UTC, wise-king-sullyman approved these changes

2023-09-19 15:55 UTC, tlabaj approved these changes
lgtm

2023-09-19 15:55 UTC, merged

2023-09-19 16:21 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.1.1-prerelease.13
 - @patternfly/react-core@5.1.1-prerelease.13
 - @patternfly/react-docs@6.1.1-prerelease.14
 - @patternfly/react-integration@5.1.1-prerelease.7
 - demo-app-ts@5.1.1-prerelease.12
 - @patternfly/react-table@5.1.1-prerelease.13

Thanks for your contribution! :tada: