fix(Nav): allow RTL scrolling
patternfly/patternfly-react pull request #9637
Opened 2023-09-18 17:39 UTC by kmcfaul

**What**: Closes #9607

2023-09-18 17:49 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9637.surge.sh

2023-09-19 14:04 UTC, wise-king-sullyman approved these changes

2023-09-19 15:58 UTC, thatblindgeye approved these changes

2023-09-20 15:33 UTC, tlabaj requested changes

2023-09-20 15:33 UTC, tlabaj commented on packages/react-core/src/components/Nav/NavList.tsx
> +  /** Aria-label for the back scroll button */
can you deprecate this and the `ariaRightScroll` prop and add `ariaBackScroll` and `ariaLeftScroll` props.

2023-09-21 16:06 UTC, tlabaj commented on packages/react-core/src/components/Nav/NavList.tsx
> +  /** @deprecated Aria-label for the left scroll button */
Can we mention which props to use instead.

2023-09-21 18:34 UTC, tlabaj approved these changes
LGTM

2023-09-21 18:35 UTC, merged