feat(Timestamp): allowed displayed datetime to be UTC
patternfly/patternfly-react pull request #9649
Opened 2023-09-19 17:45 UTC by thatblindgeye

**What**: Closes #9648 

**Additional issues**:

2023-09-19 17:53 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9649.surge.sh

2023-09-19 19:21 UTC, dlabaj requested changes
Date format doesn't say [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) when using the dateFormat / timeFormat.  Other then that looks good.
<img width="393" alt="Screenshot 2023-09-19 at 3 16 20 PM" src="https://github.com/patternfly/patternfly-react/assets/6126356/49b606a0-f43e-4f13-9416-1bb90e73a7b9">

2023-09-20 13:09 UTC, dlabaj approved these changes

2023-09-21 16:35 UTC, tlabaj approved these changes
LGTM

2023-09-21 16:36 UTC, merged

2023-09-21 16:58 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.1.1-prerelease.18
 - @patternfly/react-core@5.1.1-prerelease.18
 - @patternfly/react-docs@6.1.1-prerelease.19
 - demo-app-ts@5.1.1-prerelease.17
 - @patternfly/react-table@5.1.1-prerelease.18

Thanks for your contribution! :tada: