chore(TextInputGroup): allow input in basic example
patternfly/patternfly-react pull request #9650
Opened 2023-09-19 21:03 UTC by mfrances17

**What**: Closes #9588 

**Additional issues**:

2023-09-19 21:15 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9650.surge.sh

2023-09-21 17:03 UTC, kmcfaul requested changes
I would just discard the yarn.lock as it should not have changed, otherwise LGTM

2023-09-25 21:05 UTC, mfrances17 commented
Removed yarn.lock from the commit.

2023-10-09 13:44 UTC, gitdallas approved these changes

2023-10-09 14:02 UTC, kmcfaul approved these changes

2023-10-09 14:02 UTC, merged