docs(custom menu): add example with search input inline filtering
patternfly/patternfly-react pull request #9687
Opened 2023-09-27 12:35 UTC by adamviktora

**What**: Closes #9468

**Additional issues**:

- I think that **Context selector menu** examples should be updated both in [custom menus](https://www.patternfly.org/components/menus/custom-menus#context-selector-menu) and in the [context selector](https://www.patternfly.org/components/menus/context-selector) site too. Right now, it has following problems:

1. does not use instant filtering, you have to click on the search button instead (even _enter_ key does not work)
2. when scrolling down, search bar will not stick at place

We could update the Context selector, so it works very similarly to this "With search input filtering" menu, or even merge them into one improved Context selector example. What do you think?

2023-09-27 12:43 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9687.surge.sh

2023-10-09 17:44 UTC, mmenestr approved these changes
LGTM

2023-10-31 13:35 UTC, nicolethoen requested changes
the left + right arrow keys dont work in the inline search input. 
I think that was an issue that was fixed, so maybe this just needs a rebase. @kmcfaul do you happen to know?

also, can we call this an `inline search filter` in the title. I think that's how i've most often heard the feature called.

2023-11-06 19:37 UTC, nicolethoen approved these changes
This LGTM!

I think we can open an issue to track the issues you've noticed with the context selector demo.

2023-11-07 13:15 UTC, andrew-ronaldson reviewed
LGTM, thanks @adamviktora

2023-11-08 08:46 UTC, adamviktora commented
@nicolethoen I opened the context selector followup https://github.com/patternfly/patternfly-react/issues/9801

2023-11-13 15:50 UTC, gitdallas approved these changes

2023-11-14 18:39 UTC, kmcfaul approved these changes

2023-11-14 19:40 UTC, andrew-ronaldson approved these changes

2023-11-15 19:45 UTC, merged