fix(RTL): added right-to-left page demo
patternfly/patternfly-react pull request #9694
Opened 2023-09-28 15:51 UTC by mcoker

fixes https://github.com/patternfly/patternfly-react/issues/9550

2023-09-28 16:01 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9694.surge.sh

2023-10-02 20:41 UTC, gitdallas approved these changes
demo works. https://patternfly-react-pr-9694.surge.sh/patterns/rtl/react-demos/table-column-management/

some nits:

- tsx instead of jsx
- change table headers to hebrew too? or maybe the table itself is unnecessary? it just felt a bit odd when i hit "change to hebrew" and still saw english headings

2023-10-17 20:55 UTC, mcoker commented
@andrew-ronaldson the demo is in Hebrew - would Tal be able to review for us?

2023-10-20 20:21 UTC, srambach commented
I agree with Dallas's comment about mixing the language. One reason to translate is to see that things like the pagination are actually in the correct order, since they look off when in English.

2023-10-20 22:23 UTC, mcoker commented
@srambach thanks for looking! Looks like the build might not have run correctly? It doesn't appear to have the latest changes, like the example/URL name "Paginated table", it's still referencing the old "Table column management" name. Kicking off the build again

2023-10-23 13:21 UTC, srambach approved these changes
Looks super! 🦸

2023-10-27 20:16 UTC, kmcfaul approved these changes

2023-10-30 13:04 UTC, nicolethoen commented
LGTM! I'm curious if @tlabaj would want a React dev to walk through it and convert the demo to typescript, or if that should be done as a follow up?

2023-10-30 13:23 UTC, tlabaj requested changes
A couple of small comments.  Also like Dallas said could we change this to Typescript (.tsx rather than .jsx extension).

2023-10-30 13:23 UTC, tlabaj commented on packages/react-core/src/demos/RTL/RTL.md
> +id: RTL
Can we rename this to "Right-to-left" rather than the abbreviation.

2023-10-30 13:23 UTC, tlabaj commented on packages/react-core/src/demos/RTL/examples/PaginatedTable.jsx
> +                            <Td key={key} dataLabel={key === 'lastModified' ? 'Last modified' : capitalize(key)}>
I am not a fan of using undocumented helper functions in our demo code.  Can you create a new function for `capitalize` in the demo code instead.  That way the consumer has access to the code.

2023-10-31 19:03 UTC, mcoker commented
@tlabaj updated! Maybe we could have a follow up to convert to TS? Anyone is welcome to push to this PR if someone wants to contribute that change.

2023-11-02 13:16 UTC, srambach approved these changes

2023-11-02 13:38 UTC, andrew-ronaldson approved these changes
LGTM, thanks!

2023-11-02 14:49 UTC, merged

2023-11-02 15:14 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.2.0-prerelease.20
 - @patternfly/react-core@5.2.0-prerelease.20
 - @patternfly/react-docs@6.2.0-prerelease.20
 - demo-app-ts@5.1.1-prerelease.43
 - @patternfly/react-table@5.2.0-prerelease.20

Thanks for your contribution! :tada: