chore(DescriptionList): update tests
patternfly/patternfly-react pull request #9753
Opened 2023-10-16 17:36 UTC by kmcfaul

**What**: Closes #9673

2023-10-16 17:44 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9753.surge.sh

2023-10-20 19:07 UTC, thatblindgeye requested changes
Some initial comments below. We should also have each sub-component with its own test file, and for each we should add tests that check the default classes are rendered (currently the tests are only checking that a custom class renders)

2023-10-20 19:07 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
> +});
```suggestion
test('DescriptioinListTermHelpTextButton renders custom className', () => {
  render(
      <DescriptionListTermHelpTextButton className="custom">test</DescriptionListTermHelpTextButton>
  );
  expect(screen.getByText('test')).toHaveClass('custom');
});
```

2023-10-31 18:52 UTC, thatblindgeye requested changes

2023-10-31 18:52 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
> +import { render, screen } from '@testing-library/react';
Could we add additional tests to check that the `style` object is being applied correctly when the applicable props are possed? isHorizontal + horizontalTermWidthModifier, termWidth, and isAutoFit + autoFitMinModifier

2023-10-31 18:52 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
> +  expect(screen.getByLabelText('list')).toHaveClass(styles.descriptionList);
should be able to pass the exact option:

```suggestion
  expect(screen.getByLabelText('list')).toHaveClass(styles.descriptionList, {exact: true});
```

2023-10-31 18:52 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionListDescription.test.tsx
> +  expect(screen.getByText('test').parentElement).toHaveClass(styles.descriptionListDescription);
```suggestion
  expect(screen.getByText('test').parentElement).toHaveClass(styles.descriptionListDescription, {exact: true});
```

Also a test that spread props works correctly

2023-10-31 18:52 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionListGroup.test.tsx
> +  expect(screen.getByText('test')).toHaveClass(styles.descriptionListGroup);
```suggestion
  expect(screen.getByText('test')).toHaveClass(styles.descriptionListGroup, {exact: true});
```

Also a test that spread props works correclty

2023-10-31 18:52 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionListHelpText.test.tsx
> +  expect(screen.getByText('test')).toHaveClass(styles.descriptionListTerm);
```suggestion
  expect(screen.getByText('test')).toHaveClass(styles.descriptionListTerm, {exact: true});
```

Also a test to check props spread correctly. This file name should also be updated to `DescriptionListTermHelpText`

2023-10-31 18:52 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionListHelpTextButton.test.tsx
> +  expect(screen.getByText('test')).toHaveClass(styles.descriptionListText);
```suggestion
  expect(screen.getByText('test')).toHaveClass(styles.descriptionListText, {exact: true});
```

Also a test that props are spread correctly. File name should also be updated to `DescriptionListTermHelpTextButton`

2023-10-31 18:52 UTC, thatblindgeye commented on packages/react-core/src/components/DescriptionList/__tests__/DescriptionListTerm.test.tsx
> +  expect(screen.getByText('test').parentElement).toHaveClass(styles.descriptionListTerm);
```suggestion
  expect(screen.getByText('test').parentElement).toHaveClass(styles.descriptionListTerm, {exact: true});
```

Also a test for checking props spread correctly

2023-11-16 13:02 UTC, thatblindgeye approved these changes

2023-11-16 16:59 UTC, wise-king-sullyman approved these changes

2023-11-16 17:00 UTC, merged

2023-11-16 18:20 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.2.0-prerelease.30
 - @patternfly/react-core@5.2.0-prerelease.30
 - @patternfly/react-docs@6.2.0-prerelease.30
 - demo-app-ts@5.1.1-prerelease.53
 - @patternfly/react-table@5.2.0-prerelease.30

Thanks for your contribution! :tada: