chore(HelperText): update tests
patternfly/patternfly-react pull request #9761
Opened 2023-10-18 14:53 UTC by kmcfaul

**What**: Closes #9760

2023-10-18 15:03 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9761.surge.sh

2023-10-20 14:14 UTC, thatblindgeye requested changes
We should also have separate files for HelperText and HelperTextItem tests.

For Helper Text we should add tests for:
- id on HelperText is rendered
- a test for "renders without children" like Alert:
    https://github.com/patternfly/patternfly-react/blob/1194a7e9e99e6377906799f2c142c0b843112256/packages/react-core/src/components/Alert/__tests__/Alert.test.tsx#L29-L34
- spreads additional props correctly
- passing isLiveRegion sets the aria-live attribute

For HelperTextItem we should add tests for:
- renders without children like above
- renders with the default class on both the top level element (helperTextItem) and the element the text is rendered in (helperTextItemText)
- renders with passed id
- renders an icon when hasIcon is passed && icon is not passed (nice to have would be testing that there aren't 2 instances of the helperTextItemIcon when both hasIcon and icon are passed)
- the element is rendered with a div by default and renders with whatever is passed to `component`
- `screenReaderText` renders when it and isDynamic is passed

2023-10-20 14:14 UTC, thatblindgeye commented on packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
> +test('Renders as ul when component = ul', () => {
```suggestion
test('Renders with element passed to component prop', () => {
```

We should also have a test that checks the top element is a div by default

2023-10-20 14:14 UTC, thatblindgeye commented on packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
> +  expect(screen.getByText('help test text 1').parentElement?.tagName).toBe('LI');
Let's split this up into separate tests. This test should check that the `ul` tag is there, then for aria-label we can have tests for:

- checking the aria-label isn't rendered if the component is not ul
- checking the aria-label does get rendered when component = ul

We should also add a couple of tests that check the `role` attribute doesn't get applied when component is not ul, and that it does get applied when component = ul

2023-10-30 15:33 UTC, thatblindgeye reviewed
Thanks for the updates! Just a few more quick ones below

2023-10-30 15:33 UTC, thatblindgeye commented on packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
> +  expect(screen.getByText('text')).toHaveAttribute('id');
```suggestion
  expect(screen.getByText('text')).toHaveAttribute('id', 'helper-id');
```

2023-10-30 15:33 UTC, thatblindgeye commented on packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
> +  expect(screen.getByText('text')).toHaveAttribute('aria-live');
```suggestion
  expect(screen.getByText('text')).toHaveAttribute('aria-live', 'polite');
```

Could we also do the inverse, checking aria-live doesn't render by default?

2023-10-30 15:33 UTC, thatblindgeye commented on packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
> +  render(<HelperText>text </HelperText>);
Just need to pass another prop in here to test for

2023-10-30 15:33 UTC, thatblindgeye commented on packages/react-core/src/components/HelperText/__tests__/HelperTextItem.test.tsx
> +  expect(screen.getByText('help test text').querySelector('span')).toHaveClass('pf-v5-screen-reader');
Can we add another test to check that custom screenReaderText works

2023-10-30 15:33 UTC, thatblindgeye commented on packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
> +test('Renders with element passed to component prop', () => {
Just need a test that's the inverse to check it renders with a div by default

2023-11-15 20:05 UTC, tlabaj approved these changes
LGTM

2023-11-15 20:09 UTC, thatblindgeye approved these changes

2023-11-15 20:09 UTC, merged