chore(deps): Bump v6 branch to latest core alpha
patternfly/patternfly-react pull request #9774
Opened 2023-10-26 20:34 UTC by tlabaj

**What**: Closes #9411

**Additional issues**: towards #9675 and #9674 

- Bumped core alphas
-  Masthead:  Removed `backgroundColor` prop since light background is now the default with no option to change it.
- NotificationBadge:  `.pf-v5-c-notification-badge__count` no longer has a stye associated with it so I updated the code with hardcoded placeholder string.

2023-10-26 20:47 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9774.surge.sh

2023-10-27 20:05 UTC, mfrances17 requested changes
just some nits, copy/paste error in multiple places :)

2023-10-27 20:05 UTC, mfrances17 commented on packages/react-docs/package.json
> +,
move , to prev line

2023-10-27 20:05 UTC, mfrances17 commented on packages/react-icons/package.json
> +,
move , to prev line :)

2023-10-27 20:05 UTC, mfrances17 commented on packages/react-styles/package.json
> +,
same comment

2023-10-27 20:05 UTC, mfrances17 commented on packages/react-tokens/package.json
> +,
same comment

2023-10-31 14:03 UTC, nicolethoen commented
it'd be good to double check that any global tokens in the core repo are getting translated appropriately into react-tokens, just like the other css variables.

2023-11-02 13:59 UTC, srambach reviewed
Notification badges don't look quite right - there's a weird outline and the hover is wrong. But these are also slightly still in flight along with some button work from @mcoker
Page is getting a scrollbar that isn't there in core. That might take a little more investigation.

2023-11-06 19:33 UTC, nicolethoen reviewed
This is really cool!

couple quick questions:

I see that we are defining the token for blue_100 for example as:
```
export const _pf_t_color_blue_100 = {
  "name": "--pf-t--color--blue--100",
  "value": "#d9e9ff",
  "var": "var(--pf-t--color--blue--100)"
};
export default _pf_t_color_blue_100;
```

Will that eventually be renamed and somehow replace the coexisting global variable?:

```
export const global_palette_blue_100 = {
  "name": "--pf-v5-global--palette--blue-100",
  "value": "#bee1f4",
  "var": "var(--pf-v5-global--palette--blue-100)"
};
export default global_palette_blue_100;
```
EDIT: this might be exactly what your TODO in the PR description is referring to - so never mind :)

Also, the individual token files look good, but in patternfly_variables.js I see quite a few tokens that have `value: undefined` such as:
```
"_pf_t_global_color_nonstatus_orangered_100": {
      "name": "--pf-t--global--color--nonstatus--orangered--100",
      "value": "undefined",
      "values": [
        "--pf-t--color--orangered--200",
        "undefined"
      ]
    },
```
Is that expected?

2023-11-14 23:41 UTC, kmcfaul approved these changes

2023-11-15 16:21 UTC, srambach commented
I'm still seeing a difference in notification badge. I know there's an upcoming sprint to clean up notification badge but I don't know if there's a problem with what's in this PR or if it will be addressed. The workspace styles to make the dark background can be removed for sure.
<img width="121" alt="image" src="https://github.com/patternfly/patternfly-react/assets/19825616/cf727cec-a42f-48aa-a1ae-17ed6eb11712">

Otherwise, it looks ok to me and I'm fine moving forward and circling back.

2023-11-15 16:40 UTC, tlabaj commented
> I'm still seeing a difference in notification badge. I know there's an upcoming sprint to clean up notification badge but I don't know if there's a problem with what's in this PR or if it will be addressed. The workspace styles to make the dark background can be removed for sure. <img alt="image" width="121" src="https://user-images.githubusercontent.com/19825616/283180299-cf727cec-a42f-48aa-a1ae-17ed6eb11712.png">
> 
> Otherwise, it looks ok to me and I'm fine moving forward and circling back.

@srambach This can be addressed by the issue for notification badge #9811 
The goal of the PR was to pull in alphas, make sure it builds and make sure Tokens are generated correctly.

2023-11-15 16:41 UTC, srambach approved these changes

2023-11-15 18:38 UTC, mfrances17 approved these changes
LGTM

2023-11-15 18:38 UTC, merged