feat(Page): Added secondary variant styling for Penta work
patternfly/patternfly-react pull request #9848
Opened 2023-12-04 15:09 UTC by thatblindgeye

**What**: Closes #9808

**Additional issues**:

2023-12-04 15:19 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9848.surge.sh

2023-12-05 18:20 UTC, srambach approved these changes
LGTM 👍

2023-12-06 14:44 UTC, tlabaj requested changes
Can you update the examples to demonstrate this similar to what is done in cores examples
https://pf6.patternfly.org/components/page#vertical-nav
https://pf6.patternfly.org/components/page#horizontal-nav
https://pf6.patternfly.org/components/page#main-section-variations

2023-12-06 19:23 UTC, mmenestr approved these changes
LGTM!

2023-12-06 19:28 UTC, kmcfaul approved these changes

2023-12-06 19:46 UTC, merged

2023-12-06 20:10 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.0.0-alpha.4
 - @patternfly/react-core@6.0.0-alpha.4
 - @patternfly/react-docs@7.0.0-alpha.4
 - demo-app-ts@5.1.1-alpha.3
 - @patternfly/react-table@6.0.0-alpha.4

Thanks for your contribution! :tada: