chore(deps): Bump v6 alphas
patternfly/patternfly-react pull request #9881
Opened 2023-12-12 17:16 UTC by tlabaj

**What**: Closes #

**Additional issues**:

2023-12-12 17:26 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9881.surge.sh

2023-12-12 20:15 UTC, thatblindgeye requested changes
Looks good, just one change below

2023-12-12 20:21 UTC, tlabaj commented on packages/react-core/src/components/Pagination/Pagination.tsx
> -  isCompact?: boolean;
ok great!  I will update.

2023-12-13 20:22 UTC, thatblindgeye requested changes

2023-12-13 20:22 UTC, thatblindgeye commented on packages/react-core/src/components/Pagination/Pagination.tsx
> -        isCompact={isCompact}
We just need to add this back as well so it can be passed to the Navigation

2023-12-13 20:53 UTC, thatblindgeye approved these changes

2023-12-13 21:14 UTC, wise-king-sullyman approved these changes

2023-12-13 21:30 UTC, merged

2023-12-13 21:43 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-charts@8.0.0-alpha.4
 - @patternfly/react-code-editor@6.0.0-alpha.5
 - @patternfly/react-core@6.0.0-alpha.5
 - @patternfly/react-docs@7.0.0-alpha.5
 - @patternfly/react-icons@6.0.0-alpha.4
 - demo-app-ts@5.1.1-alpha.4
 - @patternfly/react-styles@6.0.0-alpha.4
 - @patternfly/react-table@6.0.0-alpha.5
 - @patternfly/react-tokens@6.0.0-alpha.4

Thanks for your contribution! :tada: