WIP: chore(expandablesection): Added a demo to show how to use expandable section to create an expandable text component.
patternfly/patternfly-react pull request #9887
Opened 2023-12-13 15:41 UTC by dlabaj

Added a demo to show how to use expandable section to create an expandable text component.

2023-12-13 15:52 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9887.surge.sh

2023-12-13 16:57 UTC, edonehoo commented on packages/react-core/src/demos/ExpandableSection/ExpandableSection.md
> +
```suggestion
### Expandable text with truncation

You can truncate long sections of text and add a "Show more" link that allows users to expand and view the view text content.

To specify the number of character shown prior to truncation, use a `<Truncate>` component and pass a `maxWidth` to the `style` attribute.

```

2023-12-13 17:56 UTC, fhlavac approved these changes
Looks good!

2024-01-02 21:18 UTC, thatblindgeye reviewed
One non-blocking nit I have is that we could update the demo name to "Expandable text with character truncation" to more immediately differentiate it from the existing truncate expansion, but wouldn't hold this up over that.

Otherwise only other thing is that Truncate adds a tooltip to the content, which we don't really need since we have the toggle to show the rest of the content. That could also be an issue if the truncated content is large since it'll create an equally large tooltip that would either just be a distraction or be cut off. Do we need to use a Truncate since this is more a demo showcasing how to achieve this result? I was able to get a similar (though possibly not perfect) result by using a div instead:

`<div style={{ maxWidth: '10ch' }}>{content}</div>`

We could also allow preventing a tooltip from with Truncate. I'd be hesitant about that being overridden since typically we should want that tooltip for truncated content, but a good prop description + a11y docs might offset that.

2024-01-03 14:21 UTC, andrew-ronaldson approved these changes
LGTM, thanks!

2024-01-03 18:49 UTC, edonehoo requested changes
small change per Eric's suggestion, which I +1

2024-01-03 18:49 UTC, edonehoo commented on packages/react-core/src/demos/ExpandableSection/ExpandableSection.md
> +### Expandable text with truncation
```suggestion
### Expandable text with character truncation
```

2024-01-03 18:51 UTC, evwilkin approved these changes
LGTM

With regard to @thatblindgeye comment about wrapping with a div vs using Truncate, I get the entire text block limited width as seen below - if any follow-up is needed we can open a new issue but IMO this is good to go as-is for now

https://github.com/patternfly/patternfly-react/assets/8651509/906cb2f7-c073-4338-b039-f536d737a489

2024-01-03 19:29 UTC, kmcfaul approved these changes

2024-01-03 21:10 UTC, mcoker approved these changes

2024-01-03 21:13 UTC, tlabaj approved these changes
LGTM.  @dlabaj is out.  We can talk to him about your suggestion and follow up if needed once he returns

2024-01-04 18:31 UTC, merged

2024-01-04 18:44 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@5.2.0-prerelease.40
 - @patternfly/react-core@5.2.0-prerelease.40
 - @patternfly/react-docs@6.2.0-prerelease.40
 - demo-app-ts@5.1.1-prerelease.63
 - @patternfly/react-table@5.2.0-prerelease.40

Thanks for your contribution! :tada: