feat(SimpleList): penta updates
patternfly/patternfly-react pull request #9953
Opened 2024-01-09 20:01 UTC by kmcfaul

**What**: Closes #9926

Added new modifier class when `SimpleListItem` is a link.

2024-01-09 20:07 UTC, patternfly-build commented
Preview: https://patternfly-react-pr-9953.surge.sh

2024-01-12 15:45 UTC, wise-king-sullyman approved these changes
LGTM, I'd love to see a test for the link modifier being applied correctly but since this looks like its tests haven't been revamped yet I won't block for it.

2024-01-12 15:56 UTC, thatblindgeye approved these changes

2024-01-12 16:07 UTC, lboehling requested changes
It looks like the selected item isn't getting the background color change. It should present the same as hover, but use the action--plain--selected token.

2024-01-16 15:49 UTC, kmcfaul commented
@lboehling This has been fixed on the core side and should update automatically when react updates to that core version.

2024-01-17 19:28 UTC, mcoker approved these changes
LGTM other than the core bump needed to fix the current background color.

2024-01-19 21:55 UTC, tlabaj commented
@kmcfaul if you rebase this one it should have the fix from core

2024-01-22 16:32 UTC, merged

2024-01-22 16:44 UTC, patternfly-build commented
Your changes have been released in: 
 - @patternfly/react-code-editor@6.0.0-alpha.18
 - @patternfly/react-core@6.0.0-alpha.18
 - @patternfly/react-docs@7.0.0-alpha.19
 - demo-app-ts@5.1.1-alpha.17
 - @patternfly/react-table@6.0.0-alpha.18

Thanks for your contribution! :tada: